import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";
import generalAndSportCourses from "../shared/general-and-sport-courses.json";

const generalStudiesCourses: Course[] = generalAndSportCourses.general.map((course) => ({
  ...course,
  type: "general",
  required: false,
  requirementGroup: "general-studies",
}));

const sportCourses: Course[] = generalAndSportCourses.sport.map((course) => ({
  ...course,
  type: "sport",
  required: false,
  requirementGroup: "sport-elective",
}));

const clusters: ElectiveCluster[] = [
  {
    id: "math-electives",
    name: "אשכול קורסי בחירה מתמטיים",
    minCourses: 2,
    note: "חובה לצבור לפחות 6.0 נ\"ז (שני קורסים לפחות) מאשכול זה.",
  },
  {
    id: "stage-1",
    name: "אשכול קורסי בחירה שלב 1",
    minCourses: 0,
    note: "בחירה חופשית בכפוף לעמידה בקורסי הקדם; אין מספר מינימלי קבוע לאשכול זה.",
  },
  {
    id: "stage-2",
    name: "אשכול קורסי בחירה שלב 2",
    minCourses: 0,
    note: "קורסי קדם באשכול זה נשענים לרוב על קורסי שלב 1; יש להקפיד על סדר השלבים.",
  },
  {
    id: "stage-3",
    name: "אשכול קורסי בחירה שלב 3",
    minCourses: 0,
    note: "קורסי קדם באשכול זה נשענים לרוב על קורסי שלב 2; יש להקפיד על סדר השלבים.",
  },
  {
    id: "stage-4",
    name: "אשכול קורסי בחירה שלב 4",
    minCourses: 0,
    note: "קורסי קדם באשכול זה נשענים על קורסי שלב 3; יש להקפיד על סדר השלבים.",
  },
  {
    id: "entrepreneurship",
    name: "אשכול קורסי בחירה בתחום היזמות",
    minCourses: 0,
    note: "בחירה חופשית; אינו נכלל בדרישת קורסי הבחירה המתמטיים.",
  },
];

const p = (ids: string[], label?: string) => ({ mode: "all" as const, ids, label });
const any = (ids: string[], label: string) => ({
  mode: "any" as const,
  ids,
  label,
});

const courses: Course[] = [
  // --- English placement / exemption pseudo-courses ---
  {
    id: "ENG_BASIC_OK",
    name: "פטור/סיווג מאנגלית בסיסית",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שאינם צריכים ללמוד 11063 בפועל."],
  },
  {
    id: "ENG_ADV_A_OK",
    name: "פטור/סיווג מאנגלית מתקדמים א",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שמתחילים מאנגלית מתקדמים ב או מעליה."],
  },
  {
    id: "ENG_ADV_B_OK",
    name: "פטור/סיווג מאנגלית מתקדמים ב",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11059",
    notes: ["מיועד לסטודנטים הפטורים מכל חובות האנגלית עד רמת מתקדמים ב (כולל)."],
  },

  // --- Semester 1 ---
  {
    id: "11002",
    name: "אלגברה מ",
    credits: 5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11004",
    name: "חדו\"א 1 מ",
    credits: 5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11063",
    name: "אנגלית בסיסי",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [],
    notes: ["לפי ציון פרק האנגלית בבחינה הפסיכומטרית (90-99); אינו נספר בסיכום נ\"ז בפועל."],
  },
  {
    id: "11064",
    name: "אנגלית מתקדמים א'",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסית או פטור/סיווג")],
    notes: ["לפי ציון פרק האנגלית בבחינה הפסיכומטרית (100-119) או השלמת 11063."],
  },
  {
    id: "11179",
    name: "מבוא לפיזיקה אקדמית",
    credits: 0,
    type: "required",
    semester: 1,
    prerequisites: [],
    notes: [
      "סטודנטים שלמדו פיזיקה ברמת 5 יח\"ל וקיבלו ציון 75 ומעלה פטורים מקורס זה.",
      "הקורס מוצע גם בסמסטר קיץ.",
    ],
  },
  {
    id: "61743",
    name: "מתמטיקה דיסקרטית 1",
    credits: 3,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "61741",
    name: "מבוא למדעי המחשב",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
    notes: ["לחסרי רקע בתכנות מומלץ להצטרף לסדנת הכנה."],
  },
  {
    id: "201154",
    name: "סמינר בנושאים במתמטיקה",
    credits: 1,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "251961",
    name: "מיומנויות יסוד הנדסיות",
    credits: 1,
    type: "required",
    required: true,
    semester: 1,
    notes: ["קורס זה אינו מופיע בטבלת סמסטר 1 הרשמית, אך נדרש בשנה הראשונה ללימודים."],
  },

  // --- Semester 2 ---
  {
    id: "11006",
    name: "חדו\"א 2 מ",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11004"])],
    coRequisites: ["11002"],
  },
  {
    id: "11209",
    name: "פיזיקה 1 IE",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11179"])],
  },
  {
    id: "61745",
    name: "מבוא לתכנות מערכות (מת\"מ)",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["61741"])],
  },
  {
    id: "201005",
    name: "משוואות דיפרנציאליות רגילות מש",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11004", "11002"])],
  },
  {
    id: "201174",
    name: "אלגברה לינארית 2",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11002"])],
  },

  // --- Semester 3 ---
  {
    id: "11059",
    name: "אנגלית מתקדמים ב'",
    credits: 2,
    type: "english",
    required: true,
    semester: 3,
    prerequisites: [
      any(["11064", "ENG_ADV_A_OK"], "אנגלית מתקדמים א' או ציון פסיכומטרי באנגלית 120-133"),
    ],
  },
  {
    id: "11210",
    name: "פיזיקה 2 IE",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11209"])],
    coRequisites: ["11006"],
  },
  {
    id: "51900",
    name: "תורת ההסתברות מש",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11004", "61743"])],
  },
  {
    id: "201009",
    name: "אנליזה נומרית מש",
    credits: 5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["201005", "61745"])],
  },
  {
    id: "201176",
    name: "מבוא לאנליזה",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11006", "11002"])],
  },
  {
    id: "201178",
    name: "מבוא לאופטימיזציה",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11006"])],
    coRequisites: ["201174"],
  },

  // --- Semester 4 ---
  {
    id: "51901",
    name: "תהליכים אקראיים מש",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["51900", "201005"])],
  },
  {
    id: "61739",
    name: "מבני נתונים ומבוא לאלגוריתמים",
    credits: 4,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [
      any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסית או פטור/סיווג מתאים"),
      p(["61745", "61743"]),
    ],
  },
  {
    id: "201007",
    name: "פונקציות מרוכבות מש",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11006", "11002"])],
  },
  {
    id: "201008",
    name: "טורי פורייה והתמרות אינטגרליות מש",
    credits: 4,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11006", "201174"])],
  },
  {
    id: "201015",
    name: "אלגברה מודרנית",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11002"])],
  },

  // --- Semester 5 ---
  {
    id: "201006",
    name: "משוואות דיפרנציאליות חלקיות מש",
    credits: 4,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["201005", "11006"])],
  },
  {
    id: "201180",
    name: "מערכות דינמיות מרוכבות",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["201005", "201007"])],
  },

  // --- Semester 6 ---
  {
    id: "201163",
    name: "בניית מודלים מתמטיים",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["51900", "201005"])],
  },
  {
    id: "201100",
    name: "פרויקט מסכם",
    credits: 3,
    type: "required",
    required: true,
    semester: 6,
    notes: ["לא צוינו קורסי קדם ספציפיים בטבלת המקור."],
  },

  // --- Math electives (קורסי בחירה מתמטיים) ---
  {
    id: "201012",
    name: "מכניקת רצף",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["11210", "201006"])],
  },
  {
    id: "201013",
    name: "תורת הכאוס",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201006", "201180"])],
  },
  {
    id: "201014",
    name: "אלמנטים של אנליזה פונקציונלית",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201176"])],
  },
  {
    id: "201016",
    name: "פונקציות מוכללות",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201005", "201008"])],
  },
  {
    id: "201017",
    name: "תורה איכותית של משוואות דיפרנציאליות",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201005", "201176"])],
  },
  {
    id: "201018",
    name: "חשבון ווריאציות",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["11006", "201005"])],
  },
  {
    id: "201020",
    name: "תורת הקירובים",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201008", "201009"])],
  },
  {
    id: "201182",
    name: "מבוא לחבורות ושדות",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201015", "201174"])],
  },
  {
    id: "201184",
    name: "תבניות דיפרנציאליות על יריעות",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["11002", "11006"])],
  },
  {
    id: "201186",
    name: "מבוא לחבורות לי של מטריצות",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["11006", "201174"])],
  },
  {
    id: "201188",
    name: "מבוא לגיאומטריה דיפרנציאלית",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["11006", "11002"])],
  },
  {
    id: "201190",
    name: "מבוא לטופולוגיה וטופולוגיה אלגברית",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201015", "201174"])],
  },
  {
    id: "201192",
    name: "נושאים באנליזה הרמונית ו-Wavelets",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201008"])],
  },
  {
    id: "201194",
    name: "מערכות מכניות וסימטריות",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["11006", "201174"])],
  },
  {
    id: "201196",
    name: "בעיות שאינן מוגדרות היטב",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201006"])],
  },
  {
    id: "201198",
    name: "תורת המשחקים",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201005", "201178"])],
    notes: ["ניתן לצבור נ\"ז עבור קורס אחד בלבד מבין 201198 ו-61957."],
  },
  {
    id: "61957",
    name: "תורת המשחקים",
    credits: 3,
    type: "elective",
    clusterId: "math-electives",
    prerequisites: [p(["201005", "201178"])],
    notes: [
      "ניתן לצבור נ\"ז עבור קורס אחד בלבד מבין 201198 ו-61957.",
      "קורס זה יכול להיחשב כקורס בחירה כללי או כקורס בחירה מתמטי, לפי בחירת הסטודנט.",
      "מופיע גם ברשימת קורסי בחירה שלב 1 עם קורסי קדם חלופיים המתועדים שם: 11002, 61743, 51900.",
    ],
  },

  // --- Stage 1 electives (קורסי בחירה שלב 1) ---
  {
    id: "31245",
    name: "למידה עמוקה",
    credits: 3.5,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["61739"])],
  },
  {
    id: "31430",
    name: "רשתות ומערכות בדידות",
    credits: 2.5,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["201008"])],
    notes: ["לא ניתן לצבור נ\"ז בשילוב עם קורס 61761."],
  },
  {
    id: "51525",
    name: "כריית נתונים",
    credits: 2.5,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["51900", "61741"])],
  },
  {
    id: "51703",
    name: "מודלים סטוכסטיים בחקב\"צ",
    credits: 4,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["11006", "51900"])],
  },
  {
    id: "51723",
    name: "סטטיסטיקה",
    credits: 4.5,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["51900"])],
  },
  {
    id: "51958",
    name: "סטטיסטיקה למערכות מידע",
    credits: 3.5,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["51900"])],
  },
  {
    id: "61740",
    name: "מערכות ספרתיות",
    credits: 2.5,
    type: "elective",
    clusterId: "stage-1",
  },
  {
    id: "61750",
    name: "מבוא להנדסת תוכנה",
    credits: 4,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["61741"])],
  },
  {
    id: "61755",
    name: "מערכות מסדי נתונים מ",
    credits: 4,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["61739"])],
  },
  {
    id: "61778",
    name: "לוגיקה להנדסת תוכנה",
    credits: 3,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["61743"])],
  },
  {
    id: "61958",
    name: "תורת המידע",
    credits: 3,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["51900"])],
  },
  {
    id: "61975",
    name: "דחיסת נתונים",
    credits: 2.5,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["51900", "61739", "201174"])],
  },
  {
    id: "61989",
    name: "מחשבים קוונטיים",
    credits: 3,
    type: "elective",
    clusterId: "stage-1",
    prerequisites: [p(["201174"])],
  },

  // --- Stage 2 electives (קורסי בחירה שלב 2) ---
  {
    id: "61751",
    name: "תכנות מונחה עצמים",
    credits: 3.5,
    type: "elective",
    clusterId: "stage-2",
    prerequisites: [p(["61739", "61750"])],
  },
  {
    id: "61753",
    name: "אלגוריתמים",
    credits: 5,
    type: "elective",
    clusterId: "stage-2",
    prerequisites: [p(["11006", "61739", "61778", "201174"])],
  },
  {
    id: "61764",
    name: "גרפיקה ממוחשבת",
    credits: 3,
    type: "elective",
    clusterId: "stage-2",
    prerequisites: [p(["11002", "61745"])],
  },
  {
    id: "61774",
    name: "יסודות המחשוב",
    credits: 4,
    type: "elective",
    clusterId: "stage-2",
    prerequisites: [p(["61740", "61750"])],
  },

  // --- Stage 3 electives (קורסי בחירה שלב 3) ---
  {
    id: "61759",
    name: "אוטומטים וחישוביות",
    credits: 5,
    type: "elective",
    clusterId: "stage-3",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61761",
    name: "כריית נתונים ומערכות לומדות",
    credits: 4,
    type: "elective",
    clusterId: "stage-3",
    prerequisites: [p(["51900", "61753"])],
    notes: ["לא ניתן לצבור נ\"ז בשילוב עם קורס 31430."],
  },
  {
    id: "61767",
    name: "אבטחת מידע וקריפטולוגיה",
    credits: 4,
    type: "elective",
    clusterId: "stage-3",
    prerequisites: [p(["61753", "201015", "201174"])],
  },
  {
    id: "61775",
    name: "מבוא לבינה מלאכותית",
    credits: 2.5,
    type: "elective",
    clusterId: "stage-3",
    prerequisites: [p(["51900", "61753"])],
  },
  {
    id: "61965",
    name: "ניתוח של נתוני הרשתות",
    credits: 2.5,
    type: "elective",
    clusterId: "stage-3",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61996",
    name: "אלגוריתמים מבוזרים",
    credits: 2.5,
    type: "elective",
    clusterId: "stage-3",
    prerequisites: [p(["61753"])],
  },

  // --- Stage 4 electives (קורסי בחירה שלב 4) ---
  {
    id: "61763",
    name: "תורת הקומפילציה",
    credits: 2.5,
    type: "elective",
    clusterId: "stage-4",
    prerequisites: [p(["61759"])],
  },

  // --- Entrepreneurship electives (קורסי בחירה בתחום היזמות) ---
  {
    id: "251506",
    name: "מבוא לקניין רוחני",
    credits: 2,
    type: "elective",
    clusterId: "entrepreneurship",
  },
  {
    id: "251104",
    name: "מבוא ליזמות מורחב",
    credits: 2,
    type: "elective",
    clusterId: "entrepreneurship",
  },
  {
    id: "251509",
    name: "חשיבה המצאתית",
    credits: 2,
    type: "elective",
    clusterId: "entrepreneurship",
    prerequisites: [p(["201008"])],
  },
  {
    id: "251513",
    name: "חשיבה יצירתית שיטתית",
    credits: 2,
    type: "elective",
    clusterId: "entrepreneurship",
  },
  {
    id: "251895",
    name: "תעשייה 4.0 בשילוב התנסות",
    credits: 3,
    type: "elective",
    clusterId: "entrepreneurship",
    notes: ["קורס קדם לא צוין במקור."],
  },
  {
    id: "251965",
    name: "מהנדסים למען הגיל השלישי",
    credits: 2,
    type: "elective",
    clusterId: "entrepreneurship",
    notes: ["קורס קדם לא צוין במקור."],
  },
  ...generalStudiesCourses,
  ...sportCourses,
];

export const degreePlan: DegreePlan = {
  id: "applied-mathematics",
  title: "מפת תואר מתמטיקה שימושית",
  subtitle: "המכללה האקדמית להנדסה בראודה - תוכנית תלת-שנתית (שנתון תשפ\"ד)",
  catalogYear: 'תשפ"ד (2023-2024)',
  status: "archived",
  source: {
    fileName: "ידיעונים, שנתונים ולוח שנה אקדמית - בראודה.pdf",
    pages: "123-132",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 120,
    fixedDegreeCredits: 102,
    electiveCreditsNeeded: 18,
    generalCredits: 4,
    sportCredits: 1,
    englishRequiredIds: ["11059"],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [
    {
      code: "math-electives-min",
      name: "מינימום קורסי בחירה מתמטיים",
      kind: "credits",
      requiredCredits: 6,
      minCourses: 2,
      courseIds: [
        "201012",
        "201013",
        "201014",
        "201016",
        "201017",
        "201018",
        "201020",
        "201182",
        "201184",
        "201186",
        "201188",
        "201190",
        "201192",
        "201194",
        "201196",
        "201198",
        "61957",
      ],
    },
    {
      code: "general-studies",
      name: "לימודים כלליים",
      kind: "credits",
      requiredCredits: 4,
    },
    {
      code: "sport-elective",
      name: "ספורט",
      kind: "credits",
      requiredCredits: 1,
    },
  ],
  clusters,
  courses,
  rules: [
    {
      id: "math-games-mutual-exclusion",
      type: "mutual_exclusion",
      message: "ניתן לצבור נ\"ז עבור קורס אחד בלבד מבין 201198 ו-61957 (שניהם 'תורת המשחקים').",
      payload: { courseIds: ["201198", "61957"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "networks-datamining-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לצבור נ\"ז בשילוב בין קורס 31430 (רשתות ומערכות בדידות) לקורס 61761 (כריית נתונים ומערכות לומדות).",
      payload: { courseIds: ["31430", "61761"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-basic-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית בסיסי וגם פטור/סיווג מאנגלית בסיסית.",
      payload: { courseIds: ["11063", "ENG_BASIC_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים א וגם פטור/סיווג מאנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים א חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים ב וגם פטור/סיווג מאנגלית מתקדמים ב.",
      payload: { courseIds: ["11059", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-advanced-a",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-exemptions-single-choice",
      type: "mutual_exclusion",
      message: "ניתן לבחור פטור/סיווג אנגלית אחד בלבד: בסיסי, מתקדמים א או מתקדמים ב.",
      payload: { courseIds: ["ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
  ],
  notes: [
    "לצורך זכאות לתואר יש לצבור 120 נ\"ז: 96.0 נ\"ז קורסי חובה, 4.0 נ\"ז קורסים כלליים (שני קורסים), 1.0 נ\"ז ספורט, ו-1.0 נ\"ז מיומנויות יסוד הנדסיות (251961, נלמד בשנה הראשונה); היתרה מושלמת בקורסי בחירה חופשיים.",
    "מתוך קורסי הבחירה חובה לצבור לפחות 6.0 נ\"ז (שני קורסים לפחות) מאשכול קורסי הבחירה המתמטיים; יתר קורסי הבחירה ניתן להשלים בחופשיות מבין אשכולות השלבים (1-4) ואשכול היזמות, תוך הקפדה על סדר השלבים שמבטיח את קיום קורסי הקדם הנדרשים לקורסי הבחירה בשלבים הבאים.",
    "קורסי לימודים כלליים וספורט אינם משובצים לסמסטר קבוע בתוכנית הרשמית; ניתן לשלבם לאורך כל תקופת הלימודים.",
    "שרשרת לימודי האנגלית (אנגלית בסיסי ← אנגלית מתקדמים א' ← אנגלית מתקדמים ב') נקבעת לפי ציון פרק האנגלית בבחינה הפסיכומטרית; פטור מלא ניתן החל מציון 134 ומעלה. החל משנת תשפ\"ב הסטודנטים מחויבים בשני קורסי אנגלית, לפחות אחד מהם קורס תוכן.",
    "סטודנטים שלמדו פיזיקה ברמת 5 יח\"ל וקיבלו ציון 75 ומעלה פטורים מקורס 11179 (מבוא לפיזיקה אקדמית); הקורס מוצע גם בסמסטר קיץ.",
    "לחסרי רקע בתכנות (לקראת קורס 61741 מבוא למדעי המחשב) מומלץ להצטרף לסדנת הכנה.",
    "התוכנית המובאת כאן מתייחסת למתקבלים לסמסטר חורף. קיימת תוכנית מקבילה למתקבלים בסמסטר אביב, המסדרת מחדש את אותם הקורסים (למשל ללא קורס 201154 בסמסטר הראשון, סה\"כ 17.0 נ\"ז) מבלי להוסיף קורסים, קדמים או צמודים חדשים.",
    "קורסי 201198 ו-61957 (שניהם בשם 'תורת המשחקים') חופפים בתוכן: ניתן לצבור נ\"ז עבור אחד מהם בלבד. קורס 61957 יכול להיחשב כקורס בחירה כללי או כקורס בחירה מתמטי, לפי בחירת הסטודנט.",
    "קורס 31430 (רשתות ומערכות בדידות) וקורס 61761 (כריית נתונים ומערכות לומדות) חופפים בתוכן: לא ניתן לצבור נ\"ז עבור שניהם.",
    "קיים פער קטן (כ-5 נ\"ז) בין סיכום נ\"ז קורסי החובה המצוין בפתיח הפרק (96.0 נ\"ז) לבין סכימת הנ\"ז בפועל מטבלאות הסמסטרים (כ-91.0 נ\"ז); ייתכן שנובע מהבדל בין מהדורות השנתון. הנתונים כאן מוצגים במדויק לפי המקור המתועד.",
    "המסמך הרשמי עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
