import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";

const generalAndSportCourses = require("../shared/general-and-sport-courses.json") as {
  general: { id: string; name: string; credits: number }[];
  sport: { id: string; name: string; credits: number }[];
};

const generalStudiesCourses: Course[] = generalAndSportCourses.general.map((course) => ({
  ...course,
  type: "general",
  required: false,
  requirementGroup: "general-studies",
}));

const sportCourses: Course[] = generalAndSportCourses.sport.map((course) => ({
  ...course,
  type: "sport",
  required: false,
  requirementGroup: "sport-elective",
}));

const clusters: ElectiveCluster[] = [
  {
    id: "spec-environment",
    name: "התמחות בביו-טכנולוגיה של סביבה",
    minCourses: 5,
    note: "כלל קורסי החובה במסלול; יש לבחור מסלול התמחות אחד בלבד מתוך שלושת מסלולי ההתמחות.",
  },
  {
    id: "spec-food",
    name: "התמחות בביוטכנולוגיה של מזון",
    minCourses: 5,
    note: "כלל קורסי החובה במסלול; יש לבחור מסלול התמחות אחד בלבד מתוך שלושת מסלולי ההתמחות.",
  },
  {
    id: "spec-pharma",
    name: "התמחות בביוטכנולוגיה מולקולרית-תרופתית",
    minCourses: 6,
    note: "כלל קורסי החובה במסלול; יש לבחור מסלול התמחות אחד בלבד מתוך שלושת מסלולי ההתמחות.",
  },
  {
    id: "dept-electives",
    name: "קורסי בחירה מחלקתיים",
    minCourses: 1,
    note: "רשימת בחירה מחלקתית משותפת אחת (אינה מחולקת לאשכולות בשנתון); יש להשלים נ\"ז בחירה עד 165 נ\"ז בכפוף לתנאי הקדם. הקורסים אינם ניתנים בהכרח כל שנה או בכל סמסטר.",
  },
];

const p = (ids: string[], label?: string) => ({ mode: "all" as const, ids, label });
const any = (ids: string[], label: string) => ({
  mode: "any" as const,
  ids,
  label,
});

const entrepreneurshipCapNote =
  "מקבץ קורסי היזמות: מותר לצבור עד 2 נ\"ז בלבד ממקבץ זה (251504/251506/251507/251508/251512/251513/251514).";
const researchProjectCapNote =
  "ניתן לצבור עד 5 נ\"ז מקורסי הפרויקט/סמינריון 41763, 41764, 41766, בכפוף לאישור יועץ אקדמי.";

const courses: Course[] = [
  // --- Placement / exemption pseudo-courses (English chain + physics intro) ---
  {
    id: "ENG_BASIC_OK",
    name: "פטור/סיווג מאנגלית בסיסית",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11063",
    notes: ["מיועד לסטודנטים עם ציון פסיכומטרי באנגלית 100 ומעלה, שאינם צריכים ללמוד 11063 בפועל."],
  },
  {
    id: "ENG_ADV_A_OK",
    name: "פטור/סיווג מאנגלית מתקדמים א",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11064",
    notes: ["מיועד לסטודנטים עם ציון פסיכומטרי באנגלית 120 ומעלה, שמתחילים מאנגלית מתקדמים ב או מעליה."],
  },
  {
    id: "ENG_ADV_B_OK",
    name: "פטור/סיווג מאנגלית מתקדמים ב",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11058",
    notes: [
      "מיועד לסטודנטים עם ציון פסיכומטרי באנגלית 134 ומעלה, הפטורים מכל חובות האנגלית.",
      "אף עם פטור מלא, חובה ללמוד שני קורסי תוכן באנגלית.",
    ],
  },
  {
    id: "PHYS_INTRO_OK",
    name: "פטור ממבוא לפיזיקה אקדמית",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11179",
    notes: ["פטור יינתן למי שקיבל ציון 75 ומעלה ברמה של 5 יח\"ל בפיזיקה, או שעבר קורס הכנה במכינת קדם-הנדסה במכללה."],
  },

  // --- Semester 1 ---
  { id: "11001", name: "אלגברה", credits: 4.0, type: "required", required: true, semester: 1 },
  { id: "11003", name: "חדו\"א 1", credits: 5.0, type: "required", required: true, semester: 1 },
  {
    id: "11058",
    name: "אנגלית מתקדמים ב'",
    credits: 2.0,
    type: "english",
    required: true,
    semester: 1,
    prerequisites: [any(["11064", "ENG_ADV_A_OK"], "אנגלית מתקדמים א' או פטור/סיווג מתאים")],
    notes: ["לפי ציון פסיכומטרי באנגלית 120-133 או השלמת 11064."],
  },
  {
    id: "11063",
    name: "אנגלית בסיסי",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [],
    notes: ["לפי ציון פסיכומטרי באנגלית 85-99."],
  },
  {
    id: "11064",
    name: "אנגלית מתקדמים א'",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסי או פטור/סיווג מתאים")],
    notes: ["לפי ציון פסיכומטרי באנגלית 100-119 או השלמת 11063."],
  },
  {
    id: "11179",
    name: "מבוא לפיזיקה אקדמית",
    credits: 0,
    type: "required",
    semester: 1,
    prerequisites: [],
    notes: ["פטור יינתן למי שקיבל ציון 75 ומעלה ברמה של 5 יח\"ל בפיזיקה, או שעבר קורס הכנה במכינת קדם-הנדסה."],
  },
  { id: "41014", name: "כימיה כללית ואנליטית 1", credits: 3.5, type: "required", required: true, semester: 1 },
  { id: "41113", name: "ביולוגיה של התא", credits: 4.0, type: "required", required: true, semester: 1 },
  { id: "41201", name: "צוהר להנדסת ביוטכנולוגיה", credits: 1.5, type: "required", required: true, semester: 1 },
  {
    id: "251961",
    name: "מיומנויות יסוד הנדסיות",
    credits: 1.0,
    type: "required",
    required: true,
    semester: 1,
    notes: ["חובה ללמוד בסמסטר 1 או בסמסטר 2."],
  },
  // --- Semester 2 ---
  {
    id: "11005",
    name: "חדו\"א 2",
    credits: 5.0,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11003"])],
    coRequisites: ["11001"],
  },
  {
    id: "11023",
    name: "פיזיקה 1ב",
    credits: 3.0,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [any(["11179", "PHYS_INTRO_OK"], "מבוא לפיזיקה אקדמית או פטור מתאים")],
    coRequisites: ["11003"],
  },
  {
    id: "41012",
    name: "מעבדה בכימיה כללית ואנליטית",
    credits: 1.0,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["41014"])],
    coRequisites: ["41016"],
  },
  {
    id: "41016",
    name: "כימיה כללית ואנליטית 2",
    credits: 3.0,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["41014"])],
  },
  {
    id: "41050",
    name: "כימיה אורגנית 1",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["41014"])],
  },
  { id: "41421", name: "תכנות הנדסי ואלגוריתמיקה", credits: 3.0, type: "required", required: true, semester: 2 },
  {
    id: "51701",
    name: "מבוא להסתברות וסטטיסטיקה",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 2,
    coRequisites: ["11003"],
  },

  // --- Semester 3 ---
  {
    id: "11136",
    name: "משוואות דיפרנציאליות ב",
    credits: 4.0,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11001", "11005"])],
  },
  {
    id: "41041",
    name: "תרמודינמיקה וקינטיקה ב",
    credits: 3.0,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11003", "41016"])],
    coRequisites: ["41012"],
  },
  {
    id: "41060",
    name: "כימיה אורגנית 2",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["41050"])],
  },
  {
    id: "41064",
    name: "כימיה אורגנית - מעבדה",
    credits: 1.0,
    type: "required",
    required: true,
    semester: 3,
    coRequisites: ["41060"],
  },
  {
    id: "41231",
    name: "מיקרוביולוגיה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["41113"])],
    coRequisites: ["41232"],
  },
  {
    id: "41232",
    name: "מעבדות מיקרוביולוגיה",
    credits: 0.75,
    type: "required",
    required: true,
    semester: 3,
    coRequisites: ["41231"],
  },
  {
    id: "41305",
    name: "ביוכימיה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["41016"])],
    coRequisites: ["41060"],
  },
  {
    id: "41411",
    name: "מאזן חומר ואנרגיה",
    credits: 3.0,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11023"])],
    coRequisites: ["41041"],
  },

  // --- Semester 4 ---
  {
    id: "11026",
    name: "פיזיקה 2ב",
    credits: 3.0,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11023"])],
    coRequisites: ["11005"],
  },
  {
    id: "41162",
    name: "מעבדה בביולוגיה מולקולרית",
    credits: 1.0,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["41232"])],
    coRequisites: ["41163"],
  },
  {
    id: "41163",
    name: "ביולוגיה מולקולרית והנדסה גנטית",
    credits: 4.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["41231"])],
    coRequisites: ["41305"],
  },
  {
    id: "41335",
    name: "מטבוליזם ואנזימולוגיה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["41060", "41041", "41305"])],
  },
  {
    id: "41345",
    name: "מעבדה בביוכימיה",
    credits: 1.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["41064"])],
    coRequisites: ["41335"],
  },
  {
    id: "41431",
    name: "מכניקת זורמים",
    credits: 4.0,
    type: "required",
    required: true,
    semester: 4,
    coRequisites: ["41411"],
  },
  {
    id: "51725",
    name: "מודלים סטטיסטיים לביוטכנולוגיה",
    credits: 1.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["51701"])],
  },
  // --- Semester 5 ---
  {
    id: "41181",
    name: "אימונולוגיה",
    credits: 2.0,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["41163", "11058"])],
    notes: ["קורס זה נלמד באנגלית ומהווה קורס תוכן באנגלית."],
  },
  {
    id: "41182",
    name: "מעבדה באימונולוגיה",
    credits: 0.5,
    type: "required",
    required: true,
    semester: 5,
    coRequisites: ["41181"],
  },
  {
    id: "41412",
    name: "עקרונות מעבר חום",
    credits: 4.0,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["41431"])],
  },
  {
    id: "41443",
    name: "מעבדה בפעולות יסוד בהנדסה כימית",
    credits: 1.0,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["41431"])],
    coRequisites: ["41412"],
  },
  {
    id: "41452",
    name: "סמינר מחלקתי בתהליכים ביוטכנולוגיים תעשייתיים 1",
    credits: 0,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["41163"])],
    notes: ["חובת נוכחות (קורס ללא נ\"ז)."],
  },
  {
    id: "41506",
    name: "הנדסת ביוריאקטורים",
    credits: 3.0,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["41231", "41335"])],
    coRequisites: ["41411"],
  },
  {
    id: "41507",
    name: "מעבדה בביוריאקטורים",
    credits: 1.0,
    type: "required",
    required: true,
    semester: 5,
    coRequisites: ["41506", "41560"],
  },
  {
    id: "41560",
    name: "תהליכי הפרדה 1",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["41411"])],
    coRequisites: ["41335"],
  },
  {
    id: "41562",
    name: "מעבדה בתהליכי הפרדה 1",
    credits: 0.75,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["41064"])],
    coRequisites: ["41560"],
  },

  // --- Semester 6 ---
  {
    id: "11027",
    name: "פיזיקה 3ב",
    credits: 3.0,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["11026"])],
  },
  {
    id: "41197",
    name: "ביואינפורמטיקה ובינה מלאכותית",
    credits: 2.0,
    type: "required",
    semester: 6,
    requirementGroup: "sem6-choice",
    prerequisites: [p(["41163", "41421"])],
    notes: ["חלופה ל-51728 בסמסטר 6; יש לבחור אחד מהשניים."],
  },
  {
    id: "41415",
    name: "מעבר מסה",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["41412"])],
    coRequisites: ["41421"],
  },
  {
    id: "41454",
    name: "סמינר מחלקתי בתהליכים ביוטכנולוגיים תעשייתיים 2",
    credits: 0,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["41452"])],
    notes: ["חובת נוכחות (קורס ללא נ\"ז)."],
  },
  {
    id: "41570",
    name: "תהליכי הפרדה 2",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["41560"])],
  },
  {
    id: "41640",
    name: "דיאגנוסטיקה",
    credits: 2.0,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["41181"])],
  },
  {
    id: "41652",
    name: "מעבדה בשיטות הפרדה ודיאגנוסטיקה",
    credits: 1.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["41562"])],
    coRequisites: ["41570", "41640"],
  },
  {
    id: "51728",
    name: "הבטחת איכות לביוטכנולוגיה",
    credits: 2.0,
    type: "required",
    semester: 6,
    requirementGroup: "sem6-choice",
    coRequisites: ["51725"],
    notes: ["חלופה ל-41197 בסמסטר 6; יש לבחור אחד מהשניים."],
  },
  // --- Semester 7 ---
  {
    id: "21312",
    name: "מבוא לבקרה לביוטכנולוגיה",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["11136", "11026"])],
  },
  {
    id: "41470",
    name: "פרויקט בביו-הנדסה",
    credits: 1.5,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["41412", "41506"])],
    coRequisites: ["41570"],
  },
  {
    id: "41526",
    name: "קינטיקה ותכנון ריאקטורים כימיים וביולוגיים",
    credits: 2.0,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["41412", "41506"])],
  },
  {
    id: "41525",
    name: "מעבדה בהנדסה תהליכית-ביוטכנולוגית (פיילוט)",
    credits: 3.0,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["41570", "41345"])],
    coRequisites: ["41526"],
  },
  {
    id: "41711",
    name: "כתיבה מדעית ושימוש במאגרי מידע בביו-טכנולוגיה",
    credits: 0.5,
    type: "required",
    required: true,
    semester: 7,
    coRequisites: ["41470"],
  },
  {
    id: "41730",
    name: "דרישות רגולטוריות ו-GMP בביוטכנולוגיה",
    credits: 1.0,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["41506"])],
    coRequisites: ["51728"],
  },

  // --- Semester 8 ---
  {
    id: "41750",
    name: "התמחות בתעשייה ובאקדמיה (סטאז')",
    credits: 16.0,
    type: "required",
    required: true,
    semester: 8,
    notes: [
      "קדם: השלמת כל קורסי החובה וקורסי חובת ההתמחות של תוכנית הלימודים.",
      "בסמסטר זה אין ללמוד קורסים נוספים במקביל לעבודת הסטאז'.",
    ],
  },

  // --- Specialization track: environmental biotechnology ---
  {
    id: "41242",
    name: "מעבדה בהנדסה סביבתית",
    credits: 1.0,
    type: "elective",
    clusterId: "spec-environment",
    coRequisites: ["41900"],
  },
  {
    id: "41672",
    name: "מיקרוביולוגיה של מזון וסביבה",
    credits: 3.0,
    type: "elective",
    clusterId: "spec-environment",
    prerequisites: [p(["41231"])],
    notes: ["קורס משותף למסלולי ביוטכנולוגיה של סביבה וביוטכנולוגיה של מזון."],
  },
  {
    id: "41677",
    name: "מעבדה במיקרוביולוגיה של מזון וסביבה",
    credits: 1.0,
    type: "elective",
    clusterId: "spec-environment",
    prerequisites: [p(["41162"])],
    coRequisites: ["41672"],
    notes: [
      "קורס משותף למסלולי ביוטכנולוגיה של סביבה וביוטכנולוגיה של מזון.",
      "המקור מציג חוסר עקביות בתנאי הקדם (41162 בטבלאות ההתמחות מול 41232 בטבלת הבחירה הכללית); נבחר 41162 לפי רוב המופעים במקור.",
    ],
  },
  {
    id: "41900",
    name: "כימיה של מים",
    credits: 2.5,
    type: "elective",
    clusterId: "spec-environment",
    prerequisites: [p(["41041"])],
  },
  {
    id: "41911",
    name: "תהליכים ומערכות לטיפול במים ושפכים",
    credits: 4.0,
    type: "elective",
    clusterId: "spec-environment",
    prerequisites: [p(["41231", "41506"])],
    coRequisites: ["41672"],
  },

  // --- Specialization track: food biotechnology ---
  {
    id: "41667",
    name: "עקרונות טכנולוגיים בייצור מזון",
    credits: 3.0,
    type: "elective",
    clusterId: "spec-food",
    coRequisites: ["41305"],
  },
  {
    id: "41668",
    name: "כימיה וטכנולוגיה של מוצרי מזון",
    credits: 3.25,
    type: "elective",
    clusterId: "spec-food",
    prerequisites: [p(["41667"])],
  },
  {
    id: "41669",
    name: "שיטות לאנליזה כימית של מזון",
    credits: 2.5,
    type: "elective",
    clusterId: "spec-food",
    coRequisites: ["41335"],
  },

  // --- Specialization track: molecular-pharmaceutical biotechnology ---
  {
    id: "41174",
    name: "הנדסה גנטית",
    credits: 2.5,
    type: "elective",
    clusterId: "spec-pharma",
    prerequisites: [p(["41163", "41162"])],
  },
  {
    id: "41175",
    name: "מעבדה בהנדסה גנטית",
    credits: 1.0,
    type: "elective",
    clusterId: "spec-pharma",
    prerequisites: [p(["41162"])],
    coRequisites: ["41174"],
  },
  {
    id: "41262",
    name: "טכנולוגיות של תרביות תאים אאוקריוטים",
    credits: 3.0,
    type: "elective",
    clusterId: "spec-pharma",
    prerequisites: [p(["41163"])],
  },
  {
    id: "41383",
    name: "פרמקולוגיה",
    credits: 2.5,
    type: "elective",
    clusterId: "spec-pharma",
    coRequisites: ["41335"],
  },
  {
    id: "41384",
    name: "מעבדה בפרמקולוגיה",
    credits: 0.75,
    type: "elective",
    clusterId: "spec-pharma",
    coRequisites: ["41383"],
  },
  {
    id: "41632",
    name: "כימיה ופורמולציה של תרופות",
    credits: 3.25,
    type: "elective",
    clusterId: "spec-pharma",
    prerequisites: [p(["41335", "41383"])],
  },

  // --- Departmental electives (single combined list per source) ---
  {
    id: "251504",
    name: "הנדסת יזמות - גישת ההזנק הרזה",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41305"])],
    notes: [entrepreneurshipCapNote],
  },
  {
    id: "251506",
    name: "מבוא לקניין רוחני",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41335"])],
    notes: [entrepreneurshipCapNote],
  },
  {
    id: "251507",
    name: "מבוא ליזמות",
    credits: 1.0,
    type: "elective",
    clusterId: "dept-electives",
    notes: [entrepreneurshipCapNote],
  },
  {
    id: "251508",
    name: "תכנון עסקי למיזמי הזנק",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["51605"])],
    notes: [entrepreneurshipCapNote],
  },
  {
    id: "251509",
    name: "חשיבה המצאתית",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41335"])],
  },
  {
    id: "251512",
    name: "מבוא לניהול חדשנות ויזמות פנים ארגונית",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41305"])],
    notes: [entrepreneurshipCapNote],
  },
  {
    id: "251513",
    name: "חשיבה יצירתית שיטתית",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41335"])],
    notes: [entrepreneurshipCapNote],
  },
  {
    id: "251514",
    name: "מבוא לפיתוח אב טיפוס",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41335"])],
    notes: [entrepreneurshipCapNote],
  },
  {
    id: "41081",
    name: "כימיה של פולימרים",
    credits: 2.5,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41060", "41041"])],
  },
  {
    id: "41136",
    name: "אנטומיה",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    coRequisites: ["41113"],
  },
  {
    id: "41540",
    name: "מעבר ממו\"פ לייצור תעשייתי",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41506"])],
  },
  {
    id: "41602",
    name: "ביוטכנולוגיה בצמחים",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41201", "41163"])],
  },
  {
    id: "41626",
    name: "הנדסת חלבונים",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    prerequisites: [p(["41335", "41060", "41163"])],
  },
  {
    id: "41763",
    name: "פרויקט מחקר 1",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    notes: ["מותנה באישור יועץ אקדמי.", researchProjectCapNote],
  },
  {
    id: "41764",
    name: "פרויקט מחקר 2",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
    notes: ["מותנה באישור יועץ אקדמי.", researchProjectCapNote],
  },
  {
    id: "41766",
    name: "סמינריון בביוטכנולוגיה",
    credits: 1.0,
    type: "elective",
    clusterId: "dept-electives",
    notes: ["מותנה באישור יועץ אקדמי.", researchProjectCapNote],
  },
  {
    id: "51605",
    name: "מבוא לכלכלה למהנדסים",
    credits: 2.0,
    type: "elective",
    clusterId: "dept-electives",
  },
  ...generalStudiesCourses,
  ...sportCourses,
];

export const degreePlan: DegreePlan = {
  id: "biotechnology-engineering",
  title: "מפת תואר הנדסת ביוטכנולוגיה",
  subtitle: "המכללה האקדמית להנדסה בראודה - שנתון תשפ\"ד 2023-2024",
  source: {
    fileName: "ידיעונים, שנתונים ולוח שנה אקדמית - בראודה.pdf",
    pages: "77-87",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 165,
    fixedDegreeCredits: 143,
    electiveCreditsNeeded: 22,
    generalCredits: 6,
    sportCredits: 1,
    englishRequiredIds: ["11058", "41181"],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [
    {
      code: "sem6-choice",
      name: "בחירה בין ביואינפורמטיקה ובינה מלאכותית לבין הבטחת איכות",
      kind: "alternative",
      requiredCredits: 2,
      minCourses: 1,
      courseIds: ["41197", "51728"],
    },
    {
      code: "spec-environment",
      name: "התמחות בביו-טכנולוגיה של סביבה",
      kind: "courses",
      minCourses: 5,
      courseIds: ["41242", "41672", "41677", "41900", "41911"],
    },
    {
      code: "spec-food",
      name: "התמחות בביוטכנולוגיה של מזון",
      kind: "courses",
      minCourses: 5,
      courseIds: ["41667", "41668", "41669", "41672", "41677"],
    },
    {
      code: "spec-pharma",
      name: "התמחות בביוטכנולוגיה מולקולרית-תרופתית",
      kind: "courses",
      minCourses: 6,
      courseIds: ["41174", "41175", "41262", "41383", "41384", "41632"],
    },
    {
      code: "general-studies",
      name: "לימודים כלליים",
      kind: "credits",
      requiredCredits: 6,
    },
    {
      code: "sport-elective",
      name: "ספורט",
      kind: "credits",
      requiredCredits: 1,
    },
  ],
  clusters,
  courses,
  rules: [
    {
      id: "english-basic-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית בסיסי וגם פטור/סיווג מאנגלית בסיסית.",
      payload: { courseIds: ["11063", "ENG_BASIC_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים א וגם פטור/סיווג מאנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים א חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים ב וגם פטור/סיווג מאנגלית מתקדמים ב.",
      payload: { courseIds: ["11058", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-advanced-a",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-exemptions-single-choice",
      type: "mutual_exclusion",
      message: "ניתן לבחור פטור/סיווג אנגלית אחד בלבד: בסיסי, מתקדמים א או מתקדמים ב.",
      payload: { courseIds: ["ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "physics-intro-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם מבוא לפיזיקה אקדמית וגם פטור ממבוא לפיזיקה אקדמית.",
      payload: { courseIds: ["11179", "PHYS_INTRO_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "sem6-choice-mutual-exclusion",
      type: "mutual_exclusion",
      message: "ניתן לבחור קורס אחד בלבד מבין 41197 (ביואינפורמטיקה ובינה מלאכותית) ו-51728 (הבטחת איכות).",
      payload: { courseIds: ["41197", "51728"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "specialization-single-track-choice",
      type: "single_track_choice",
      message: "יש לבחור מסלול התמחות אחד בלבד: סביבה, מזון, או ביוטכנולוגיה מולקולרית-תרופתית.",
      payload: { trackGroupCodes: ["spec-environment", "spec-food", "spec-pharma"] },
      enabled: true,
    },
    {
      id: "entrepreneurship-credit-cap",
      type: "credit_cap",
      message: entrepreneurshipCapNote,
      payload: {
        courseIds: ["251504", "251506", "251507", "251508", "251512", "251513", "251514"],
        maxCredits: 2,
      },
      enabled: true,
    },
    {
      id: "research-project-credit-cap",
      type: "credit_cap",
      message: researchProjectCapNote,
      payload: { courseIds: ["41763", "41764", "41766"], maxCredits: 5 },
      enabled: true,
    },
  ],
  notes: [
    "לצורך קבלת זכאות לתואר יש לצבור 165 נ\"ז.",
    "התוכנית כוללת 6 נ\"ז לימודים כלליים ו-1 נ\"ז ספורט; קורסים אלה אינם משובצים לסמסטר קבוע בשנתון וניתן לשלבם בכל סמסטר.",
    "יש לבחור מסלול התמחות אחד (ביו-טכנולוגיה של סביבה, ביוטכנולוגיה של מזון, או ביוטכנולוגיה מולקולרית-תרופתית) וללמוד את כל קורסי החובה שלו; פתיחת מסלול מותנית במספר הנרשמים.",
    "קורסי הבחירה המחלקתיים מוצגים בשנתון כרשימה משותפת אחת שאינה מחולקת לאשכולות, ואינם ניתנים בהכרח מדי שנה או סמסטר.",
    entrepreneurshipCapNote,
    researchProjectCapNote,
    "יש ללמוד לפחות שני קורסים בשפה האנגלית במהלך הלימודים, לפחות אחד מהם קורס תוכן (למשל 41181 אימונולוגיה).",
    "בסמסטר 8 (התמחות בתעשייה ובאקדמיה - סטאז', 41750) אין ללמוד קורסים נוספים; קדם הוא השלמת כל קורסי החובה וההתמחות של תוכנית הלימודים.",
    "בעקבות החלטת המל\"ג מיום 22.12.20 לא יינתנו פטורים ממקצועות יסוד/ליבה/מבואות על בסיס לימודים לא אקדמיים.",
    "המסמך הרשמי עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
