import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";

const generalAndSportCourses = require("../shared/general-and-sport-courses.json") as {
  general: { id: string; name: string; credits: number }[];
  sport: { id: string; name: string; credits: number }[];
};

const generalStudiesCourses: Course[] = generalAndSportCourses.general.map((course) => ({
  ...course,
  type: "general",
  required: false,
  requirementGroup: "general-studies",
}));

const sportCourses: Course[] = generalAndSportCourses.sport.map((course) => ({
  ...course,
  type: "sport",
  required: false,
  requirementGroup: "sport-elective",
}));

const clusters: ElectiveCluster[] = [
  { id: "sciences", name: "אשכול מדעים", minCourses: 1 },
  {
    id: "signals-networks",
    name: "אשכול עיבוד אותות ורשתות תקשורת",
    minCourses: 1,
  },
  { id: "algorithms", name: "אשכול אלגוריתמים", minCourses: 1 },
  {
    id: "seminars",
    name: "אשכול סמינרים",
    minCourses: 1,
    note: "קורסי האשכול ניתנים באנגלית; לא ניתן להמיר אותם בפעילות חברתית או מילואים.",
  },
  { id: "software", name: "אשכול הנדסת תוכנה", minCourses: 1 },
  { id: "labs", name: "אשכול מעבדות", minCourses: 1 },
];

const p = (ids: string[], label?: string) => ({ mode: "all" as const, ids, label });
const any = (ids: string[], label: string) => ({
  mode: "any" as const,
  ids,
  label,
});

const courses: Course[] = [
  {
    id: "ENG_BASIC_OK",
    name: "פטור/סיווג מאנגלית בסיסית",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שאינם צריכים ללמוד 11063 בפועל."],
  },
  {
    id: "ENG_ADV_A_OK",
    name: "פטור/סיווג מאנגלית מתקדמים א",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שמתחילים מאנגלית מתקדמים ב או מעליה."],
  },
  {
    id: "ENG_ADV_B_OK",
    name: "פטור/סיווג מאנגלית מתקדמים ב",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11060",
    notes: ["מיועד לסטודנטים הפטורים מכל חובות האנגלית עד רמת מתקדמים ב (כולל)."],
  },
  {
    id: "11063",
    name: "אנגלית בסיסי",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [],
    notes: ["לפי סיווג באנגלית; אינו נספר בסיכום סמסטר 1 בטבלה."],
  },
  {
    id: "11064",
    name: "אנגלית מתקדמים א",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסית או פטור/סיווג")],
    notes: ["לפי סיווג באנגלית; אינו נספר בסיכום סמסטר 1 בטבלה."],
  },
  {
    id: "251961",
    name: "מיומנויות יסוד הנדסיות",
    credits: 1,
    type: "required",
    required: true,
    semester: 1,
    notes: ["חובה ללמוד בשנה הראשונה."],
  },
  {
    id: "11004",
    name: "חדו\"א 1מ",
    credits: 5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11102",
    name: "אלגברה 1 מח",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "61740",
    name: "מערכות ספרתיות",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "61741",
    name: "מבוא למדעי המחשב",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11006",
    name: "חדו\"א 2מ",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11004"])],
    coRequisites: ["11102"],
  },
  {
    id: "11060",
    name: "אנגלית מתקדמים ב",
    credits: 2,
    type: "english",
    required: true,
    semester: 2,
    prerequisites: [any(["11064", "ENG_ADV_A_OK"], "אנגלית מתקדמים א או סיווג מתאים")],
  },
  {
    id: "61738",
    name: "מבנים אלגבריים להנדסת תוכנה 1",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11102"])],
  },
  {
    id: "61743",
    name: "מתמטיקה דיסקרטית 1",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "61745",
    name: "מבוא לתכנות מערכות",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["61741"])],
  },
  {
    id: "61750",
    name: "מבוא להנדסת תוכנה",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["61741"])],
  },
  {
    id: "11129",
    name: "טורים, התמרות ומשוואות דיפרנציאליות",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11006", "61738"])],
  },
  {
    id: "61739",
    name: "מבני נתונים ומבוא לאלגוריתמים",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [
      any(
        ["11063", "ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"],
        "אנגלית בסיסית או פטור/סיווג מתאים"
      ),
      p(["61743", "61745"]),
    ],
    notes: ["קורס קדם 11063 חל על סטודנטים שהחלו בתשפ\"ג ואילך."],
  },
  {
    id: "61774",
    name: "יסודות המחשוב",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["61740", "61750"])],
  },
  {
    id: "61778",
    name: "לוגיקה להנדסת תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["61743"])],
  },
  {
    id: "61911",
    name: "מבנים אלגבריים להנדסת תוכנה 2",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["61738", "61743"])],
  },
  {
    id: "61912",
    name: "ארכיטקטורת מערכות תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["61750"])],
  },
  {
    id: "61751",
    name: "תכנות מונחה עצמים",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["61739", "61750"])],
  },
  {
    id: "61752",
    name: "מערכות הפעלה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["61745", "61774"])],
  },
  {
    id: "61753",
    name: "אלגוריתמים",
    credits: 5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11006", "61738", "61739", "61778"])],
  },
  {
    id: "61755",
    name: "מערכות מסדי נתונים מ",
    credits: 4,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["61739"])],
  },
  {
    id: "61762",
    name: "ניהול פרויקטי תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["61750", "61912"])],
  },
  {
    id: "11069",
    name: "אנגלית טכנית יישומית - תוכנה",
    credits: 1,
    type: "english",
    required: true,
    semester: 5,
    prerequisites: [any(["11060", "ENG_ADV_B_OK"], "אנגלית מתקדמים ב או פטור/סיווג")],
    notes: ["אחד משני קורסי האנגלית הנדרשים בתוכנית."],
  },
  {
    id: "61756",
    name: "שיטות הנדסיות לפיתוח מערכות תוכנה",
    credits: 5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [
      any(["11060", "ENG_ADV_B_OK"], "אנגלית מתקדמים ב או פטור/סיווג"),
      p(["61751", "61755", "61762"]),
    ],
    coRequisites: ["61757", "61769"],
    notes: ["יש ללמוד בצמוד את 61757 ואת 61769."],
  },
  {
    id: "61757",
    name: "מבוא לבדיקות תוכנה",
    credits: 2,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [
      any(["11060", "ENG_ADV_B_OK"], "אנגלית מתקדמים ב או פטור/סיווג"),
      p(["61751", "61755", "61762"]),
    ],
    coRequisites: ["61756", "61769"],
  },
  {
    id: "61759",
    name: "אוטומטים וחישוביות",
    credits: 5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["61753"])],
  },
  {
    id: "61760",
    name: "הסתברות להנדסת תוכנה",
    credits: 4,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["11006", "61739", "61911"])],
  },
  {
    id: "61769",
    name: "ממשק אדם מחשב",
    credits: 2,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [
      any(["11060", "ENG_ADV_B_OK"], "אנגלית מתקדמים ב או פטור/סיווג"),
      p(["61751", "61755", "61762"]),
    ],
    coRequisites: ["61756", "61757"],
  },
  {
    id: "61179",
    name: "מבוא לפיזיקה להנדסת תוכנה",
    credits: 0,
    type: "required",
    semester: 6,
    prerequisites: [p(["11006", "61738", "61741"])],
    coRequisites: ["61180"],
    notes: ["מיועד למי שאין לו פטור מפיזיקה אקדמית; בצמוד ל-61180."],
  },
  {
    id: "61180",
    name: "פיזיקה להנדסת תוכנה ל'",
    credits: 3,
    type: "required",
    semester: 6,
    requirementGroup: "physics",
    prerequisites: [p(["11006", "61738", "61741"])],
    coRequisites: ["61179"],
    notes: ["אחת מחלופות הפיזיקה לזכאות לתואר."],
  },
  {
    id: "61181",
    name: "פיזיקה להנדסת תוכנה",
    credits: 3,
    type: "required",
    semester: 6,
    requirementGroup: "physics",
    prerequisites: [p(["11006", "61738", "61741"])],
    notes: ["מיועד לסטודנטים שיש להם פטור מפיזיקה אקדמית."],
  },
  {
    id: "11158",
    name: "מכניקה להנדסת תוכנה",
    credits: 3,
    type: "required",
    semester: 6,
    requirementGroup: "physics",
    notes: ["קורס חליפי לקורסי הפיזיקה 61180/61181 לפי הערת השנתון."],
  },
  {
    id: "61761",
    name: "כריית נתונים ומערכות לומדות",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["61753", "61760"])],
  },
  {
    id: "61763",
    name: "תורת הקומפילציה",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["61759"])],
  },
  {
    id: "61773",
    name: "מבוא למחשוב ענן",
    credits: 3,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["61756"])],
  },
  {
    id: "61775",
    name: "מבוא לבינה מלאכותית",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["61753", "61760"])],
  },
  {
    id: "61776",
    name: "טכנולוגיות אינטרנט מתקדמות (web)",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["61752", "61756"])],
  },
  {
    id: "61765",
    name: "רשתות מחשבים",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["61751", "61753"])],
  },
  {
    id: "61767",
    name: "אבטחת מידע וקריפטולוגיה",
    credits: 4,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["61753", "61911"])],
  },
  {
    id: "61998",
    name: "פרויקט מסכם שלב א'",
    credits: 4,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [
      p(["11069", "11129", "61756", "61759", "61761", "61775", "61776"]),
      any(["61180", "61181", "11158"], "אחת מחלופות הפיזיקה"),
    ],
    notes: ["קורס קדם 61775 חל על סטודנטים שהחלו בשנת 2022 ואילך."],
  },
  {
    id: "61999",
    name: "פרויקט מסכם שלב ב'",
    credits: 4,
    type: "required",
    required: true,
    semester: 8,
    prerequisites: [p(["61998"])],
  },
  {
    id: "SOCIAL",
    name: "המרת פעילות חברתית או שירות מילואים",
    credits: 2,
    type: "conversion",
    notes: [
      "ניתן להמיר במקום קורס כללי או קורס בחירה מחלקתי.",
      "לא ניתן להמיר במקום קורס מאשכול סמינרים.",
    ],
  },
  {
    id: "41942",
    name: "מבוא לביולוגיה מולקולרית וגנטיקה להנדסת תוכנה",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61957",
    name: "תורת המשחקים",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61760"])],
  },
  {
    id: "61958",
    name: "תורת המידע",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61760"])],
  },
  {
    id: "61989",
    name: "מחשבים קוונטים",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61738"])],
  },
  {
    id: "61991",
    name: "תכנות מדעי",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61760"])],
  },
  {
    id: "61992",
    name: "מבוא לחישה ולמידה",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61993",
    name: "תורת המשחקים האלגוריתמית",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61753", "61760"])],
  },
  {
    id: "62002",
    name: "עיבוד שפה טבעית עם למידת מכונה",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61751", "61761"])],
  },
  {
    id: "61836",
    name: "שיטות סטטיסטיות ותהליכים סטוכסטיים",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61911", "61760"])],
  },
  {
    id: "65010",
    name: "סוגיות באתיקה של AI",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61775"])],
  },
  {
    id: "65011",
    name: "אלגוריתמים קוונטים",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61760"])],
  },
  {
    id: "61971",
    name: "עיבוד תמונה ספרתי",
    credits: 3,
    type: "elective",
    clusterId: "signals-networks",
    prerequisites: [p(["11129"])],
  },
  {
    id: "61972",
    name: "עיבוד אותות ספרתי DSP",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-networks",
    prerequisites: [p(["11129"])],
  },
  {
    id: "61973",
    name: "תקשורת אלחוטית ורשתות מחשבים",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-networks",
    prerequisites: [p(["61765"])],
  },
  {
    id: "61974",
    name: "בדיקת מערכות ספרתיות",
    credits: 3.5,
    type: "elective",
    clusterId: "signals-networks",
    prerequisites: [p(["61774"])],
  },
  {
    id: "61975",
    name: "דחיסת נתונים",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-networks",
    prerequisites: [p(["61760"])],
  },
  {
    id: "61976",
    name: "ביולוגיה חישובית",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-networks",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61994",
    name: "למידה עמוקה עבור ראיית מכונה",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-networks",
    prerequisites: [p(["61751", "61761"])],
  },
  {
    id: "62008",
    name: "מערכות משובצות מחשב",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-networks",
    prerequisites: [p(["61751", "61774"])],
  },
  {
    id: "61764",
    name: "גרפיקה ממוחשבת",
    credits: 3,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["11102", "61745"])],
  },
  {
    id: "61913",
    name: "כלכלה חישובית ומסחר אלגוריתמי",
    credits: 2.5,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61753", "61760"])],
  },
  {
    id: "61956",
    name: "חישוב מקבילי ומבוזר",
    credits: 3,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61752", "61763", "61912"])],
  },
  {
    id: "61959",
    name: "אנליזה נומרית",
    credits: 3,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["11129", "61741"])],
  },
  {
    id: "65005",
    name: "מבוא לאופטימיזציה",
    credits: 2.5,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["11006", "61745", "61911"])],
  },
  {
    id: "61961",
    name: "אחזור מידע",
    credits: 2.5,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61761"])],
  },
  {
    id: "61962",
    name: "גיאומטריה חישובית ומידול",
    credits: 2.5,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["11006", "61738", "61764"])],
  },
  {
    id: "61964",
    name: "ויזואליזציה של המידע",
    credits: 2.5,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61751"])],
  },
  {
    id: "61965",
    name: "ניתוח של נתוני הרשתות",
    credits: 2.5,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61995",
    name: "אלגוריתמים לטקסטים ורצפים",
    credits: 2.5,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61753", "61760"])],
  },
  {
    id: "61996",
    name: "אלגוריתמים מבוזרים",
    credits: 2.5,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61753"])],
  },
  {
    id: "62013",
    name: "אלגוריתמים ומבני נתונים במחרוזות",
    credits: 3,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61753"])],
  },
  {
    id: "62014",
    name: "למידה מחיזוקים",
    credits: 3,
    type: "elective",
    clusterId: "algorithms",
    prerequisites: [p(["61761", "61775"])],
  },
  {
    id: "61966",
    name: "סמינר מערכות לומדות",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61761"])],
  },
  {
    id: "61967",
    name: "סמינר באלגוריתמים אקראיים",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61753", "61760"])],
  },
  {
    id: "61968",
    name: "סמינר באלגוריתמים מתקדמים",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61753"])],
  },
  {
    id: "61969",
    name: "סמינר באימות תוכנה",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61759"])],
  },
  {
    id: "61970",
    name: "סמינר באוטומטים",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61759"])],
  },
  {
    id: "61997",
    name: "סמינר בחישוב מבוזר",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61759"])],
  },
  {
    id: "61779",
    name: "סמינר בנושאים נבחרים בבינה מלאכותית",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61775"])],
    notes: ["מי שלמד בעבר את 61963 בינה מלאכותית אינו יכול ללמוד סמינר זה."],
  },
  {
    id: "62005",
    name: "סמינר בהתאמת תבניות",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61753"])],
  },
  {
    id: "62015",
    name: "סמינר בניתוח סיבוכיות חישוב במערכות מודרניות",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61752"])],
  },
  {
    id: "65012",
    name: "סמינר בתורת הצפינה",
    credits: 3,
    type: "elective",
    clusterId: "seminars",
    prerequisites: [p(["11069", "61760"])],
  },
  {
    id: "61834",
    name: "מסדי נתונים מבוזרים",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61753", "61756"])],
  },
  {
    id: "61914",
    name: "בלוקצ'יין ומטבעות קריפטו",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751", "61755"])],
  },
  {
    id: "61978",
    name: "אימות תוכנה וחומרה",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61759"])],
  },
  {
    id: "61980",
    name: "שפות תכנות",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751"])],
  },
  {
    id: "61981",
    name: "הנדסת דרישות",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61750"])],
  },
  {
    id: "61955",
    name: "מחשוב זמן אמת",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61752"])],
  },
  {
    id: "62001",
    name: "תכנות מקבילי",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61752", "61756"])],
  },
  {
    id: "62003",
    name: "פרויקט במציאות רבודה",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61756", "61761"])],
  },
  {
    id: "62004",
    name: "מבוא להנדסת מערכות ותעשייה 4.0 להנדסת תוכנה",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61756"])],
  },
  {
    id: "62006",
    name: "דרישות במערכות IOT",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61750"])],
  },
  {
    id: "251100",
    name: "פרויקט בין-תחומי",
    credits: 3,
    type: "elective",
    clusterId: "software",
    notes: ["באשכול הנדסת תוכנה ניתן לקחת אחד משני קורסי הכוכבית, אך לא את שניהם."],
  },
  {
    id: "251965",
    name: "מהנדסים למען הגיל השלישי",
    credits: 2,
    type: "elective",
    clusterId: "software",
    notes: ["באשכול הנדסת תוכנה ניתן לקחת אחד משני קורסי הכוכבית, אך לא את שניהם."],
  },
  {
    id: "62009",
    name: "תכנות למערכות מידע מבוזרות",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61752", "61911"])],
  },
  {
    id: "65013",
    name: "אימות פורמאלי של מערכות ריאקטיביות",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61759"])],
  },
  {
    id: "61954",
    name: "למידה עמוקה יוצרת",
    credits: 3,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61761"])],
  },
  {
    id: "61982",
    name: "מעבדה במידול מערכות אקולוגיות",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["11006", "61738"])],
  },
  {
    id: "61983",
    name: "מעבדה בתכנות מקבילי והטרוגני",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61751", "61752"])],
  },
  {
    id: "61984",
    name: "מעבדה באופטימיזציה",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["11006", "61745"])],
  },
  {
    id: "61985",
    name: "מעבדה בפיתוח יישומים באנדרואיד",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61751", "61752"])],
  },
  {
    id: "61986",
    name: "מעבדה בסחר אלקטרוני",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61750"])],
  },
  {
    id: "61987",
    name: "מעבדה בכריית נתונים",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61761"])],
  },
  {
    id: "61988",
    name: "מעבדה בעיצוב תבניות בתוכנה",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61751"])],
  },
  {
    id: "62010",
    name: "מעבדה בניתוח נתונים",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61760"])],
  },
  {
    id: "62012",
    name: "מעבדה בדבאופס",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61751"])],
  },
  {
    id: "61990",
    name: "מעבדה בטכנולוגיות תכנות צד לקוח ושרת",
    credits: 2.5,
    type: "elective",
    clusterId: "labs",
    prerequisites: [p(["61750", "61751"])],
  },
  ...generalStudiesCourses,
  ...sportCourses,
];

export const degreePlan: DegreePlan = {
  id: "braude-software-2020",
  title: "מפת תואר הנדסת תוכנה",
  subtitle: "המכללה האקדמית להנדסה בראודה - רפורמה 2020",
  source: {
    fileName: "ידיעונים, שנתונים ולוח שנה אקדמית - בראודה.pdf",
    pages: "1-63, 136-146",
    extractedAt: "2026-07-02",
  },
  requirements: {
    totalCredits: 160,
    fixedDegreeCredits: 138,
    electiveCreditsNeeded: 22,
    generalCredits: 6,
    sportCredits: 1,
    englishRequiredIds: ["11060", "11069"],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [
    {
      code: "physics",
      name: "חלופת פיזיקה אחת",
      kind: "alternative",
      requiredCredits: 3,
      minCourses: 1,
      courseIds: ["61180", "61181", "11158"],
    },
    {
      code: "general-studies",
      name: "לימודים כלליים",
      kind: "credits",
      requiredCredits: 6,
    },
    {
      code: "sport-elective",
      name: "ספורט",
      kind: "credits",
      requiredCredits: 1,
    },
  ],
  clusters,
  courses,
  rules: [
    {
      id: "software-star-mutual-exclusion",
      type: "mutual_exclusion",
      message: "באשכול הנדסת תוכנה ניתן לקחת אחד משני קורסי הכוכבית, אך לא את שניהם.",
      payload: { courseIds: ["251100", "251965"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-basic-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית בסיסי וגם פטור/סיווג מאנגלית בסיסית.",
      payload: { courseIds: ["11063", "ENG_BASIC_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים א וגם פטור/סיווג מאנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים א חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים ב וגם פטור/סיווג מאנגלית מתקדמים ב.",
      payload: { courseIds: ["11060", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-advanced-a",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-exemptions-single-choice",
      type: "mutual_exclusion",
      message: "ניתן לבחור פטור/סיווג אנגלית אחד בלבד: בסיסי, מתקדמים א או מתקדמים ב.",
      payload: { courseIds: ["ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "physics-alternative-mutual-exclusion",
      type: "mutual_exclusion",
      message: "ניתן לבחור חלופת פיזיקה אחת בלבד: 61180 (בצמוד ל-61179), 61181 או 11158.",
      payload: { courseIds: ["61180", "61181", "11158"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "physics-intro-lab-mutual-exclusion",
      type: "mutual_exclusion",
      message: "קורס 61179 נלמד רק בצמוד ל-61180; אינו תואם לחלופות 61181 או 11158.",
      payload: { courseIds: ["61179", "61181", "11158"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "conversion-does-not-replace-seminar",
      type: "conversion_requires_cluster",
      message: "המרת פעילות חברתית/מילואים אינה מחליפה את דרישת אשכול הסמינרים.",
      payload: { conversionCourseIds: ["SOCIAL"], clusterId: "seminars" },
      enabled: true,
    },
  ],
  notes: [
    "לצורך זכאות לתואר יש לצבור לפחות 160 נ\"ז.",
    "התוכנית כוללת 6 נ\"ז לימודים כלליים, 1 נ\"ז ספורט ו-1 נ\"ז מיומנויות יסוד הנדסיות.",
    "יש לקחת לפחות קורס אחד מכל אשכול בחירה, ולהשלים קורסי בחירה עד 160 נ\"ז.",
    "ניתן להמיר 2 נ\"ז פעילות חברתית או שירות מילואים במקום קורס כללי או קורס בחירה מחלקתי, אך לא במקום סמינר.",
    "המסמך הרשמי עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
