import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";

const generalAndSportCourses = require("../shared/general-and-sport-courses.json") as {
  general: { id: string; name: string; credits: number }[];
  sport: { id: string; name: string; credits: number }[];
};

const generalStudiesCourses: Course[] = generalAndSportCourses.general.map((course) => ({
  ...course,
  type: "general",
  required: false,
  requirementGroup: "general-studies",
}));

const sportCourses: Course[] = generalAndSportCourses.sport.map((course) => ({
  ...course,
  type: "sport",
  required: false,
  requirementGroup: "sport-elective",
}));

const clusters: ElectiveCluster[] = [
  {
    id: "structural-track",
    name: "מסלול הנדסת מבנים - קורסי חובה",
    minCourses: 9,
    note:
      "קורסי החובה של מסלול הנדסת מבנים (סמסטרים 3-7): 421212, 421219, 421314, 421315, 421316, 421326, 500115, 421411, 421412. יש להשלים את כל 9 הקורסים עבור מי שבחר במסלול זה.",
  },
  {
    id: "construction-mgmt-track",
    name: "מסלול הנדסת ניהול הבנייה - קורסי חובה",
    minCourses: 9,
    note:
      "קורסי החובה של מסלול הנדסת ניהול הבנייה (סמסטרים 3-7): 421214, 421221, 421222, 421317, 421318, 421319, 421327, 421328, 421413. יש להשלים את כל 9 הקורסים עבור מי שבחר במסלול זה.",
  },
  {
    id: "structural-electives-group1",
    name: "מסלול מבנים - קבוצה 1 (בחירת התמחות)",
    minCourses: 2,
    note: "חובה ללמוד לפחות 2 קורסים מהרשימה הבאה (קבוצה 1, מסלול הנדסת מבנים).",
  },
  {
    id: "structural-electives-group2",
    name: "מסלול מבנים - קבוצה 2 (בחירת התמחות)",
    minCourses: 1,
    note:
      "חובה ללמוד לפחות קורס אחד מהרשימה הבאה (קבוצה 2, מסלול הנדסת מבנים). הרשימה כוללת גם קורסים המופיעים כחובה במסלול הנדסת ניהול הבנייה (421221, 421222, 421318, 421319, 421413) וכן קורס 500120 עיקרי תכן אדריכלי 2, המופיע ברשימת מסלול ניהול הבנייה בהיקף 2.5 נ\"ז וכאן במקור בהיקף 2.0 נ\"ז.",
  },
  {
    id: "construction-mgmt-electives",
    name: "מסלול ניהול הבנייה - קורסי בחירה מחלקתית",
    minCourses: 1,
    note:
      "קורסי בחירה מחלקתית עבור מסלול הנדסת ניהול הבנייה (סמסטרים 6-8). המקור אינו מציין מספר קורסים מזערי מפורש; יש להשלים קורסי בחירה עד להיקף הנ\"ז הנדרש (ראו הערות התוכנית). הרשימה כוללת גם 421412 בניית המהנדס ו-421418 אקוסטיקת הבנייה, המשותפים למסלול הנדסת מבנים.",
  },
];

const p = (ids: string[], label?: string) => ({ mode: "all" as const, ids, label });
const any = (ids: string[], label: string) => ({
  mode: "any" as const,
  ids,
  label,
});

const courses: Course[] = [
  // --- English placement / exemption placeholders ---
  {
    id: "ENG_BASIC_OK",
    name: "פטור/סיווג מאנגלית בסיסית",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שאינם צריכים ללמוד 11063 בפועל."],
  },
  {
    id: "ENG_ADV_A_OK",
    name: "פטור/סיווג מאנגלית מתקדמים א",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שמתחילים מאנגלית מתקדמים ב או מעליה."],
  },
  {
    id: "ENG_ADV_B_OK",
    name: "פטור/סיווג מאנגלית מתקדמים ב",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11061",
    notes: ["מיועד לסטודנטים הפטורים מכל חובות האנגלית עד רמת מתקדמים ב (כולל)."],
  },

  // --- English chain ---
  {
    id: "11063",
    name: "אנגלית בסיסי",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [],
    notes: [
      "לפי ציון פסיכומטרי באנגלית 85-99 או סיווג מקביל.",
      "חובה ללמוד את שרשרת הלימוד של האנגלית כמפורט בפרק היחידה ללימודי אנגלית בשנתון.",
    ],
  },
  {
    id: "11064",
    name: "אנגלית מתקדמים א",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסי או פטור/סיווג")],
    notes: ["לפי ציון פסיכומטרי באנגלית 100-119 או השלמת 11063."],
  },
  {
    id: "11061",
    name: "אנגלית מתקדמים ב",
    credits: 2,
    type: "english",
    required: true,
    semester: 3,
    prerequisites: [any(["11064", "ENG_ADV_A_OK"], "אנגלית מתקדמים א או פטור/סיווג")],
    notes: ["יש לסיים את לימודי החובה באנגלית עד תום השנה השנייה ללימודים."],
  },

  // --- Semester 1 ---
  {
    id: "11003",
    name: "חדו\"א 1",
    credits: 5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11001",
    name: "אלגברה",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "41079",
    name: "כימיה כללית",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "421109",
    name: "מבוא לגרפיקה הנדסית",
    credits: 3,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "421110",
    name: "מבוא למכניקה הנדסית",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
    coRequisites: ["11001"],
    notes: [
      "חובת קדם: מבוא לפיזיקה אקדמית, או פיזיקה ברמת 5 יח\"ל, או קורס הכנה במכינת קדם-הנדסה במכללה (אינו קורס מהתוכנית).",
    ],
  },
  {
    id: "22400",
    name: "הנדסת חומרים",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 1,
    coRequisites: ["41079"],
  },
  {
    id: "251961",
    name: "מיומנות יסוד הנדסית",
    credits: 1,
    type: "required",
    required: true,
    semester: 1,
  },

  // --- Semester 2 ---
  {
    id: "11005",
    name: "חדו\"א 2",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11003"])],
  },
  {
    id: "51750",
    name: "הסתברות וסטטיסטיקה אז",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11003", "11001"])],
    coRequisites: ["11005"],
  },
  {
    id: "421208",
    name: "פיזיקה 1 אז",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11003"])],
  },
  {
    id: "421111",
    name: "עיקרי תכן אדריכלי 1",
    credits: 2,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["421109"])],
  },
  {
    id: "421112",
    name: "תורת החוזק 1",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["421110"])],
  },
  {
    id: "421113",
    name: "כלכלה הנדסית",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },

  // --- Semester 3 (common) ---
  {
    id: "11124",
    name: "משוואות דיפרנציאליות אז",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11005"])],
  },
  {
    id: "421209",
    name: "פיזיקה 2 אז",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["421208"])],
  },
  {
    id: "421210",
    name: "מבוא לחומרי בנייה וסלילה",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["22400", "41079"])],
  },
  {
    id: "421213",
    name: "מבוא לגאולוגיה ורעידות אדמה",
    credits: 2,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "421211",
    name: "מבוא לניהול פרויקטי בנייה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["421113", "51750"])],
    notes: [
      "ניתן לעמוד בדרישת הקדם הסטטיסטית גם באמצעות 51707 הסתברות וסטטיסטיקה מכ (קורס ממחלקה אחרת שאינו כלול ברשימת קורסי תוכנית זו).",
    ],
  },

  // --- Semester 3 specialization-mandatory ---
  {
    id: "421212",
    name: "תורת החוזק 2",
    credits: 4,
    type: "required",
    clusterId: "structural-track",
    semester: 3,
    prerequisites: [p(["421112"])],
  },
  {
    id: "421214",
    name: "מבני בטון 12",
    credits: 4,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 3,
    prerequisites: [p(["421112"])],
    coRequisites: ["421210"],
    notes: ["קורס משולב (\"מבני בטון 1&2\") הנלמד במסלול ניהול הבנייה במקום 421219 ו-421314."],
  },

  // --- Semester 4 (common) ---
  {
    id: "421215",
    name: "מכניקת זורמים",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11124", "421208", "421110"])],
  },
  {
    id: "421216",
    name: "גאומכניקה",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["421213", "421112"])],
    coRequisites: ["421215"],
  },
  {
    id: "421217",
    name: "סטטיקת מבנים 1",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["421112"])],
  },
  {
    id: "421223",
    name: "מבוא לאלגוריתמיקה ותכנות",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11005"])],
  },
  {
    id: "421220",
    name: "מעבדה בחוזק חומרים",
    credits: 1.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["421112", "22400"])],
    notes: [
      "במקור מודפס קורס קדם כ-\"421212 תורת החוזק 1\" — ככל הנראה טעות דפוס בשנתון (421212 הוא תורת החוזק 2, ו-421112 הוא תורת החוזק 1). תוקן כאן ל-421112 בהתאם להערת השנתון על טעויות מיפוי.",
    ],
  },
  {
    id: "421218",
    name: "יסודות המיפוי והמדידה",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
  },

  // --- Semester 4 specialization-mandatory ---
  {
    id: "421219",
    name: "מבני בטון 1",
    credits: 4,
    type: "required",
    clusterId: "structural-track",
    semester: 4,
    prerequisites: [p(["421112", "421210"])],
  },
  {
    id: "421221",
    name: "שיטות ביצוע",
    credits: 2.5,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 4,
    prerequisites: [p(["421211"])],
    notes: ["זמין גם כקורס בחירה בקבוצה 2 של מסלול הנדסת מבנים."],
  },
  {
    id: "421222",
    name: "ניהול ובקרת ביצוע פרויקטי בנייה",
    credits: 2.5,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 4,
    prerequisites: [p(["421211"])],
    notes: ["זמין גם כקורס בחירה בקבוצה 2 של מסלול הנדסת מבנים."],
  },

  // --- Semester 5 (common) ---
  {
    id: "421310",
    name: "שרטוט הנדסי",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["421109", "421111"])],
    coRequisites: ["421314"],
    notes: [
      "עבור מסלול הנדסת ניהול הבנייה: נדרש בנוסף גם 421214 מבני בטון 12 כקורס קדם.",
      "עבור מסלול הנדסת מבנים: הקורס צמוד (נלמד באותו סמסטר) ל-421314 מבני בטון 2.",
    ],
  },
  {
    id: "421311",
    name: "תכנון, ניהול ובקרת איכות",
    credits: 2,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["421211"])],
  },
  {
    id: "421312",
    name: "מבני פלדה",
    credits: 3,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["421217"])],
  },
  {
    id: "421313",
    name: "הנדסת קרקע",
    credits: 3,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["421216"])],
  },
  {
    id: "22130",
    name: "אנליזה נומרית",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["11124", "421223"])],
  },

  // --- Semester 5 specialization-mandatory ---
  {
    id: "421314",
    name: "מבני בטון 2",
    credits: 4,
    type: "required",
    clusterId: "structural-track",
    semester: 5,
    prerequisites: [p(["421219", "421217"])],
  },
  {
    id: "421315",
    name: "דינמיקת מבנים",
    credits: 3,
    type: "required",
    clusterId: "structural-track",
    semester: 5,
    prerequisites: [p(["11124", "421208", "421112", "421213"])],
  },
  {
    id: "421316",
    name: "סטטיקת מבנים 2",
    credits: 3,
    type: "required",
    clusterId: "structural-track",
    semester: 5,
    prerequisites: [p(["421217", "421223"])],
    coRequisites: ["22130"],
  },
  {
    id: "421317",
    name: "ייזום ובדיקת כדאיות פרויקטים",
    credits: 2.5,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 5,
    prerequisites: [p(["421113", "421211"])],
  },
  {
    id: "421318",
    name: "מיכון ותיעוש",
    credits: 2.5,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 5,
    notes: ["זמין גם כקורס בחירה בקבוצה 2 של מסלול הנדסת מבנים."],
  },
  {
    id: "421319",
    name: "אומדן עלויות של פרויקטים הנדסיים",
    credits: 2.5,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 5,
    prerequisites: [p(["421113", "421211"])],
    notes: ["זמין גם כקורס בחירה בקבוצה 2 של מסלול הנדסת מבנים."],
  },

  // --- Semester 6 (common) ---
  {
    id: "421320",
    name: "יסודות",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [
      p(["421313"]),
      any(["421314", "421214"], "מבני בטון 2 (מסלול מבנים) או מבני בטון 12 (מסלול ניהול)"),
    ],
  },
  {
    id: "421321",
    name: "יסודות הנדסת תחבורה",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["421208", "421218", "421216", "421215"])],
  },
  {
    id: "421322",
    name: "מבוא להנדסת הסביבה",
    credits: 2,
    type: "required",
    required: true,
    semester: 6,
  },
  {
    id: "421323",
    name: "סמינר בהנדסת ניהול הבנייה/הנדסת מבנים",
    credits: 1,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [any(["421314", "421221"], "מבני בטון 2 (מסלול מבנים) או שיטות ביצוע (מסלול ניהול)")],
  },
  {
    id: "421324",
    name: "עיקרי תכן מבנים",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [
      p(["421313", "421312"]),
      any(["421314", "421214"], "מבני בטון 2 (מסלול מבנים) או מבני בטון 12 (מסלול ניהול)"),
    ],
    coRequisites: ["421320"],
  },
  {
    id: "421325",
    name: "תכנון, ניהול ובקרת בטיחות בעבודה",
    credits: 2,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["421211"])],
  },

  // --- Semester 6 specialization-mandatory ---
  {
    id: "421326",
    name: "הנדסת רעידות אדמה",
    credits: 2.5,
    type: "required",
    clusterId: "structural-track",
    semester: 6,
    prerequisites: [p(["421315"])],
  },
  {
    id: "500115",
    name: "מבוא לאלמנטים סופיים",
    credits: 2.5,
    type: "required",
    clusterId: "structural-track",
    semester: 6,
    prerequisites: [p(["421316", "22130"])],
  },
  {
    id: "421327",
    name: "מבוא למבנים ארעיים",
    credits: 2,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 6,
    prerequisites: [p(["421214", "421312"])],
  },
  {
    id: "421328",
    name: "ניהול פרויקטי בנייה בשלב הייזום",
    credits: 2.5,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 6,
    prerequisites: [p(["421211"])],
  },

  // --- Semester 7 (common) ---
  {
    id: "421410",
    name: "פרויקט שלב א'",
    credits: 4,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [
      any(
        ["421324", "421328"],
        "עיקרי תכן מבנים + הנדסת רעידות אדמה (מסלול מבנים) או ניהול פרויקטי בנייה בשלב הייזום (מסלול ניהול)"
      ),
    ],
    notes: ["עבור מסלול הנדסת מבנים: נדרש בנוסף גם 421326 הנדסת רעידות אדמה."],
  },
  {
    id: "421414",
    name: "תפקוד פיזי של בניינים",
    credits: 3,
    type: "required",
    required: true,
    semester: 7,
  },

  // --- Semester 7 specialization-mandatory ---
  {
    id: "421411",
    name: "בטון דרוך",
    credits: 2.5,
    type: "required",
    clusterId: "structural-track",
    semester: 7,
    prerequisites: [p(["421314"])],
  },
  {
    id: "421412",
    name: "בניית המהנדס",
    credits: 3,
    type: "required",
    clusterId: "structural-track",
    semester: 7,
    prerequisites: [p(["421324"])],
    notes: ["זמין גם כקורס בחירה מחלקתית במסלול הנדסת ניהול הבנייה."],
  },
  {
    id: "421413",
    name: "תכנון תפעולי בתחבורה",
    credits: 3,
    type: "required",
    clusterId: "construction-mgmt-track",
    semester: 7,
    prerequisites: [p(["421321"])],
    notes: ["זמין גם כקורס בחירה בקבוצה 2 של מסלול הנדסת מבנים."],
  },

  // --- Semester 8 ---
  {
    id: "421415",
    name: "פרויקט שלב ב'",
    credits: 4,
    type: "required",
    required: true,
    semester: 8,
    prerequisites: [p(["421410"])],
    notes: ["עבור מסלול הנדסת מבנים: נדרש בנוסף גם 421412 בניית המהנדס."],
  },

  // --- מסלול מבנים - קבוצה 1 (לפחות 2 קורסים) ---
  {
    id: "500110",
    name: "תורת האלסטיות",
    credits: 2.5,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["11005", "421212", "11124"])],
  },
  {
    id: "500111",
    name: "יציבות מבנים",
    credits: 2.5,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["11003", "421212"])],
  },
  {
    id: "500112",
    name: "מבנים מרחביים",
    credits: 2.5,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["421208", "11001", "11124", "421314", "421312"])],
  },
  {
    id: "500113",
    name: "תכן בניינים רבי קומות",
    credits: 2.5,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["421314", "421312", "421326"])],
  },
  {
    id: "500114",
    name: "סדנה במבנים",
    credits: 2,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["421312", "421315"])],
    coRequisites: ["421326"],
  },
  {
    id: "421418",
    name: "אקוסטיקת הבנייה",
    credits: 2.5,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["421209"])],
    notes: ["זמין גם כקורס בחירה מחלקתית במסלול הנדסת ניהול הבנייה."],
  },
  {
    id: "500116",
    name: "הנדסת מבנים מתקדמת",
    credits: 2.5,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["421314", "421312"])],
  },
  {
    id: "500117",
    name: "תב\"ם למבנים",
    credits: 1,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["421312"])],
    coRequisites: ["500115", "421326"],
  },
  {
    id: "500118",
    name: "גשרים מבטון ופלדה",
    credits: 2.5,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["421314", "421312"])],
    coRequisites: ["421411"],
  },
  {
    id: "500119",
    name: "הערכה ושיפור עמידות מבנים לרעידות אדמה",
    credits: 2.5,
    type: "elective",
    clusterId: "structural-electives-group1",
    prerequisites: [p(["421326"])],
  },

  // --- מסלול מבנים - קבוצה 2 (לפחות קורס אחד; חלק מהקורסים משותפים למסלול ניהול) ---
  {
    id: "500120",
    name: "עיקרי תכן אדריכלי 2",
    credits: 2.5,
    type: "elective",
    clusterId: "construction-mgmt-electives",
    prerequisites: [p(["421111"])],
    notes: [
      "זמין גם כקורס בחירה בקבוצה 2 של מסלול הנדסת מבנים.",
      "בטבלת קבוצה 2 (מסלול מבנים) מופיע בהיקף 2.0 נ\"ז; בטבלת מסלול ניהול הבנייה מופיע בהיקף 2.5 נ\"ז - נתונים כפי שמופיעים במקור.",
    ],
  },
  {
    id: "500121",
    name: "תכן מבנים ארעיים",
    credits: 2,
    type: "elective",
    clusterId: "structural-electives-group2",
    prerequisites: [p(["421314", "421312"])],
  },

  // --- מסלול ניהול הבנייה - קורסי בחירה מחלקתית ---
  {
    id: "500210",
    name: "ניהול משאבי אנוש בבנייה",
    credits: 2.5,
    type: "elective",
    clusterId: "construction-mgmt-electives",
  },
  {
    id: "500211",
    name: "מבוא לקיים ואחזקת מבנים",
    credits: 2,
    type: "elective",
    clusterId: "construction-mgmt-electives",
  },
  {
    id: "500212",
    name: "בנייה תת קרקעית",
    credits: 2.5,
    type: "elective",
    clusterId: "construction-mgmt-electives",
    prerequisites: [p(["421221", "421313"])],
  },
  {
    id: "500213",
    name: "בנייה ירוקה",
    credits: 2,
    type: "elective",
    clusterId: "construction-mgmt-electives",
  },
  {
    id: "500214",
    name: "מבוא לניהול פיננסי בחברות בנייה",
    credits: 2,
    type: "elective",
    clusterId: "construction-mgmt-electives",
    prerequisites: [p(["421113"])],
  },
  {
    id: "500122",
    name: "סדנה במבנים הנ'",
    credits: 2,
    type: "elective",
    clusterId: "construction-mgmt-electives",
    prerequisites: [p(["421214", "421312", "421324"])],
  },
  {
    id: "421420",
    name: "קורס BIM מתקדם",
    credits: 2,
    type: "elective",
    clusterId: "construction-mgmt-electives",
    prerequisites: [p(["421109", "421111", "421218"])],
  },
  {
    id: "421422",
    name: "מבוא לניהול BIM",
    credits: 2,
    type: "elective",
    clusterId: "construction-mgmt-electives",
    prerequisites: [p(["421109", "421111"])],
    notes: [
      "במקור מודפס קוד קורס הקדם כ-\"4211109\" (ספרה עודפת) עבור מה שברור שהוא 421109 מבוא לגרפיקה הנדסית. תוקן כאן ל-421109; ככל הנראה טעות דפוס בשנתון.",
    ],
  },
  {
    id: "500217",
    name: "מבוא לגשרים",
    credits: 2.5,
    type: "elective",
    clusterId: "construction-mgmt-electives",
    prerequisites: [p(["421420", "500218", "421214", "421312"])],
  },
  {
    id: "500218",
    name: "מערכות בבניינים ובפרויקטי תשתית",
    credits: 2.5,
    type: "elective",
    clusterId: "construction-mgmt-electives",
  },
  ...generalStudiesCourses,
  ...sportCourses,
];

export const degreePlan: DegreePlan = {
  id: "civil-engineering",
  title: "מפת תואר הנדסה אזרחית",
  subtitle: "המכללה האקדמית להנדסה בראודה - שנתון תשפ\"ד (2023-2024)",
  source: {
    fileName: "ידיעונים, שנתונים ולוח שנה אקדמית - המכללה האקדמית להנדסה בראודה בכרמיאל.pdf",
    pages: "63-76",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 160,
    fixedDegreeCredits: 121.5,
    electiveCreditsNeeded: 38.5,
    generalCredits: 6,
    sportCredits: 1,
    englishRequiredIds: ["11061"],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
  ],
  requirementGroups: [
    {
      code: "general-studies",
      name: "לימודים כלליים",
      kind: "credits",
      requiredCredits: 6,
    },
    {
      code: "sport-elective",
      name: "ספורט",
      kind: "credits",
      requiredCredits: 1,
    },
  ],
  clusters,
  courses,
  rules: [
    {
      id: "english-basic-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית בסיסי וגם פטור/סיווג מאנגלית בסיסית.",
      payload: { courseIds: ["11063", "ENG_BASIC_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים א וגם פטור/סיווג מאנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים א חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים ב וגם פטור/סיווג מאנגלית מתקדמים ב.",
      payload: { courseIds: ["11061", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-advanced-a",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-exemptions-single-choice",
      type: "mutual_exclusion",
      message: "ניתן לבחור פטור/סיווג אנגלית אחד בלבד: בסיסי, מתקדמים א או מתקדמים ב.",
      payload: { courseIds: ["ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
  ],
  notes: [
    "לצורך זכאות לתואר יש לצבור לפחות 160 נ\"ז: 113.5 נ\"ז לימודי חובה, 1 נ\"ז מיומנות יסוד הנדסית, 24.0-28.5 נ\"ז התמחות, 10.0-14.5 נ\"ז בחירה מחלקתית, 6 נ\"ז לימודים כלליים ו-1 נ\"ז ספורט.",
    "יש לבחור מסלול התמחות אחד: מסלול הנדסת מבנים או מסלול הנדסת ניהול הבנייה, ולהשלים את כל קורסי החובה של המסלול הנבחר (סמסטרים 3-8).",
    "במסלול הנדסת מבנים: יש להשלים לפחות 2 קורסים מקבוצה 1 ולפחות קורס אחד מקבוצה 2 מתוך קורסי הבחירה בהתמחות.",
    "יש לסיים את לימודי החובה באנגלית עד תום השנה השנייה ללימודים.",
    "קורס צמוד (מסומן בקו תחתי במקור) הוא קורס שניתן להשתתף בו רק אם הקורס שאליו הוא מוצמד נלמד באותו סמסטר.",
    "כמה קורסי בחירה/התמחות משותפים לשני המסלולים ומופיעים במקור ביותר מרשימה אחת (למשל 421412, 421418, 500120); שויכו כאן לאשכול אחד עם הערה על הזמינות הנוספת, בשל מגבלת שיוך יחיד לאשכול בכל קורס.",
    "המסמך הרשמי (שנתון תשפ\"ד) עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
