import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";

import generalAndSportCourses from "../shared/general-and-sport-courses.json";

const all = (ids: string[], label?: string) => ({ mode: "all" as const, ids, label });
const any = (ids: string[], label: string) => ({ mode: "any" as const, ids, label });

const generalStudiesCourses: Course[] = generalAndSportCourses.general.map((course) => ({
  ...course,
  type: "general",
  requirementGroup: "general-studies",
}));

const sportCourses: Course[] = generalAndSportCourses.sport.map((course) => ({
  ...course,
  type: "sport",
  requirementGroup: "sport",
}));

const clusters: ElectiveCluster[] = [
  { id: "learning-systems", name: "מסלול מערכות לומדות", minCourses: 0 },
  { id: "general-track", name: "מסלול כללי", minCourses: 0 },
];

const requiredCourses: Course[] = [
  {
    id: "ENG_BASIC_OK",
    name: "פטור/סיווג מאנגלית בסיסית",
    credits: 0,
    type: "placement",
  },
  {
    id: "ENG_ADV_A_OK",
    name: "פטור/סיווג מאנגלית מתקדמים א",
    credits: 0,
    type: "placement",
  },
  {
    id: "ENG_ADV_B_OK",
    name: "פטור/סיווג מאנגלית מתקדמים ב",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11060",
  },
  {
    id: "11063",
    name: "אנגלית בסיסי",
    credits: 0,
    type: "english",
    semester: 1,
    notes: ["לפי סיווג באנגלית."],
  },
  {
    id: "11064",
    name: "אנגלית מתקדמים א'",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסי או סיווג מתאים")],
    notes: ["לפי סיווג באנגלית."],
  },
  { id: "11004", name: "חדו\"א 1מ", credits: 5, type: "required", required: true, semester: 1 },
  { id: "61740", name: "מערכות ספרתיות", credits: 2.5, type: "required", required: true, semester: 1 },
  { id: "61743", name: "מתמטיקה דיסקרטית 1", credits: 3, type: "required", required: true, semester: 1 },
  { id: "65001", name: "מבוא למדעי המחשב למדמ\"ח", credits: 4, type: "required", required: true, semester: 1 },
  { id: "65002", name: "אלגברה 1 (מדמ\"ח)", credits: 5, type: "required", required: true, semester: 1 },
  {
    id: "251961",
    name: "מיומנויות יסוד הנדסיות",
    credits: 1,
    type: "required",
    required: true,
    semester: 1,
  },
  { id: "11006", name: "חדו\"א 2מ", credits: 5, type: "required", required: true, semester: 2, prerequisites: [all(["11004"])] },
  {
    id: "61739",
    name: "מבני נתונים ומבוא לאלגוריתמים",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [
      any(["11063", "ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], "אנגלית בסיסי או סיווג מתאים"),
      all(["61743", "65001"]),
    ],
  },
  { id: "61778", name: "לוגיקה להנדסת תוכנה", credits: 3, type: "required", required: true, semester: 2, prerequisites: [all(["61743"])] },
  {
    id: "65003",
    name: "אלגברה 2 (מדמ\"ח)",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [all(["65002", "61743"])],
  },
  { id: "65004", name: "תכנות מערכות (פייתון)", credits: 2.5, type: "required", required: true, semester: 2, prerequisites: [all(["65001"])] },
  {
    id: "11060",
    name: "אנגלית מתקדמים ב'",
    credits: 2,
    type: "english",
    required: true,
    semester: 3,
    prerequisites: [any(["11064", "ENG_ADV_A_OK"], "אנגלית מתקדמים א או סיווג מתאים")],
  },
  {
    id: "61751",
    name: "תכנות מונחה עצמים",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [all(["61739", "65004"])],
    notes: ["בדף המקור מופיע 65003 לצד השם תכנות מערכות (פייתון); הקוד 65003 הוא אלגברה 2, ולכן הקדם ממופה ל-65004 לפי שם הקורס והופעתו בסמסטר 2."],
  },
  {
    id: "61753",
    name: "אלגוריתמים",
    credits: 5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [all(["11006", "61739", "61778", "65003"])],
  },
  {
    id: "61774",
    name: "יסודות המחשוב",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [all(["61740", "65004"])],
  },
  {
    id: "61832",
    name: "מבוא להסתברות וסטטיסטיקה",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [all(["11006", "61739", "65003"])],
  },
  {
    id: "65005",
    name: "מבוא לאופטימיזציה",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [all(["11006", "65001", "65003"])],
  },
  {
    id: "61752",
    name: "מערכות הפעלה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [any(["65004", "61745"], "תכנות מערכות (פייתון) או מבוא לתכנות מערכות") , all(["61774"])],
    notes: ["בדף המקור מופיע 61745 כקדם. 65004 הוא קורס תכנות המערכות שמופיע בתוכנית החדשה; שתי האפשרויות נתמכות כדי לא לחסום סטודנטים ותיקים."],
  },
  {
    id: "61761",
    name: "כריית נתונים ומערכות לומדות",
    credits: 4,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [all(["61753", "61832", "65004"])],
  },
  { id: "61773", name: "מבוא למחשוב ענן", credits: 3, type: "required", required: true, semester: 4, prerequisites: [all(["61751"])] },
  { id: "65006", name: "מודלים חישוביים", credits: 5, type: "required", required: true, semester: 4, prerequisites: [all(["61753"])] },
  { id: "65007", name: "מבוא ללמידה עמוקה", credits: 3, type: "required", required: true, semester: 4, prerequisites: [all(["61753", "61832"])] },
  {
    id: "65008",
    name: "שפות תכנות לעיבוד מידע",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [all(["61751", "61761", "65004", "65005"])],
  },
  {
    id: "65009",
    name: "פרויקט מסכם",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [all(["11060", "61752", "65006", "65007", "65008"])],
  },
];

const learningSystemsElectives: Course[] = [
  { id: "61775", name: "מבוא לבינה מלאכותית", credits: 2.5, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61753", "61832"])] },
  { id: "61776", name: "טכנולוגיות אינטרנט מתקדמות WEB", credits: 4, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61752"])] },
  { id: "61779", name: "סמינר בנושאים נבחרים בבינה מלאכותית", credits: 3, type: "elective", clusterId: "learning-systems", prerequisites: [all(["11060", "61775"])] },
  { id: "61954", name: "למידה עמוקה יוצרת", credits: 3, type: "elective", clusterId: "learning-systems", prerequisites: [all(["65007"])] },
  { id: "61966", name: "סמינר במערכות לומדות", credits: 3, type: "elective", clusterId: "learning-systems", prerequisites: [all(["11060", "65007"])] },
  { id: "61967", name: "סמינר באלגוריתמים אקראיים", credits: 3, type: "elective", clusterId: "learning-systems", prerequisites: [all(["11060", "61753", "61832"])] },
  { id: "61968", name: "סמינר באלגוריתמים מתקדמים", credits: 3, type: "elective", clusterId: "learning-systems", prerequisites: [all(["11060", "61753"])] },
  { id: "61975", name: "דחיסת נתונים", credits: 2.5, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61832"])] },
  { id: "61982", name: "מעבדה במידול מערכות אקולוגיות", credits: 2.5, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61753", "61773"])] },
  { id: "61992", name: "מבוא לחישה ולמידה", credits: 3, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61753"])] },
  { id: "61994", name: "למידה עמוקה עבור ראיית מכונה", credits: 2.5, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61751", "65007"])] },
  { id: "61995", name: "אלגוריתמים לטקסטים ורצפים", credits: 2.5, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61753", "61832"])] },
  { id: "62002", name: "עיבוד שפה טבעית עם למידה עמוקה", credits: 3, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61751", "65007"])] },
  { id: "62010", name: "מעבדה בניתוח נתונים", credits: 2.5, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61832"])] },
  { id: "62012", name: "מעבדה ב DevOps", credits: 2.5, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61751"])] },
  { id: "65010", name: "סוגיות באתיקה של AI", credits: 3, type: "elective", clusterId: "learning-systems", prerequisites: [all(["61775"])] },
];

const generalTrackElectives: Course[] = [
  { id: "61755", name: "מערכות מסדי נתונים מ'", credits: 4, type: "elective", clusterId: "general-track", prerequisites: [all(["61739"])] },
  { id: "61763", name: "תורת הקומפילציה", credits: 2.5, type: "elective", clusterId: "general-track", prerequisites: [all(["65006"])] },
  { id: "61764", name: "גרפיקה ממוחשבת", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["61751", "65002"])] },
  { id: "61765", name: "רשתות מחשבים", credits: 3.5, type: "elective", clusterId: "general-track", prerequisites: [all(["61751", "61753"])] },
  { id: "61914", name: "בלוקצ'ין ומטבעות קריפטו", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["61751"])] },
  { id: "61957", name: "תורת המשחקים", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["61832"])] },
  { id: "61958", name: "תורת המידע", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["61832"])] },
  { id: "61969", name: "סמינר באימות תוכנה", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["11060", "65006"])] },
  { id: "61972", name: "עיבוד אותות ספרתי DSP", credits: 2.5, type: "elective", clusterId: "general-track", prerequisites: [all(["11006", "65003"])] },
  { id: "61985", name: "מעבדה בפיתוח יישומים באנדרואיד", credits: 2.5, type: "elective", clusterId: "general-track", prerequisites: [all(["61751", "61752"])] },
  { id: "61988", name: "מעבדה בעיצוב תבניות בתוכנה", credits: 2.5, type: "elective", clusterId: "general-track", prerequisites: [all(["61751"])] },
  { id: "61991", name: "תכנות מדעי", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["61753", "61832"])] },
  { id: "62001", name: "תכנות מקבילי", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["61752"])] },
  { id: "62005", name: "סמינר בהתאמת תבניות", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["11060", "61753"])] },
  { id: "62008", name: "מערכות משובצות מחשב", credits: 2.5, type: "elective", clusterId: "general-track", prerequisites: [all(["61751", "61774"])] },
  { id: "62013", name: "אלגוריתמים ומבני נתונים במחרוזות", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["61753"])] },
  { id: "65011", name: "אלגוריתמים קוונטים", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["61832"])] },
  { id: "65012", name: "סמינר בתורת הצפינה", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["11060", "61832"])] },
  { id: "65013", name: "אימות פורמלי של מערכות ריאקטיביות", credits: 3, type: "elective", clusterId: "general-track", prerequisites: [all(["65006"])] },
];

const seminarCourseIds = ["61779", "61966", "61967", "61968", "61969", "62005", "65012"];
const laboratoryCourseIds = ["61982", "62010", "62012", "61985", "61988"];

export const degreePlan: DegreePlan = {
  id: "computer-science-2027",
  title: "מפת תואר מדעי המחשב",
  subtitle: "B.Sc תלת-שנתי במדעי המחשב - שנתון תשפ\"ז (2026-2027)",
  catalogYear: 'תשפ"ז (2026-2027)',
  status: "active",
  source: {
    fileName: "התוכנית למדעי המחשב (.B.Sc)",
    pages: "https://w3.braude.ac.il/comp-sci-plan/",
    extractedAt: "2026-07-11",
  },
  requirements: {
    totalCredits: 120,
    fixedDegreeCredits: 91,
    electiveCreditsNeeded: 29,
    generalCredits: 4,
    sportCredits: 1,
    englishRequiredIds: ["11060"],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
  ],
  requirementGroups: [
    { code: "general-studies", name: "לימודים כלליים", kind: "credits", requiredCredits: 4 },
    { code: "sport", name: "ספורט", kind: "credits", requiredCredits: 1 },
    {
      code: "seminar",
      name: "סמינר בחירה",
      kind: "courses",
      minCourses: 1,
      courseIds: seminarCourseIds,
      metadata: { countsTowardFixedCredits: false },
    },
    {
      code: "laboratory",
      name: "מעבדת בחירה",
      kind: "courses",
      minCourses: 1,
      courseIds: laboratoryCourseIds,
      metadata: { countsTowardFixedCredits: false },
    },
  ],
  clusters,
  courses: [...requiredCourses, ...learningSystemsElectives, ...generalTrackElectives, ...generalStudiesCourses, ...sportCourses],
  rules: [
    {
      id: "english-basic-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית בסיסי וגם פטור/סיווג מאנגלית בסיסית.",
      payload: { courseIds: ["11063", "ENG_BASIC_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים א וגם פטור/סיווג מאנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים א חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים ב וגם פטור/סיווג מאנגלית מתקדמים ב.",
      payload: { courseIds: ["11060", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-advanced-a",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-exemptions-single-choice",
      type: "mutual_exclusion",
      message: "ניתן לבחור פטור/סיווג אנגלית אחד בלבד: בסיסי, מתקדמים א או מתקדמים ב.",
      payload: { courseIds: ["ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
  ],
  notes: [
    "המסלול הוא תלת-שנתי. יש לבחור קורסי בחירה עד להשלמת 120 נ\"ז, כולל לפחות סמינר אחד ומעבדה אחת.",
    "האתר הרשמי מציג שני מסלולי בחירה: מערכות לומדות ומסלול כללי. אפשרויות שני המסלולים מוצגות כאן לבחירה ולתכנון.",
    "החובה בשפה האנגלית כוללת שני קורסים באנגלית, שלפחות אחד מהם קורס תוכן, לפי ההנחיה באתר התוכנית.",
  ],
};
