import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";
import generalAndSportCourses from "../shared/general-and-sport-courses.json";

const generalStudiesCourses: Course[] = generalAndSportCourses.general.map((course) => ({
  ...course,
  type: "general",
  required: false,
  requirementGroup: "general-studies",
}));

const sportCourses: Course[] = generalAndSportCourses.sport.map((course) => ({
  ...course,
  type: "sport",
  required: false,
  requirementGroup: "sport-elective",
}));

const clusters: ElectiveCluster[] = [
  {
    id: "computers",
    name: "התמחות מחשבים (חומרה ותוכנה)",
    minCourses: 6,
    note: "התמחות ראשית: לפחות 20 נ\"ז ולפחות 6 קורסי חובה בהתמחות (3 חומרה + 3 תוכנה). התמחות משנית (נדרשת רק במסלולי תכן הנדסי מחקרי/בתעשייה): לפחות 10 נ\"ז ולפחות 3 קורסי חובה.",
  },
  {
    id: "signals-comm",
    name: "התמחות עיבוד אותות ותקשורת",
    minCourses: 4,
    note: "התמחות ראשית: לפחות 20 נ\"ז ולפחות 4 קורסי חובה בהתמחות. התמחות משנית: לפחות 10 נ\"ז ולפחות 3 קורסי חובה.",
  },
  {
    id: "devices-optics",
    name: "התמחות התקנים ואלקטרואופטיקה",
    minCourses: 4,
    note: "התמחות ראשית: לפחות 20 נ\"ז ולפחות 4 קורסי חובה בהתמחות. התמחות משנית: לפחות 10 נ\"ז ולפחות 3 קורסי חובה.",
  },
  {
    id: "shared-electives",
    name: "קורסי בחירה משותפים למספר התמחויות",
    minCourses: 0,
    note: "קורסים אלה אינם ייחודיים להתמחות מסוימת וניתן לשלבם כקורסי בחירה נוספים בכל אחת מההתמחויות.",
  },
  {
    id: "multidisciplinary",
    name: "רצועה רב-תחומית",
    minCourses: 0,
    note: "ניתן לשלב עד 3 נ\"ז מרצועה זו במסגרת לימודי ההתמחות והבחירה; אינה מהווה התמחות בפני עצמה. רשימת הקורסים מתעדכנת מעת לעת.",
  },
];

const p = (ids: string[], label?: string) => ({ mode: "all" as const, ids, label });
const any = (ids: string[], label: string) => ({
  mode: "any" as const,
  ids,
  label,
});

const courses: Course[] = [
  // --- English placement / exemption pseudo-courses (mirrors the psychometric-score
  // exemption chain described in footnote 1: 11063 -> 11064 -> 11057) ---
  {
    id: "ENG_BASIC_OK",
    name: "פטור/סיווג מאנגלית בסיסית",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שאינם צריכים ללמוד 11063 בפועל."],
  },
  {
    id: "ENG_ADV_A_OK",
    name: "פטור/סיווג מאנגלית מתקדמים א",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שמתחילים מאנגלית מתקדמים ב או מעליה."],
  },
  {
    id: "ENG_ADV_B_OK",
    name: "פטור/סיווג מאנגלית מתקדמים ב",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11057",
    notes: ["מיועד לסטודנטים הפטורים מכל חובות האנגלית עד רמת מתקדמים ב (כולל)."],
  },

  // --- Semester 1 ---
  { id: "11002", name: "אלגברה מ", credits: 5, type: "required", required: true, semester: 1 },
  { id: "11004", name: "חדו\"א 1 מ'", credits: 5, type: "required", required: true, semester: 1 },
  {
    id: "11063",
    name: "אנגלית בסיסי",
    credits: 0,
    type: "english",
    semester: 1,
    notes: ["לפי סיווג באנגלית (ציון פסיכומטרי 90-99); אינו נספר בסיכום סמסטר 1 בטבלה."],
  },
  { id: "31230", name: "מבוא למחשבים", credits: 2.5, type: "required", required: true, semester: 1 },
  { id: "31511", name: "מיתוג ומערכות ספרתיות", credits: 4, type: "required", required: true, semester: 1 },
  { id: "41090", name: "כימיה א", credits: 2.5, type: "required", required: true, semester: 1 },
  {
    id: "251961",
    name: "מיומנויות יסוד הנדסיות",
    credits: 1,
    type: "required",
    required: true,
    semester: 1,
    notes: ["חובה ללמוד בשנה א', בסמסטר 1 או 2."],
  },

  // --- Semester 2 ---
  {
    id: "11006",
    name: "חדו\"א 2מ",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11004"])],
    coRequisites: ["11002"],
  },
  {
    id: "11064",
    name: "אנגלית מתקדמים א'",
    credits: 0,
    type: "english",
    semester: 2,
    prerequisites: [any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסית או פטור/סיווג")],
    notes: ["לפי סיווג באנגלית (ציון פסיכומטרי 100-119); אינו נספר בסיכום סמסטר 2 בטבלה."],
  },
  {
    id: "11121",
    name: "משוואות דיפרנציאליות רגילות",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11004", "11002"])],
  },
  {
    id: "11231",
    name: "פיזיקה 1מ",
    credits: 4.5,
    type: "required",
    required: true,
    semester: 2,
    coRequisites: ["11004"],
  },
  {
    id: "31316",
    name: "מבוא להנדסת חשמל",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11004", "11002"])],
  },
  {
    id: "31616",
    name: "מבוא למדעי המחשב ושפת C",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
  },

  // --- Semester 3 ---
  {
    id: "11057",
    name: "אנגלית מתקדמים ב'",
    credits: 2,
    type: "english",
    required: true,
    semester: 3,
    prerequisites: [any(["11064", "ENG_ADV_A_OK"], "אנגלית מתקדמים א או פטור/סיווג")],
    notes: ["יש לסיים את שרשרת לימודי האנגלית עד סוף הסמסטר הרביעי (מומלץ עד סוף הסמסטר השלישי)."],
  },
  {
    id: "11122",
    name: "משוואות דיפרנציאליות חלקיות וטורי פורייה",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11006", "11121"])],
  },
  {
    id: "11123",
    name: "פונקציות מרוכבות",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11006", "11121"])],
  },
  {
    id: "11232",
    name: "פיזיקה 2מ",
    credits: 4.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11231"])],
  },
  {
    id: "31350",
    name: "מוליכים למחצה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["31316", "41090"])],
    coRequisites: ["11232"],
  },
  {
    id: "51742",
    name: "הסתברות ויסודות הסטטיסטיקה",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11006"])],
  },

  // --- Semester 4 ---
  {
    id: "31401",
    name: "תורת האלקטרוניקה התקבילית",
    credits: 5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["31350"])],
    coRequisites: ["31402"],
    notes: ["יש ללמוד בצמוד את 31402 (מעבדת חשמל ואלקטרוניקה 1)."],
  },
  {
    id: "31402",
    name: "מעבדת חשמל ואלקטרוניקה 1",
    credits: 2,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["31350"])],
    coRequisites: ["31401"],
    notes: ["יש ללמוד בצמוד את 31401 (תורת האלקטרוניקה התקבילית)."],
  },
  {
    id: "31421",
    name: "אותות ומערכות",
    credits: 5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11122"])],
  },
  {
    id: "31700",
    name: "שדות ותמסורת גלים",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11232", "31316"])],
  },
  {
    id: "31891",
    name: "מידול וסימולציה של מערכות דינמיות",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11006", "11121", "11232", "31316"])],
  },

  // --- Semester 5 ---
  {
    id: "31403",
    name: "מעבדת חשמל ואלקטרוניקה 2",
    credits: 2,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["31402"])],
    coRequisites: ["31521"],
    notes: ["יש ללמוד בצמוד את 31521 (אלקטרוניקה ספרתית)."],
  },
  {
    id: "31442",
    name: "מבוא לעיבוד אותות ספרתי",
    credits: 3,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["11057", "31421"])],
  },
  {
    id: "31521",
    name: "אלקטרוניקה ספרתית",
    credits: 4,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["31511", "31401"])],
    coRequisites: ["31403"],
    notes: ["יש ללמוד בצמוד את 31403 (מעבדת חשמל ואלקטרוניקה 2)."],
  },
  {
    id: "31711",
    name: "מבוא לתקשורת",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["31316", "31421", "51742"])],
  },
  {
    id: "31910",
    name: "מבוא לבקרה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["11122", "31891"])],
  },
  {
    id: "31999",
    name: "המרת אנרגיה א'",
    credits: 3,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["31700"])],
  },

  // --- Semester 6 ---
  {
    id: "11233",
    name: "פיזיקה 3מ",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["11232"])],
  },
  {
    id: "31017",
    name: "פרויקט תחרותי",
    credits: 3,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["31403"])],
  },
  {
    id: "31451",
    name: "אותות אקראיים ורעש",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["31421", "51742"])],
  },

  // --- Semester 7 ---
  {
    id: "31101",
    name: "תכן הנדסי א'",
    credits: 3,
    type: "required",
    required: true,
    semester: 7,
    coRequisites: ["31017"],
  },

  // --- Semester 8: choose exactly ONE of the three תכן הנדסי ב' tracks (footnote 3) ---
  // Footnote 4: these three courses share the same 7 "prereq-or-parallel" corequisites,
  // i.e. each of the 7 courses may be studied before or concurrently with תכן הנדסי ב'.
  {
    id: "31102",
    name: "תכן הנדסי ב' – פרויקט גמר",
    credits: 3,
    type: "required",
    semester: 8,
    requirementGroup: "final-project-track",
    prerequisites: [p(["31101"])],
    coRequisites: ["11233", "31442", "31451", "31521", "31711", "31910", "31999"],
    notes: [
      "ניתן לבחור רק באחת משלוש האפשרויות: פרויקט גמר, מחקרי או בתעשייה.",
      "יש להירשם לשני חלקי התכן ההנדסי (א' ו-ב') בסמסטרים עוקבים.",
    ],
  },
  {
    id: "31103",
    name: "תכן הנדסי ב' – מחקרי",
    credits: 5,
    type: "required",
    semester: 8,
    requirementGroup: "final-project-track",
    prerequisites: [p(["31101"])],
    coRequisites: ["11233", "31442", "31451", "31521", "31711", "31910", "31999"],
    notes: [
      "ניתן לבחור רק באחת משלוש האפשרויות: פרויקט גמר, מחקרי או בתעשייה.",
      "מחייב השלמת התמחות ראשית והתמחות משנית.",
    ],
  },
  {
    id: "31104",
    name: "תכן הנדסי ב' – בתעשייה",
    credits: 7,
    type: "required",
    semester: 8,
    requirementGroup: "final-project-track",
    prerequisites: [p(["31101"])],
    coRequisites: ["11233", "31442", "31451", "31521", "31711", "31910", "31999"],
    notes: [
      "ניתן לבחור רק באחת משלוש האפשרויות: פרויקט גמר, מחקרי או בתעשייה.",
      "מחייב השלמת התמחות ראשית אחת ומקצועות בחירה נוספים (אינו מחייב התמחות משנית).",
    ],
  },

  // --- Specialization: מחשבים (חומרה ותוכנה) ---
  {
    id: "31215",
    name: "מיקרו-מעבדים",
    credits: 4,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31230"])],
    notes: ["חובה בהתמחות מחשבים (חומרה)."],
  },
  {
    id: "31226",
    name: "מיקרו-בקרים",
    credits: 4,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31230", "31616"])],
    notes: ["חובה בהתמחות מחשבים (חומרה)."],
  },
  {
    id: "31245",
    name: "מערכות לומדות ולמידה עמוקה",
    credits: 3.5,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["51742"])],
    // Source data-quality note: the yearbook prints this course's corequisite as 31422
    // ("מבוא לעיבוד אותות ספרתי") in all three specialization tables that list 31245.
    // Every other occurrence of "מבוא לעיבוד אותות ספרתי" in this chapter (mandatory
    // semester 5, and as a prerequisite of 31655/31471/31651) uses code 31442. This is
    // almost certainly a document typo, so 31442 is used here (the consistently-used code).
    coRequisites: ["31442"],
    notes: [
      "חובה בהתמחות (מחשבים-תוכנה, עיבוד אותות ותקשורת, והתקנים ואלקטרואופטיקה גם יחד).",
      "המקור מציין קורס צמוד בקוד 31422; זהו כנראה טעות דפוס עבור 31442 (מבוא לעיבוד אותות ספרתי), הקוד המופיע בעקביות בכל שאר האזכורים בשנתון. נעשה שימוש בקוד 31442.",
    ],
  },
  {
    id: "31261",
    name: "מערכות הפעלה",
    credits: 3,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31281"])],
    notes: ["חובה בהתמחות מחשבים (תוכנה)."],
  },
  {
    id: "31500",
    name: "תכן לוגי",
    credits: 2.5,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31230", "31511"])],
    notes: ["חובה בהתמחות מחשבים (חומרה)."],
  },
  {
    id: "31551",
    name: "התקנים לוגיים מתוכנתים",
    credits: 3.5,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31511"])],
    notes: ["חובה בהתמחות מחשבים (חומרה)."],
  },
  {
    id: "31632",
    name: "מבני נתונים ואלגוריתמים",
    credits: 3,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31281"])],
    notes: ["חובה בהתמחות מחשבים (תוכנה)."],
  },
  {
    id: "31695",
    name: "תכנות מכוון אובייקטים",
    credits: 3,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31616"])],
    notes: ["חובה בהתמחות מחשבים (תוכנה)."],
  },
  {
    id: "31270",
    name: "ארכיטקטורה ומבנה מחשבים",
    credits: 2.5,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31500"])],
  },
  {
    id: "31570",
    name: "מעגלים ספרתיים",
    credits: 2.5,
    type: "elective",
    clusterId: "computers",
    prerequisites: [p(["31521"])],
  },
  {
    id: "61996",
    name: "אלגוריתמים מבוזרים",
    credits: 2.5,
    type: "elective",
    clusterId: "computers",
    prerequisites: [
      any(["61753", "31632"], "אלגוריתמים (61753, מקטלוג הנדסת תוכנה) או מבני נתונים ואלגוריתמים (31632)"),
    ],
    notes: ["61753 שייך לקטלוג הקורסים של הנדסת תוכנה; מוצע כאן כחלופה מוכרת."],
  },

  // --- Specialization: עיבוד אותות ותקשורת ---
  {
    id: "31251",
    name: "רשתות מחשבים ותקשורת",
    credits: 3.5,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31616"])],
    notes: ["חובה בהתמחות עיבוד אותות ותקשורת."],
  },
  {
    id: "31361",
    name: "מכשור אלקטרוני",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31401"])],
    notes: ["חובה בהתמחות עיבוד אותות ותקשורת."],
  },
  {
    id: "31471",
    name: "מעבדה לעיבוד אותות",
    credits: 3,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31442"])],
    notes: ["חובה בהתמחות עיבוד אותות ותקשורת."],
  },
  {
    id: "31476",
    name: "יישומי Matlab באלקטרוניקה",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31421", "31616"])],
    notes: ["חובה בהתמחות עיבוד אותות ותקשורת."],
  },
  {
    id: "31561",
    name: "תכנות מעבדי DSP",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31616"])],
    notes: ["חובה בהתמחות עיבוד אותות ותקשורת."],
  },
  {
    id: "31651",
    name: "עיבוד תמונה",
    credits: 4,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31442"])],
    notes: ["חובה בהתמחות עיבוד אותות ותקשורת."],
  },
  {
    id: "31724",
    name: "תקשורת ספרתית",
    credits: 3,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31711", "31442", "31891"])],
    coRequisites: ["31451"],
    notes: ["חובה בהתמחות עיבוד אותות ותקשורת.", "יש ללמוד בצמוד את 31451 (אותות אקראיים ורעש)."],
  },
  {
    id: "31485",
    name: "עיבוד וידאו והדמיה רפואית",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31442"])],
  },
  {
    id: "31740",
    name: "טכניקות קליטה ושידור",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["11122", "11123"])],
  },
  {
    id: "31991",
    name: "מבוא למערכות מכ\"ם",
    credits: 2.5,
    type: "elective",
    clusterId: "signals-comm",
    prerequisites: [p(["31700", "31711"])],
    notes: ["מופיע גם ברשימת קורסי התמחות התקנים ואלקטרואופטיקה בלבד."],
  },

  // --- Specialization: התקנים ואלקטרואופטיקה ---
  {
    id: "31088",
    name: "התקנים אלקטרוניים מתקדמים",
    credits: 3.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["31350"])],
    notes: ["חובה בהתמחות התקנים ואלקטרואופטיקה."],
  },
  {
    id: "31715",
    name: "רכיבי מערכות תקשורת אופטית",
    credits: 3.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["31350", "31711"])],
    notes: ["חובה בהתמחות התקנים ואלקטרואופטיקה."],
  },
  {
    id: "31820",
    name: "מעבדה מתקדמת לאפיון התקנים",
    credits: 2.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["31350"])],
    notes: ["חובה בהתמחות התקנים ואלקטרואופטיקה."],
  },
  {
    id: "31840",
    name: "אלקטרוניקה של מערכות הספק",
    credits: 2.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["31401"])],
    notes: ["חובה בהתמחות התקנים ואלקטרואופטיקה."],
  },
  {
    id: "31980",
    name: "מבוא לאלקטרו-אופטיקה",
    credits: 2.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["11233"])],
    notes: ["חובה בהתמחות התקנים ואלקטרואופטיקה."],
  },
  {
    id: "391411",
    name: "גלים ואופטיקה",
    credits: 4,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["31700", "11122"])],
    notes: ["חובה בהתמחות התקנים ואלקטרואופטיקה."],
  },
  {
    id: "391310",
    name: "מקורות אור ולייזרים",
    credits: 3.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["11232", "31350", "391411"])],
    notes: ["חובה בהתמחות התקנים ואלקטרואופטיקה."],
  },
  {
    id: "391412",
    name: "מעבדה באופטיקה",
    credits: 2,
    type: "elective",
    clusterId: "devices-optics",
    coRequisites: ["391411"],
    notes: ["חובה בהתמחות התקנים ואלקטרואופטיקה.", "יש ללמוד בצמוד את 391411 (גלים ואופטיקה)."],
  },
  {
    id: "391321",
    name: "רדיומטריה ודטקציה של קרינה א\"מ",
    credits: 2.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["391411"])],
    coRequisites: ["31350"],
    notes: [
      "חובה בהתמחות התקנים ואלקטרואופטיקה.",
      "391411 הוא קורס קדם רגיל; 31350 (מוליכים למחצה) הוא קורס צמוד.",
    ],
  },
  {
    id: "31802",
    name: "אנרגיה מתחדשת",
    credits: 2.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["31999"])],
  },
  {
    id: "31985",
    name: "רכיבים אלקטרואופטיים",
    credits: 2.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["31350", "31700"])],
  },
  {
    id: "391415",
    name: "מעבדה באופטיקה מתקדמת 1",
    credits: 2,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["391411", "391412"])],
  },
  {
    id: "391419",
    name: "תכן רכיבים ומערכות אופטיות (זימקס)",
    credits: 3,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["391411"])],
  },
  {
    id: "391421",
    name: "תכנון אופטי מתקדם בעזרת תכנות זימקס",
    credits: 2,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["391419"])],
  },
  {
    id: "391525",
    name: "מערכות דימות",
    credits: 2.5,
    type: "elective",
    clusterId: "devices-optics",
    prerequisites: [p(["391321"])],
  },

  // --- Shared electives (available across multiple specializations) ---
  {
    id: "31060",
    name: "סמינר מחלקתי 1",
    credits: 0.25,
    type: "elective",
    clusterId: "shared-electives",
    notes: ["הרשמה לקורס מחייבת נוכחות בכל הסמינרים המחלקתיים המתקיימים אחת לחודש במשך כל סמסטר."],
  },
  {
    id: "31061",
    name: "סמינר מחלקתי 2",
    credits: 0.25,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31060"])],
    notes: ["הרשמה לקורס מחייבת נוכחות בכל הסמינרים המחלקתיים המתקיימים אחת לחודש במשך כל סמסטר."],
  },
  {
    id: "31090",
    name: "תכן מעגלים משולבים אנלוגיים",
    credits: 3,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31401"])],
  },
  {
    id: "31105",
    name: "מתמטיקה דיסקרטית להנדסת אלקטרוניקה",
    credits: 3,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["11002"])],
  },
  {
    id: "31281",
    name: "תכנות בשפת פייתון",
    credits: 2.5,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31616"])],
  },
  {
    id: "31285",
    name: "מבוא לתכן כרטיסים",
    credits: 2.5,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31521", "31403"])],
  },
  {
    id: "31363",
    name: "מכשור רפואי",
    credits: 2.5,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31401"])],
  },
  {
    id: "31540",
    name: "מבוא ל-VLSI",
    credits: 2.5,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31521"])],
  },
  {
    id: "31565",
    name: "עיבוד אותות בזמן אמת - DSP",
    credits: 2.5,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31421", "31616"])],
  },
  {
    id: "31653",
    name: "זיהוי תצורות",
    credits: 2.5,
    type: "elective",
    clusterId: "shared-electives",
    coRequisites: ["31245", "31651"],
    notes: ["יש ללמוד בצמוד את 31245 (מערכות לומדות ולמידה עמוקה) ואת 31651 (עיבוד תמונה)."],
  },
  {
    id: "31655",
    name: "ראייה ממוחשבת",
    credits: 2.5,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31442"])],
  },
  {
    id: "31880",
    name: "תאימות אלקטרומגנטית (EMC)",
    credits: 2.5,
    type: "elective",
    clusterId: "shared-electives",
    prerequisites: [p(["31700"])],
  },

  // --- Multidisciplinary track (רצועה רב-תחומית, footnote 6) ---
  { id: "51301", name: "יסודות השיווק", credits: 2, type: "elective", clusterId: "multidisciplinary" },
  {
    id: "51625",
    name: "מבוא לכלכלה למהנדסי אלקטרוניקה",
    credits: 1.5,
    type: "elective",
    clusterId: "multidisciplinary",
  },
  {
    id: "51160",
    name: "הנדסת מערכות ותעשייה",
    credits: 2.5,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  {
    id: "251100",
    name: "פרויקט בינתחומי",
    credits: 3,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  {
    id: "251504",
    name: "הנדסת יזמות - גישת ההזנק הרזה",
    credits: 2,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  {
    id: "251506",
    name: "מבוא ליזמות וקניין רוחני",
    credits: 2,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  { id: "251507", name: "מבוא ליזמות", credits: 1, type: "elective", clusterId: "multidisciplinary" },
  {
    id: "251509",
    name: "חשיבה המצאתית",
    credits: 2,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  {
    id: "251512",
    name: "מבוא לניהול חדשנות ויזמות פנים ארגונית",
    credits: 2,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  {
    id: "251513",
    name: "חשיבה יצירתית שיטתית",
    credits: 2,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  {
    id: "251514",
    name: "מבוא לפיתוח אב טיפוס",
    credits: 2,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  {
    id: "251520",
    name: "להשאיר את החותם האישי",
    credits: 2,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  {
    id: "251965",
    name: "מהנדסים למען הגיל השלישי",
    credits: 2,
    type: "elective",
    clusterId: "multidisciplinary",
    prerequisites: [p(["31421"])],
  },
  ...generalStudiesCourses,
  ...sportCourses,
];

export const degreePlan: DegreePlan = {
  id: "electrical-engineering",
  title: "מפת תואר הנדסת חשמל ואלקטרוניקה",
  subtitle: "המכללה האקדמית להנדסה בראודה - שנתון תשפ\"ד",
  catalogYear: 'תשפ"ד (2023-2024)',
  status: "archived",
  source: {
    fileName: "ידיעונים, שנתונים ולוח שנה אקדמית - בראודה.pdf",
    pages: "88-102",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 160,
    fixedDegreeCredits: 128,
    electiveCreditsNeeded: 32,
    generalCredits: 6,
    sportCredits: 1,
    englishRequiredIds: ["11057"],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [
    {
      code: "final-project-track",
      name: "מסלול תכן הנדסי ב' - בחירת אחד משלושה",
      kind: "alternative",
      minCourses: 1,
      courseIds: ["31102", "31103", "31104"],
    },
    {
      code: "general-studies",
      name: "לימודים כלליים",
      kind: "credits",
      requiredCredits: 6,
    },
    {
      code: "sport-elective",
      name: "ספורט",
      kind: "credits",
      requiredCredits: 1,
    },
  ],
  clusters,
  courses,
  rules: [
    {
      id: "final-project-track-mutual-exclusion",
      type: "mutual_exclusion",
      message:
        "ניתן לבחור מסלול אחד בלבד עבור תכן הנדסי ב': פרויקט גמר (31102), מחקרי (31103) או בתעשייה (31104).",
      payload: { courseIds: ["31102", "31103", "31104"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-basic-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית בסיסי וגם פטור/סיווג מאנגלית בסיסית.",
      payload: { courseIds: ["11063", "ENG_BASIC_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים א וגם פטור/סיווג מאנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים א חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים ב וגם פטור/סיווג מאנגלית מתקדמים ב.",
      payload: { courseIds: ["11057", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-advanced-a",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-exemptions-single-choice",
      type: "mutual_exclusion",
      message: "ניתן לבחור פטור/סיווג אנגלית אחד בלבד: בסיסי, מתקדמים א או מתקדמים ב.",
      payload: { courseIds: ["ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
  ],
  notes: [
    "לצורך זכאות לתואר יש לצבור לפחות 160 נ\"ז (ולא יותר מ-165 נ\"ז).",
    "התוכנית כוללת כ-128 נ\"ז לימודי חובה ולפחות 32 נ\"ז לימודי התמחות ובחירה. סך נ\"ז תכן הנדסי (חלקים א'+ב') משתנה לפי המסלול: 10 נ\"ז בתכן הנדסי בתעשייה, 8 נ\"ז בתכן הנדסי מחקרי, 6 נ\"ז בפרויקט גמר.",
    "יש לבחור מסלול אחד בלבד עבור תכן הנדסי ב': פרויקט גמר (31102, 3 נ\"ז), מחקרי (31103, 5 נ\"ז) או בתעשייה (31104, 7 נ\"ז); יש להירשם לשני חלקי התכן ההנדסי (א' ו-ב') בסמסטרים עוקבים.",
    "הקורסים 11233, 31442, 31451, 31521, 31711, 31910 ו-31999 ילמדו כקורס קדם או כקורס מקביל (צמוד) לחלק ב' של התכן ההנדסי.",
    "המחלקה מציעה שלוש התמחויות: מחשבים (חומרה ותוכנה), עיבוד אותות ותקשורת, והתקנים ואלקטרואופטיקה. התמחות ראשית דורשת לפחות 20 נ\"ז ולפחות 4 קורסי חובה (בהתמחות מחשבים: לפחות 6, 3 חומרה ו-3 תוכנה). התמחות משנית (נדרשת רק במסלולי התכן ההנדסי המחקרי או בתעשייה) דורשת לפחות 10 נ\"ז ולפחות 3 קורסי חובה.",
    "ניתן לשלב עד 3 נ\"ז מהרצועה הרב-תחומית במסגרת לימודי ההתמחות והבחירה.",
    "יש ללמוד לפחות שני קורסים בשפה האנגלית במהלך התואר, לפחות אחד מהם קורס תוכן; יש לסיים את שרשרת האנגלית עד סוף הסמסטר הרביעי (מומלץ עד סוף הסמסטר השלישי).",
    "קורסים בלימודים כלליים ובספורט הנכללים בלימודי החובה אינם משובצים לסמסטר קבוע בטבלאות המחלקה וניתן לשלבם בכל סמסטר.",
    "פטור מכל קורסי האנגלית יינתן לסטודנטים שקיבלו בפרק האנגלית בבחינה הפסיכומטרית ציון 134 ומעלה.",
    "המסמך הרשמי עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
