import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";
import generalAndSportCourses from "../shared/general-and-sport-courses.json";

const generalStudiesCourses: Course[] = generalAndSportCourses.general.map((course) => ({
  ...course,
  type: "general",
  required: false,
  requirementGroup: "general-studies",
}));

const sportCourses: Course[] = generalAndSportCourses.sport.map((course) => ({
  ...course,
  type: "sport",
  required: false,
  requirementGroup: "sport-elective",
}));

const clusters: ElectiveCluster[] = [
  { id: "sciences", name: "אשכול מדעים", minCourses: 1 },
  { id: "software", name: "אשכול הנדסת תוכנה", minCourses: 1 },
  {
    id: "design-ops-management",
    name: "אשכול תכן, תפעול וניהול",
    minCourses: 1,
  },
];

const p = (ids: string[], label?: string) => ({ mode: "all" as const, ids, label });
const any = (ids: string[], label: string) => ({
  mode: "any" as const,
  ids,
  label,
});

const courses: Course[] = [
  {
    id: "ENG_BASIC_OK",
    name: "פטור/סיווג מאנגלית בסיסית",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שאינם צריכים ללמוד 11063 בפועל."],
  },
  {
    id: "ENG_ADV_A_OK",
    name: "פטור/סיווג מאנגלית מתקדמים א",
    credits: 0,
    type: "placement",
    notes: ["מיועד לסטודנטים שמתחילים מאנגלית מתקדמים ב או מעליה."],
  },
  {
    id: "ENG_ADV_B_OK",
    name: "פטור/סיווג מאנגלית מתקדמים ב",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11060",
    notes: ["מיועד לסטודנטים הפטורים מכל חובות האנגלית עד רמת מתקדמים ב (כולל)."],
  },
  {
    id: "11063",
    name: "אנגלית בסיסי",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [],
    notes: ["לפי סיווג באנגלית; אינו נספר בסיכום סמסטר 1 בטבלה."],
  },
  {
    id: "11064",
    name: "אנגלית מתקדמים א",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסית או פטור/סיווג")],
    notes: ["לפי סיווג באנגלית; אינו נספר בסיכום סמסטר 1 בטבלה."],
  },
  {
    id: "251961",
    name: "מיומנויות יסוד הנדסיות",
    credits: 1,
    type: "required",
    required: true,
    semester: 1,
    notes: ["חובה ללמוד בשנה הראשונה."],
  },
  {
    id: "11004",
    name: "חדו\"א 1מ",
    credits: 5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11102",
    name: "אלגברה 1 מח",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "61740",
    name: "מערכות ספרתיות",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "61741",
    name: "מבוא למדעי המחשב",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "61830",
    name: "מבוא להנדסת מערכות מידע",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 1,
    notes: ["קורס זה יינתן אחת לשנה בלבד ויש לעקוב אחר פרסומי המחלקה."],
  },
  {
    id: "11006",
    name: "חדו\"א 2מ",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11004"])],
    coRequisites: ["11102"],
  },
  {
    id: "11060",
    name: "אנגלית מתקדמים ב",
    credits: 2,
    type: "english",
    required: true,
    semester: 2,
    prerequisites: [any(["11064", "ENG_ADV_A_OK"], "אנגלית מתקדמים א או סיווג מתאים")],
  },
  {
    id: "61738",
    name: "מבנים אלגבריים להנדסת תוכנה 1",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11102"])],
  },
  {
    id: "61743",
    name: "מתמטיקה דיסקרטית 1",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "61745",
    name: "מבוא לתכנות מערכות",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["61741"])],
  },
  {
    id: "61750",
    name: "מבוא להנדסת תוכנה",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["61741"])],
  },
  {
    id: "51709",
    name: "הסתברות",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11004", "61743"])],
  },
  {
    id: "61739",
    name: "מבני נתונים ומבוא לאלגוריתמים",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [
      any(
        ["11063", "ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"],
        "אנגלית בסיסית או פטור/סיווג מתאים"
      ),
      p(["61743", "61745"]),
    ],
    notes: ["קורס קדם 11063 חל על סטודנטים אשר החלו לימודיהם בשנה\"ל תשפ\"ג (2023) ואילך."],
  },
  {
    id: "61774",
    name: "יסודות המחשוב",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["61740", "61750"])],
  },
  {
    id: "61778",
    name: "לוגיקה להנדסת תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["61743", "61738"])],
  },
  {
    id: "61911",
    name: "מבנים אלגבריים להנדסת תוכנה 2",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["61743", "61738"])],
  },
  {
    id: "61912",
    name: "ארכיטקטורת מערכות תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["61750"])],
  },
  {
    id: "11069",
    name: "אנגלית טכנית יישומית - תוכנה",
    credits: 1,
    type: "english",
    required: true,
    semester: 4,
    prerequisites: [any(["11060", "ENG_ADV_B_OK"], "אנגלית מתקדמים ב או פטור/סיווג")],
  },
  {
    id: "61751",
    name: "תכנות מונחה עצמים",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["61739", "61750"])],
  },
  {
    id: "61752",
    name: "מערכות הפעלה",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["61745", "61774"])],
  },
  {
    id: "61753",
    name: "אלגוריתמים",
    credits: 5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11006", "61738", "61739", "61778"])],
  },
  {
    id: "61755",
    name: "מערכות מסדי נתונים מ",
    credits: 4,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["61739"])],
  },
  {
    id: "61762",
    name: "ניהול פרויקטי תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["61750", "61830", "61912"])],
  },
  {
    id: "51702",
    name: "מודלים דטרמיניסטים בחקב\"צ",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["61911"])],
  },
  {
    id: "51703",
    name: "מודלים סטוכסטיים בחקב\"צ",
    credits: 4,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["11006", "51709"])],
  },
  {
    id: "51958",
    name: "סטטיסטיקה למערכות מידע",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["51709"])],
  },
  {
    id: "61756",
    name: "שיטות הנדסיות לפיתוח מערכות תוכנה",
    credits: 5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [
      any(["11060", "ENG_ADV_B_OK"], "אנגלית מתקדמים ב או פטור/סיווג"),
      p(["61751", "61755", "61762"]),
    ],
    coRequisites: ["61757", "61769"],
    notes: ["יש ללמוד בצמוד את 61757 ואת 61769."],
  },
  {
    id: "61757",
    name: "מבוא לבדיקות תוכנה",
    credits: 2,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [
      any(["11060", "ENG_ADV_B_OK"], "אנגלית מתקדמים ב או פטור/סיווג"),
      p(["61751", "61755", "61762"]),
    ],
    coRequisites: ["61756", "61769"],
    notes: ["קורסי הקדם של 61756 שיטות הנדסיות לפיתוח מערכות תוכנה חלים גם על קורס זה."],
  },
  {
    id: "61769",
    name: "ממשק אדם מחשב",
    credits: 2,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [
      any(["11060", "ENG_ADV_B_OK"], "אנגלית מתקדמים ב או פטור/סיווג"),
      p(["61751", "61755", "61762"]),
    ],
    coRequisites: ["61756", "61757"],
    notes: ["קורסי הקדם של 61756 שיטות הנדסיות לפיתוח מערכות תוכנה חלים גם על קורס זה."],
  },
  {
    id: "51617",
    name: "חשבונאות פיננסית",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 6,
  },
  {
    id: "51957",
    name: "מערכות ארגוניות וניהול",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["11060", "61830"])],
    notes: [
      "קורס זה יינתן אחת לשנה בלבד ויש לעקוב אחר פרסומי המחלקה.",
      "ניתן ללמוד קורס זה במקביל לקורס 61831 ניהול ידע, אך אין זו חובה (קורס צמוד רשות).",
    ],
  },
  {
    id: "61179",
    name: "מבוא לפיזיקה להנדסת תוכנה",
    credits: 0,
    type: "required",
    semester: 6,
    prerequisites: [p(["11006", "61738", "61741"])],
    coRequisites: ["61180"],
    notes: ["מיועד למי שאין לו פטור מפיזיקה אקדמית; חובה ללמוד בצמוד ל-61180 ולא ניתן ללומדו בנפרד."],
  },
  {
    id: "61180",
    name: "פיזיקה להנדסת תוכנה ל'",
    credits: 3,
    type: "required",
    semester: 6,
    requirementGroup: "physics",
    prerequisites: [p(["11006", "61738", "61741"])],
    coRequisites: ["61179"],
    notes: ["מיועד למי שאין לו פטור מפיזיקה אקדמית; חובה ללמוד בצמוד ל-61179. אחת מחלופות הפיזיקה לזכאות לתואר."],
  },
  {
    id: "61181",
    name: "פיזיקה להנדסת תוכנה",
    credits: 3,
    type: "required",
    semester: 6,
    requirementGroup: "physics",
    prerequisites: [p(["11006", "61738", "61741"])],
    notes: [
      "מיועד לסטודנטים שיש להם פטור מפיזיקה אקדמית (פטור מקורס 12179 או שלמדו 11179/11279 מבוא לפיזיקה אקדמית).",
      "אחת מחלופות הפיזיקה לזכאות לתואר.",
    ],
  },
  {
    id: "11158",
    name: "מכניקה להנדסת תוכנה",
    credits: 3,
    type: "required",
    semester: 6,
    requirementGroup: "physics",
    notes: [
      "קורס חליפי לקורסי הפיזיקה 61180/61181 עבור מי שלמד אותו בעבר.",
      "אחת מחלופות הפיזיקה לזכאות לתואר.",
    ],
  },
  {
    id: "61761",
    name: "כריית נתונים ומערכות לומדות",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["51709", "61753"])],
  },
  {
    id: "61776",
    name: "טכנולוגיות אינטרנט מתקדמות (web)",
    credits: 4,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["61752", "61756"])],
  },
  {
    id: "51955",
    name: "חשבונאות ניהולית ומימון",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["51617"])],
  },
  {
    id: "51956",
    name: "מבוא לכלכלה מיקרו",
    credits: 3,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["11004"])],
  },
  {
    id: "61767",
    name: "אבטחת מידע וקריפטולוגיה",
    credits: 4,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["61753", "61911"])],
  },
  {
    id: "61831",
    name: "ניהול ידע",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["61756", "51958"])],
    notes: ["ניתן ללמוד את 51957 מערכות ארגוניות וניהול במקביל לקורס זה, אך אין זו חובה (קורס צמוד רשות, לא חובה)."],
  },
  {
    id: "61998",
    name: "פרויקט מסכם שלב א'",
    credits: 4,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [
      p(["11069", "51703", "61752", "61756", "61761", "61776"]),
      any(["61180", "61181", "11158"], "אחת מחלופות הפיזיקה"),
    ],
  },
  {
    id: "61999",
    name: "פרויקט מסכם שלב ב'",
    credits: 4,
    type: "required",
    required: true,
    semester: 8,
    prerequisites: [p(["61998"])],
  },
  {
    id: "11129",
    name: "טורים, התמרות ומשוואות דיפרנציאליות",
    credits: 4,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["11006", "61738"])],
  },
  {
    id: "41942",
    name: "מבוא לביולוגיה מולקולרית וגנטיקה להנדסת תוכנה",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61957",
    name: "תורת המשחקים",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["11102", "51709"])],
  },
  {
    id: "61958",
    name: "תורת המידע",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["11006", "51709", "61911"])],
  },
  {
    id: "61959",
    name: "אנליזה נומרית",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["11006", "61738", "61741"])],
  },
  {
    id: "61967",
    name: "סמינר באלגוריתמים אקראיים",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["11069", "51709", "61753"])],
    notes: ["קורס באנגלית."],
  },
  {
    id: "61968",
    name: "סמינר באלגוריתמים מתקדמים",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["11069", "61753"])],
    notes: ["קורס באנגלית."],
  },
  {
    id: "61982",
    name: "מעבדה במידול מערכות אקולוגיות",
    credits: 2.5,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["11006", "61738"])],
  },
  {
    id: "61989",
    name: "מחשבים קוונטים",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61738"])],
  },
  {
    id: "61991",
    name: "תכנות מדעי",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["51709", "61753"])],
  },
  {
    id: "61992",
    name: "מבוא לחישה ולמידה",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61993",
    name: "תורת המשחקים האלגוריתמית",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["51709", "61753"])],
  },
  {
    id: "61994",
    name: "למידה עמוקה עבור ראיית מכונה",
    credits: 2.5,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["61751", "61761"])],
  },
  {
    id: "62005",
    name: "סמינר בהתאמת תבניות",
    credits: 3,
    type: "elective",
    clusterId: "sciences",
    prerequisites: [p(["11069", "61753"])],
    notes: ["קורס באנגלית."],
  },
  {
    id: "61834",
    name: "מסדי נתונים מבוזרים",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61753", "61756"])],
  },
  {
    id: "61764",
    name: "גרפיקה ממוחשבת",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["11102", "61745"])],
  },
  {
    id: "61765",
    name: "רשתות מחשבים",
    credits: 3.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751", "61753"])],
  },
  {
    id: "61775",
    name: "מבוא לבינה מלאכותית",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["51709", "61753"])],
  },
  {
    id: "61779",
    name: "סמינר בנושאים נבחרים בבינה מלאכותית",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["11069", "61761"])],
    notes: ["קורס באנגלית.", "מי שלמד בעבר את 61963 בינה מלאכותית אינו יכול ללמוד סמינר זה."],
  },
  {
    id: "61914",
    name: "בלוקצ'יין ומטבעות קריפטו",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751"])],
  },
  {
    id: "61954",
    name: "למידה עמוקה יוצרת",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61755", "61761"])],
  },
  {
    id: "61961",
    name: "אחזור מידע",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61761"])],
  },
  {
    id: "61964",
    name: "ויזואליזציה של מידע",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751"])],
  },
  {
    id: "61965",
    name: "ניתוח של נתוני הרשתות",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61966",
    name: "סמינר מערכות לומדות",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["11069", "61761"])],
    notes: ["קורס באנגלית."],
  },
  {
    id: "61971",
    name: "עיבוד תמונה ספרתי",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["11006", "61738"])],
  },
  {
    id: "61975",
    name: "דחיסת נתונים",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61739", "51709"])],
  },
  {
    id: "61980",
    name: "שפות תכנות",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751"])],
  },
  {
    id: "61981",
    name: "הנדסת דרישות",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61750"])],
  },
  {
    id: "61983",
    name: "מעבדה בתכנות מקבילי והטרוגני",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751", "61752"])],
  },
  {
    id: "61985",
    name: "מעבדה בפיתוח יישומים באנדרואיד",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751", "61752"])],
  },
  {
    id: "61986",
    name: "מעבדה בסחר אלקטרוני",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61750"])],
  },
  {
    id: "61987",
    name: "מעבדה בכריית נתונים",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61761"])],
  },
  {
    id: "61988",
    name: "מעבדה בעיצוב תבניות בתוכנה",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61750", "61751"])],
  },
  {
    id: "61990",
    name: "מעבדה בטכנולוגיות תכנות צד לקוח ושרת",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61750", "61751"])],
  },
  {
    id: "61995",
    name: "אלגוריתמים לטקסטים ורצפים",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["51709", "61753"])],
  },
  {
    id: "61996",
    name: "אלגוריתמים מבוזרים",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61753"])],
  },
  {
    id: "61997",
    name: "סמינר בחישוב מבוזר",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["11069", "51702", "61753"])],
    notes: ["קורס באנגלית."],
  },
  {
    id: "62001",
    name: "תכנות מקבילי",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61752", "61756"])],
  },
  {
    id: "62002",
    name: "עיבוד שפה טבעית עם למידה עמוקה",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61751", "61761"])],
  },
  {
    id: "62003",
    name: "פרויקט במציאות רבודה",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61756", "61761"])],
  },
  {
    id: "62004",
    name: "מבוא להנדסת מערכות ותעשייה 4.0 להנדסת תוכנה",
    credits: 2.5,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61756"])],
  },
  {
    id: "62006",
    name: "דרישות במערכות IOT",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61750"])],
  },
  {
    id: "251100",
    name: "פרויקט בין-תחומי",
    credits: 3,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61741", "61830"])],
    notes: [
      "קורס באחריות האקדמית של המרכז לחינוך הנדסי ויזמות.",
      "באשכול הנדסת תוכנה ניתן לקחת אחד משני קורסי הכוכבית (251100 או 251965), אך לא את שניהם.",
    ],
  },
  {
    id: "251965",
    name: "מהנדסים למען הגיל השלישי",
    credits: 2,
    type: "elective",
    clusterId: "software",
    prerequisites: [p(["61741", "61830"])],
    notes: [
      "קורס באחריות האקדמית של המרכז לחינוך הנדסי ויזמות.",
      "באשכול הנדסת תוכנה ניתן לקחת אחד משני קורסי הכוכבית (251100 או 251965), אך לא את שניהם.",
    ],
  },
  {
    id: "51106",
    name: "מערכות מלאי",
    credits: 2.5,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["51132"])],
  },
  {
    id: "51131",
    name: "ניהול מערכות ייצור",
    credits: 4,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["11006", "51702", "51958"])],
  },
  {
    id: "51132",
    name: "תכנון ותפעול תהליך האספקה בארגון",
    credits: 4,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["11006", "51702", "51958"])],
  },
  {
    id: "51147",
    name: "תכנון משאבים ודרישות חומרים",
    credits: 3,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["51132", "61750"])],
  },
  {
    id: "51154",
    name: "מבוא ל-ERP ומערכות ארגוניות",
    credits: 3,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["51132"])],
  },
  {
    id: "51202",
    name: "אמינות",
    credits: 2.5,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["51958"])],
  },
  {
    id: "51213",
    name: "ניהול איכות סטטיסטי",
    credits: 4,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["51958"])],
  },
  {
    id: "51430",
    name: "תכנון פרויקטים וניהולם",
    credits: 3,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["51702", "51709"])],
  },
  {
    id: "51724",
    name: "סימולציה ספרתית",
    credits: 3,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["51955", "51703", "61741"])],
  },
  {
    id: "61984",
    name: "מעבדה באופטימיזציה",
    credits: 2.5,
    type: "elective",
    clusterId: "design-ops-management",
    prerequisites: [p(["11006", "61745"])],
  },
  ...generalStudiesCourses,
  ...sportCourses,
];

export const degreePlan: DegreePlan = {
  id: "information-systems-engineering",
  title: "מפת תואר הנדסת מערכות מידע",
  subtitle: "המכללה האקדמית להנדסה בראודה - רפורמה 2020",
  catalogYear: 'תשפ"ד (2023-2024)',
  status: "archived",
  source: {
    fileName: "ידיעונים, שנתונים ולוח שנה אקדמית - בראודה.pdf",
    pages: "147-158",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 160,
    fixedDegreeCredits: 145,
    electiveCreditsNeeded: 15,
    generalCredits: 6,
    sportCredits: 1,
    englishRequiredIds: ["11060", "11069"],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [
    {
      code: "physics",
      name: "חלופת פיזיקה אחת",
      kind: "alternative",
      requiredCredits: 3,
      minCourses: 1,
      courseIds: ["61180", "61181", "11158"],
    },
    {
      code: "general-studies",
      name: "לימודים כלליים",
      kind: "credits",
      requiredCredits: 6,
    },
    {
      code: "sport-elective",
      name: "ספורט",
      kind: "credits",
      requiredCredits: 1,
    },
  ],
  clusters,
  courses,
  rules: [
    {
      id: "software-star-mutual-exclusion",
      type: "mutual_exclusion",
      message: "באשכול הנדסת תוכנה ניתן לקחת אחד משני קורסי הכוכבית, אך לא את שניהם.",
      payload: { courseIds: ["251100", "251965"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-basic-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית בסיסי וגם פטור/סיווג מאנגלית בסיסית.",
      payload: { courseIds: ["11063", "ENG_BASIC_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים א וגם פטור/סיווג מאנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים א חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים ב וגם פטור/סיווג מאנגלית מתקדמים ב.",
      payload: { courseIds: ["11060", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-advanced-a",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-exemptions-single-choice",
      type: "mutual_exclusion",
      message: "ניתן לבחור פטור/סיווג אנגלית אחד בלבד: בסיסי, מתקדמים א או מתקדמים ב.",
      payload: { courseIds: ["ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "physics-alternative-mutual-exclusion",
      type: "mutual_exclusion",
      message: "ניתן לבחור חלופת פיזיקה אחת בלבד: 61180 (בצמוד ל-61179), 61181 או 11158.",
      payload: { courseIds: ["61180", "61181", "11158"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "physics-intro-lab-mutual-exclusion",
      type: "mutual_exclusion",
      message: "קורס 61179 נלמד רק בצמוד ל-61180; אינו תואם לחלופות 61181 או 11158.",
      payload: { courseIds: ["61179", "61181", "11158"], maxSelected: 1 },
      enabled: true,
    },
  ],
  notes: [
    "לצורך זכאות לתואר יש לצבור לפחות 160.0 נ\"ז.",
    "התוכנית כוללת 6 נ\"ז לימודים כלליים, 1 נ\"ז ספורט ו-1 נ\"ז מיומנויות יסוד הנדסיות.",
    "יש ללמוד לפחות קורס אחד מכל אשכול בחירה (מדעים, הנדסת תוכנה, תכן תפעול וניהול), ולהשלים קורסי בחירה עד 160 נ\"ז.",
    "חובה לסיים את שרשרת לימודי האנגלית עד סוף סמסטר 4, כמפורט בפרק היחידה ללימודי אנגלית בשנתון.",
    "בסמסטר 5 חובה ללמוד את 61757 ואת 61769 בצמוד ל-61756; קורסי הקדם של 61756 חלים גם על שני הקורסים הצמודים לו.",
    "בסמסטר 6, קורס 61179 נלמד רק בצמוד לקורס 61180 ולהיפך; שני הקורסים מיועדים למי שאין לו פטור מפיזיקה אקדמית. סטודנטים עם פטור לומדים את 61181 בלבד, ומי שלמד בעבר את 11158 מכניקה להנדסת תוכנה פטור גם הוא מ-61180/61179/61181.",
    "51617 חשבונאות פיננסית ו-51957 מערכות ארגוניות וניהול הם קורסי חובה בתוכנית (סמסטר 6) ואינם חלק מאשכול הבחירה תכן, תפעול וניהול.",
    "ניתן ללמוד את 51957 מערכות ארגוניות וניהול במקביל לקורס 61831 ניהול ידע, אך אין זו חובה - קורס צמוד רשות בלבד.",
    "באשכול הנדסת תוכנה ניתן לקחת אחד משני קורסי הכוכבית (251100, 251965) בלבד, ולא את שניהם.",
    "המסמך הרשמי עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
