import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";
import generalAndSportCourses from "../shared/general-and-sport-courses.json";

const generalStudiesCourses: Course[] = generalAndSportCourses.general.map((course) => ({
  ...course,
  type: "general",
  required: false,
  requirementGroup: "general-studies",
}));

const sportCourses: Course[] = generalAndSportCourses.sport.map((course) => ({
  ...course,
  type: "sport",
  required: false,
  requirementGroup: "sport-elective",
}));

const clusters: ElectiveCluster[] = [
  { id: "track-design-mfg", name: "מסלול תכן וייצור", minCourses: 4, note: "4 קורסי חובה במסלול (ללא תחליף) בתוספת קורסי בחירה והעשרה במסלול, עד לצבירת 28.5 נ\"ז בהתמחות. תנאי קדם ללימוד קורסי ההתמחות: השלמת קורסי היסוד." },
  { id: "track-mechatronics", name: "מסלול מכטרוניקה", minCourses: 4, note: "4 קורסי חובה במסלול (ללא תחליף) בתוספת קורסי בחירה והעשרה במסלול, עד לצבירת 28.5 נ\"ז בהתמחות. תנאי קדם ללימוד קורסי ההתמחות: השלמת קורסי היסוד." },
  { id: "track-biomechanics", name: "מסלול ביומכניקה", minCourses: 4, note: "4 קורסי חובה במסלול (ללא תחליף) בתוספת קורסי בחירה והעשרה במסלול, עד לצבירת 28.5 נ\"ז בהתמחות. תנאי קדם ללימוד קורסי ההתמחות: השלמת קורסי היסוד." },
  { id: "track-industry40", name: "מסלול תעשייה מתקדמת בעידן המידע (תעשייה 4.0)", minCourses: 3, note: "3 קורסי חובה במסלול לפי המקור (ללא תחליף) בתוספת קורסי בחירה והעשרה במסלול, עד לצבירת 28.5 נ\"ז בהתמחות. תנאי קדם ללימוד קורסי ההתמחות: השלמת קורסי היסוד." },
];

const p = (ids: string[], label?: string) => ({ mode: "all" as const, ids, label });
const any = (ids: string[], label: string) => ({
  mode: "any" as const,
  ids,
  label,
});

const courses: Course[] = [
  {
    id: "ENG_BASIC_OK",
    name: "פטור/סיווג מאנגלית בסיסית",
    credits: 0,
    type: "placement",
    notes: [
      "מיועד לסטודנטים שאינם צריכים ללמוד 11063 בפועל (ציון פסיכומטרי 100-119 ומעלה).",
    ],
  },
  {
    id: "ENG_ADV_A_OK",
    name: "פטור/סיווג מאנגלית מתקדמים א",
    credits: 0,
    type: "placement",
    notes: [
      "מיועד לסטודנטים שמתחילים מאנגלית מתקדמים ב' או מעליה (ציון פסיכומטרי 120 ומעלה).",
    ],
  },
  {
    id: "ENG_ADV_B_OK",
    name: "פטור/סיווג מאנגלית מתקדמים ב",
    credits: 0,
    type: "placement",
    satisfiesCourseId: "11061",
    notes: [
      "מיועד לסטודנטים הפטורים מכל חובות האנגלית עד רמת מתקדמים ב' (כולל).",
    ],
  },
  {
    id: "11063",
    name: "אנגלית בסיסי",
    credits: 0,
    type: "english",
    semester: 1,
    notes: [
      "לפי סיווג באנגלית (ציון פסיכומטרי 85-99); חובה ללמוד את שרשרת האנגלית לפי פרק היחידה ללימודי אנגלית בשנתון.",
    ],
  },
  {
    id: "11064",
    name: "אנגלית מתקדמים א'",
    credits: 0,
    type: "english",
    semester: 1,
    prerequisites: [any(["11063", "ENG_BASIC_OK"], "אנגלית בסיסי או ציון פסיכומטרי 100-119")],
    notes: [
      "ניתן ללמוד גם בסמסטר 1 וגם בסמסטר 2, בהתאם לסיווג.",
    ],
  },
  {
    id: "11061",
    name: "אנגלית מתקדמים ב'",
    credits: 2,
    type: "english",
    required: true,
    semester: 3,
    prerequisites: [any(["11064", "ENG_ADV_A_OK"], "אנגלית מתקדמים א' או ציון פסיכומטרי 120-133")],
    notes: [
      "יש לסיים את לימודי האנגלית עד תום השנה השנייה ללימודים.",
      "קורס האנגלית הנדרש היחיד להשלמת שרשרת האנגלית בתוכנית זו.",
    ],
  },
  {
    id: "11001",
    name: "אלגברה",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11003",
    name: "חדו\"א 1",
    credits: 5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11179",
    name: "מבוא לפיזיקה אקדמית",
    credits: 0,
    type: "required",
    semester: 1,
    notes: [
      "ניתן פטור למי שלמד פיזיקה ברמת 5 יח\"ל וקיבל ציון 75 ומעלה, או שעבר קורס הכנה במכינת קדם-הנדסה במכללה.",
    ],
  },
  {
    id: "41077",
    name: "כימיה מכ",
    credits: 4,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "22112",
    name: "מבוא לגרפיקה הנדסית",
    credits: 3,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "22705",
    name: "מבוא יצירתי להנדסת מכונות",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 1,
    notes: [
      "ניתן ללמוד בסמסטר 1 (מומלץ לפטורי פיזיקה אקדמית) או בסמסטר 2.",
    ],
  },
  {
    id: "251961",
    name: "מיומנויות יסוד הנדסיות",
    credits: 1,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "11005",
    name: "חדו\"א 2",
    credits: 5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11003"])],
  },
  {
    id: "22511",
    name: "דינמיקה של חלקיקים",
    credits: 4.5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11179", "11001"])],
    coRequisites: ["22305", "11005"],
  },
  {
    id: "22305",
    name: "מכניקת מוצקים 1",
    credits: 4,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["11003", "11001"])],
  },
  {
    id: "22400",
    name: "הנדסת חומרים",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 2,
    prerequisites: [p(["41077"])],
  },
  {
    id: "22106",
    name: "מבוא לאלגוריתמיקה ותכנות",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "11133",
    name: "משוואות דיפרנציאליות מכ",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["11001"])],
    coRequisites: ["11005"],
  },
  {
    id: "11212",
    name: "פיזיקה 2מכ",
    credits: 4.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["22511"])],
    coRequisites: ["11005"],
  },
  {
    id: "22114",
    name: "תיב\"ם",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["22112"])],
  },
  {
    id: "22310",
    name: "מכניקת מוצקים 2",
    credits: 4,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["22305", "22705"])],
  },
  {
    id: "22205",
    name: "טכנולוגיה יישומית",
    credits: 1.5,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["22400"])],
    coRequisites: ["22114"],
  },
  {
    id: "22415",
    name: "מעבדה בחוזק וחומרים",
    credits: 1,
    type: "required",
    required: true,
    semester: 3,
    prerequisites: [p(["22400"])],
    coRequisites: ["22310"],
  },
  {
    id: "31375",
    name: "חשמל ואלקטרוניקה מכ",
    credits: 5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11212"])],
  },
  {
    id: "22600",
    name: "תרמודינמיקה",
    credits: 4,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11133"])],
  },
  {
    id: "22512",
    name: "דינמיקה של גוף קשיח",
    credits: 4,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["22305", "11005", "22511"])],
  },
  {
    id: "22715",
    name: "מבוא לתכן מכני",
    credits: 4,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["22400", "22310"])],
  },
  {
    id: "22210",
    name: "מבוא לתהליכי ייצור",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["22205", "22400"])],
    coRequisites: ["22112"],
  },
  {
    id: "22800",
    name: "אותות ומערכות",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 4,
    prerequisites: [p(["11001", "22106", "11133"])],
    coRequisites: ["31375"],
  },
  {
    id: "22130",
    name: "אנליזה נומרית",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["22106", "11133"])],
  },
  {
    id: "22810",
    name: "מבוא לבקרה",
    credits: 3,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["22800"])],
  },
  {
    id: "22610",
    name: "מכניקת זורמים",
    credits: 4,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["11133", "22600"])],
  },
  {
    id: "22735",
    name: "פרויקט תכן מכני",
    credits: 2.5,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["22715", "22512"])],
    coRequisites: ["22114"],
  },
  {
    id: "22520",
    name: "תורת הרטט",
    credits: 3,
    type: "required",
    required: true,
    semester: 5,
    prerequisites: [p(["22512", "22310", "11133"])],
    coRequisites: ["22800"],
  },
  {
    id: "22720",
    name: "תכן רכיבים מכניים",
    credits: 3,
    type: "elective",
    semester: 5,
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22715", "22512"])],
    notes: [
      "קורס חובה במסלול תכן וייצור (אינו ניתן להחלפה); נלמד גם כבחירה במסלולי מכטרוניקה ותעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22861",
    name: "מבוא למערכות מכטרוניות",
    credits: 3.5,
    type: "elective",
    semester: 5,
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22800", "31375"])],
    coRequisites: ["22810"],
    notes: [
      "קורס חובה במסלול מכטרוניקה (אינו ניתן להחלפה); נלמד גם כבחירה במסלול ביומכניקה.",
    ],
  },
  {
    id: "22467",
    name: "מבוא לביומכניקה",
    credits: 3,
    type: "elective",
    semester: 5,
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["22512", "22310"])],
    notes: [
      "קורס חובה במסלול ביומכניקה (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22993",
    name: "תעשייה 4.0 - המפעל החכם",
    credits: 3.5,
    type: "elective",
    semester: 5,
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["22800"])],
    notes: [
      "קורס חובה במסלול תעשייה מתקדמת בעידן המידע (אינו ניתן להחלפה); נלמד גם כבחירה במסלולים תכן וייצור, מכטרוניקה וביומכניקה.",
      "נ\"ז 3.5 לפי רוב המופעים במקור; בטבלת הבחירה של מסלול תכן וייצור מופיע ברישום נ\"ז 3.0 (חוסר עקביות במקור).",
    ],
  },
  {
    id: "22620",
    name: "מעבר חום",
    credits: 3,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["22600", "22610"])],
  },
  {
    id: "22635",
    name: "מעבדה בתופעות מעבר",
    credits: 1,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["22610"])],
    coRequisites: ["22620"],
  },
  {
    id: "22745",
    name: "תכן הנדסי מתקדם",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["22715"])],
    coRequisites: ["22735"],
  },
  {
    id: "11213",
    name: "פיזיקה 3מכ",
    credits: 3,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["11212"])],
  },
  {
    id: "51700",
    name: "הסתברות וסטטיסטיקה מכ",
    credits: 3,
    type: "required",
    required: true,
    semester: 6,
    prerequisites: [p(["11005"])],
  },
  {
    id: "22251",
    name: "תהליכי עיבוד שבבי",
    credits: 3.5,
    type: "elective",
    semester: 6,
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22210"])],
    notes: [
      "קורס חובה במסלול תכן וייצור (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22267",
    name: "הנדסת חומרים מתקדמת",
    credits: 2.5,
    type: "elective",
    semester: 6,
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22400"])],
    notes: [
      "קורס חובה במסלול תכן וייצור (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22862",
    name: "מעבדה במכטרוניקה",
    credits: 2,
    type: "elective",
    semester: 6,
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22810"])],
    notes: [
      "קורס חובה במסלול מכטרוניקה (אינו ניתן להחלפה); נלמד גם כבחירה במסלולי ביומכניקה ותעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22864",
    name: "בקרה מודרנית",
    credits: 3,
    type: "elective",
    semester: 6,
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22810"])],
    notes: [
      "קורס חובה במסלול מכטרוניקה (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22472",
    name: "פולימרים בביומכניקה",
    credits: 3.5,
    type: "elective",
    semester: 6,
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["41077", "22600", "22310", "22467"])],
    notes: [
      "קורס חובה במסלול ביומכניקה (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22855",
    name: "גוף האדם כמערכת הנדסית",
    credits: 2.5,
    type: "elective",
    semester: 6,
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["22471"])],
    notes: [
      "קורס חובה במסלול ביומכניקה (אינו ניתן להחלפה); קורס הקדם 22471 נלמד עצמו בסמסטר 7 - ראה סדר לימוד גמיש בין קורסי ההתמחות.",
    ],
  },
  {
    id: "22992",
    name: "מבוא לרובוטים אוטונומיים",
    credits: 3.5,
    type: "elective",
    semester: 6,
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["22106", "22800", "22512", "31375"])],
    notes: [
      "קורס חובה במסלול תעשייה מתקדמת בעידן המידע (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22900",
    name: "התנסות בתעשייה",
    credits: 5,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["22745", "22512", "22735", "22810", "22610", "22520", "22620"])],
    notes: [
      "תנאי סף נוספים: מעמד אקדמי תקין בתום שנה ג' וצבירת 115 נ\"ז לפחות.",
    ],
  },
  {
    id: "22921",
    name: "פרויקט מסכם שלב א'",
    credits: 4,
    type: "required",
    required: true,
    semester: 7,
    prerequisites: [p(["22745", "22512", "22735", "22810", "22610", "22520", "22620"])],
    coRequisites: ["22900"],
    notes: [
      "תנאי סף נוספים: מעמד אקדמי תקין בתום שנה ג' וצבירת 115 נ\"ז לפחות.",
    ],
  },
  {
    id: "22268",
    name: "חוזק מתקדם",
    credits: 2.5,
    type: "elective",
    semester: 7,
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22310"])],
    notes: [
      "קורס חובה במסלול תכן וייצור (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22863",
    name: "תכן מערכות משולבות",
    credits: 3,
    type: "elective",
    semester: 7,
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22862", "22864"])],
    notes: [
      "קורס חובה במסלול מכטרוניקה (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22471",
    name: "ניתוח הנדסי של מערכות פיזיולוגיות",
    credits: 2.5,
    type: "elective",
    semester: 7,
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["41077"])],
    notes: [
      "קורס חובה במסלול ביומכניקה (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22994",
    name: "תכן ותפעול שרשרת אספקה",
    credits: 3,
    type: "elective",
    semester: 7,
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["11005", "22800"])],
    notes: [
      "קורס חובה במסלול תעשייה מתקדמת בעידן המידע (אינו ניתן להחלפה).",
    ],
  },
  {
    id: "22930",
    name: "פרויקט מסכם שלב ב'",
    credits: 4,
    type: "required",
    required: true,
    semester: 8,
    prerequisites: [p(["22921"])],
  },
  {
    id: "51605",
    name: "מבוא לכלכלה למהנדסים",
    credits: 0,
    type: "elective",
    notes: [
      "קורס חוץ-מחלקתי (ככל הנראה מתחום ניהול/תעשייה); אינו מתועד בטבלאות הנדסת מכונות במקור זה - נ\"ז אינם ידועים ממקור זה.",
      "משמש כקורס קדם לקורס ההעשרה 251508 בלבד.",
    ],
  },
  {
    id: "22853",
    name: "יישומים מעשיים באלמנטים סופיים",
    credits: 3.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22310", "22130"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22163",
    name: "אלמנטים סופיים",
    credits: 3,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22310", "22114", "22106"])],
    coRequisites: ["22130", "22620"],
    notes: [
      "המקור מציין קורס קדם \"22105 מבוא לתכנות\" שאינו מוגדר בטבלאות הסמסטרים; מפורש כאן כ-22106 מבוא לאלגוריתמיקה ותכנות (קורס החובה התואם, שכל הסטודנטים לומדים ממילא).",
      "אי-עקביות במקור: קורסי הצמוד 22130 ו-22620 מופיעים תחת קורס זה בשלוש מתוך ארבע טבלאות המסלולים (מכטרוניקה, ביומכניקה, תעשייה מתקדמת) אך לא בטבלת מסלול תכן וייצור. נעשה שימוש בגרסת הרוב (עם קורסי צמוד).",
      "מופיע כבחירה במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22255",
    name: "עיבוד פלסטי של מתכות",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22310", "22210"])],
  },
  {
    id: "22254",
    name: "מערכות ייצור ממוחשבות",
    credits: 3,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22210", "22810"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "31854",
    name: "מערכות הנעה חשמליות מכ'",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["31375"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, מכטרוניקה.",
      "בטבלת מסלול מכטרוניקה מופיע קורס קדם נוסף \"22105 מבוא לתכנות\" (מפורש כ-22106); לא נכלל כאן כברירת מחדל בשל אי-עקביות בין הטבלאות.",
    ],
  },
  {
    id: "22779",
    name: "תכן מערכות הידראוליות",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22610"])],
  },
  {
    id: "31852",
    name: "הנע חשמלי ME",
    credits: 3.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["31375"])],
  },
  {
    id: "22844",
    name: "מבוא לתכן מכניזמים",
    credits: 3,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22511"])],
    notes: [
      "מופיע כבחירה/העשרה במסלולים: תכן וייצור, ביומכניקה.",
    ],
  },
  {
    id: "22253",
    name: "אוטומציה תעשייתית",
    credits: 3,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22810"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22776",
    name: "מערכות שינוע והובלה",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22720"])],
  },
  {
    id: "22772",
    name: "רובוטיקה",
    credits: 3.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22810", "22511"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22784",
    name: "מידול ויצור מיקרו התקנים מכניים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["11212", "22310", "22400"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22777",
    name: "תכן ואנליזת מבנים מחומרים מרוכבים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22310"])],
  },
  {
    id: "22486",
    name: "ביומכניקה שיקומית",
    credits: 4,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22745"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה.",
      "נ\"ז 4.0 לפי רוב המופעים (מכטרוניקה, ביומכניקה); בטבלת מסלול תכן וייצור מופיע ברישום נ\"ז 3.0 (חוסר עקביות במקור).",
    ],
  },
  {
    id: "22449",
    name: "מבוא לחומרים פלסטיים ועיבודם",
    credits: 3,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22600", "22210"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, ביומכניקה.",
    ],
  },
  {
    id: "22774",
    name: "תכן מבנים מתקפלים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22511"])],
    notes: [
      "מופיע כבחירה במסלולים: תכן וייצור, מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
      "בטבלת מסלול תעשייה מתקדמת בעידן המידע מופיע קורס קדם נוסף 22861 מבוא למערכות מכטרוניות; גרסת הרוב (תכן וייצור, מכטרוניקה) אינה כוללת אותו.",
    ],
  },
  {
    id: "22848",
    name: "מבוא לתהליכי הדפסה תלת ממדית",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22400", "22210", "22114"])],
    notes: [
      "מופיע כבחירה/העשרה במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22775",
    name: "תכן מוצר מחומרים פלסטיים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22715"])],
    notes: [
      "מופיע כבחירה/העשרה במסלולים: תכן וייצור, ביומכניקה.",
    ],
  },
  {
    id: "31853",
    name: "הנע חשמלי מכ",
    credits: 3.5,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["31375"])],
  },
  {
    id: "22845",
    name: "למידת מכונה אבולוציונית",
    credits: 3,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22800", "11133", "22106"])],
    coRequisites: ["22810"],
    notes: [
      "המקור מציין קורס קדם \"22105 מבוא לתכנות\" שאינו מוגדר בטבלאות הסמסטרים; מפורש כאן כ-22106 מבוא לאלגוריתמיקה ותכנות (קורס החובה התואם, שכל הסטודנטים לומדים ממילא).",
      "מופיע כבחירה במסלולים: מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22874",
    name: "רובוטיקה תעופתית",
    credits: 4,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["31375", "22511"])],
  },
  {
    id: "22748",
    name: "מבוא למכניקת הטיס",
    credits: 2.5,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22610"])],
  },
  {
    id: "22837",
    name: "Designing Solutions to Surgical Problems",
    credits: 4,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22745"])],
    notes: [
      "מופיע כבחירה במסלולים: מכטרוניקה, ביומכניקה.",
    ],
  },
  {
    id: "22851",
    name: "עקרונות טיסת חלל",
    credits: 3.5,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22511"])],
  },
  {
    id: "22769",
    name: "מידול סימולציה וזיהוי מערכות",
    credits: 2.5,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22130", "22800"])],
    coRequisites: ["22810"],
    notes: [
      "מופיע כבחירה במסלולים: מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22838",
    name: "ניתוח נומרי של בעיות הנדסיות מורכבות",
    credits: 3.5,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22130"])],
    notes: [
      "מופיע כבחירה במסלולים: מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22995",
    name: "ראייה ממוחשבת למהנדסי מכונות",
    credits: 3,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22106", "22512"])],
    notes: [
      "מופיע כבחירה במסלולים: מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22997",
    name: "מבוא לאינטרנט של הדברים בהנדסה (IOT)",
    credits: 2.5,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["11061"])],
    notes: [
      "מופיע כבחירה במסלולים: מכטרוניקה, ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "21461",
    name: "מבוא לזיווד אלקטרוני ומיקרו אלקטרוני",
    credits: 3,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22310", "22400", "22520"])],
    coRequisites: ["22620"],
    notes: [
      "מופיע כבחירה/העשרה במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22483",
    name: "ביומכניקה של שתלים",
    credits: 3,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["22310", "22512", "22855"])],
    notes: [
      "המקור מציין קורס קדם \"22510\"; מפורש כאן כ-22512 דינמיקה של גוף קשיח (טעות דפוס במקור, לפי הערת מסמך המקור).",
    ],
  },
  {
    id: "41591",
    name: "יישומים של ביוחומרים",
    credits: 2,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["22810"])],
    notes: [
      "טקסט הקדם במקור פגום/מטושטש (\"NCUT KCERV22810\"); מפורש כאן כהפניה לקורס 22810 מבוא לבקרה, ללא ודאות מלאה.",
    ],
  },
  {
    id: "22450",
    name: "מבנה ותכונות של חומרים פלסטיים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["41077"])],
    notes: [
      "משמש כקורס קדם למספר קורסי העשרה בנושא חומרים פלסטיים במסלולים שונים.",
    ],
  },
  {
    id: "22968",
    name: "טכנולוגיות מתקדמות בעידן תעשייה 4.0",
    credits: 2.5,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["22210"])],
    notes: [
      "מופיע כבחירה במסלולים: ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22770",
    name: "התקנים וחומרים להשתלה בגוף האדם",
    credits: 3,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["22400"])],
  },
  {
    id: "22834",
    name: "מבוא להדפסת תלת מימד",
    credits: 2.5,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["11061", "22114"])],
    notes: [
      "מופיע כבחירה/העשרה בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "251504",
    name: "הנדסת יזמות - גישת ההזנק הרזה",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22705"])],
    notes: [
      "קורס יזמות; ניתן לצבור עד מכסה כוללת של 4 נ\"ז מקורסי היזמות. מופיע בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "251506",
    name: "מבוא ליזמות וקניין רוחני",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22705"])],
    notes: [
      "קורס יזמות; ניתן לצבור עד מכסה כוללת של 4 נ\"ז מקורסי היזמות. מופיע בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "251507",
    name: "מבוא ליזמות",
    credits: 1,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    notes: [
      "קורס יזמות; ניתן לצבור עד מכסה כוללת של 4 נ\"ז מקורסי היזמות. מופיע בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "251508",
    name: "תכנון עסקי למיזמי הזנק",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["51605"])],
    notes: [
      "קורס יזמות; ניתן לצבור עד מכסה כוללת של 4 נ\"ז מקורסי היזמות. מופיע בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "251512",
    name: "מבוא לניהול חדשנות ויזמות פנים ארגונית",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22800"])],
    notes: [
      "קורס יזמות; ניתן לצבור עד מכסה כוללת של 4 נ\"ז מקורסי היזמות. מופיע בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "251514",
    name: "מבוא לפיתוח אב טיפוס",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22800"])],
    notes: [
      "קורס יזמות; ניתן לצבור עד מכסה כוללת של 4 נ\"ז מקורסי היזמות. מופיע בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "251965",
    name: "מהנדסים למען הגיל השלישי",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22735"])],
    notes: [
      "מופיע במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה (אינו מופיע ברשימת תעשייה מתקדמת בעידן המידע).",
    ],
  },
  {
    id: "251966",
    name: "מוצר וחשיבה עיצובית",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22735"])],
    notes: [
      "מופיע בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "251520",
    name: "להשאיר את החותם האישי",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22735"])],
    notes: [
      "מופיע במסלולים: תכן וייצור, מכטרוניקה.",
    ],
  },
  {
    id: "251102",
    name: "היבטים רב-תחומיים בחדשנות טכנולוגית",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22715"])],
    notes: [
      "מופיע בכל ארבעת המסלולים.",
    ],
  },
  {
    id: "22868",
    name: "מקורות אנרגיה",
    credits: 3.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["41077", "22600"])],
    coRequisites: ["22610"],
    notes: [
      "מופיע כהעשרה במסלולים: תכן וייצור, מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22453",
    name: "תהליכי עיבוד של חומרים פלסטיים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22450", "22610"])],
    notes: [
      "מופיע כהעשרה במסלולים: תכן וייצור, ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22458",
    name: "כשל ואפיון של חומרים פלסטיים",
    credits: 3.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22450"])],
  },
  {
    id: "22459",
    name: "מבוא לתכן תבניות הזרקה",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22450"])],
    notes: [
      "מופיע כהעשרה במסלולים: תכן וייצור, ביומכניקה.",
    ],
  },
  {
    id: "22484",
    name: "נושאים מתקדמים בחומרים פלסטיים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22453"])],
    notes: [
      "מופיע כהעשרה במסלולים: תכן וייצור, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22747",
    name: "אמינות מערכות מכניות",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22720"])],
    notes: [
      "מופיע כהעשרה במסלולים: תכן וייצור, תעשייה מתקדמת בעידן המידע.",
      "בטבלת מסלול תעשייה מתקדמת בעידן המידע מופיע קורס קדם נוסף 51700 הסתברות וסטטיסטיקה מכ.",
    ],
  },
  {
    id: "22778",
    name: "יסודות העיצוב התעשייתי למהנדסים",
    credits: 3,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["51700"])],
    notes: [
      "מופיע כהעשרה במסלולים: תכן וייצור, תעשייה מתקדמת בעידן המידע.",
      "בטבלת מסלול תעשייה מתקדמת בעידן המידע אין קורס קדם רשום (חוסר עקביות במקור); נעשה שימוש בגרסת מסלול תכן וייצור.",
    ],
  },
  {
    id: "22839",
    name: "תכונות ויישומים של חומרים קרמיים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    prerequisites: [p(["22400"])],
    notes: [
      "מופיע כהעשרה במסלולים: תכן וייצור, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22971",
    name: "פרויקט מיוחד בהנדסת מכונות א1",
    credits: 1,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    notes: [
      "דורש אישור יועץ אקדמי; מופיע במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה.",
    ],
  },
  {
    id: "22973",
    name: "פרויקט מיוחד בהנדסת מכונות א2",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    notes: [
      "דורש אישור יועץ אקדמי; מופיע במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה.",
    ],
  },
  {
    id: "22975",
    name: "פרויקט מיוחד בהנדסת מכונות ב1",
    credits: 1,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    notes: [
      "דורש אישור יועץ אקדמי; מופיע במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה.",
    ],
  },
  {
    id: "22977",
    name: "פרויקט מיוחד בהנדסת מכונות ב2",
    credits: 2,
    type: "elective",
    clusterId: "track-design-mfg",
    requirementGroup: "track-design-mfg",
    notes: [
      "דורש אישור יועץ אקדמי; מופיע במסלולים: תכן וייצור, מכטרוניקה, ביומכניקה.",
    ],
  },
  {
    id: "22840",
    name: "הנעה רקטית",
    credits: 2.5,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22600"])],
    coRequisites: ["22610"],
    notes: [
      "מופיע כהעשרה במסלולים: מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22843",
    name: "זרימה דחיסה ומבוא למנועי סילון",
    credits: 3,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["22610"])],
    notes: [
      "מופיע כהעשרה במסלולים: מכטרוניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "51203",
    name: "הבטחת איכות למהנדסים מכ",
    credits: 2,
    type: "elective",
    clusterId: "track-mechatronics",
    requirementGroup: "track-mechatronics",
    prerequisites: [p(["51700"])],
    notes: [
      "מופיע כהעשרה במסלולים: מכטרוניקה, ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "22456",
    name: "טכנולוגיה של תהליך הזרקה",
    credits: 2.5,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["22600"])],
    notes: [
      "מופיע כהעשרה במסלולים: ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "51525",
    name: "כריית נתונים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
    prerequisites: [p(["22106", "51700"])],
    notes: [
      "מופיע כהעשרה/בחירה במסלולים: ביומכניקה, תעשייה מתקדמת בעידן המידע.",
    ],
  },
  {
    id: "51301",
    name: "יסודות השיווק",
    credits: 2,
    type: "elective",
    clusterId: "track-biomechanics",
    requirementGroup: "track-biomechanics",
  },
  {
    id: "22991",
    name: "מעבר מתכנון לייצור",
    credits: 2.5,
    type: "elective",
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
  },
  {
    id: "22996",
    name: "אבחון מפעלים והטמעת טכנולוגיות",
    credits: 2.5,
    type: "elective",
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["11061"])],
  },
  {
    id: "22455",
    name: "שיטות חישוב והדמיה מולקולרית של פולימרים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["22450", "22600", "11212"])],
    notes: [
      "המקור מציין קורס קדם \"11213 פיזיקה 2מכ\"; שם הקורס תואם ל-11212 (פיזיקה 2מכ), בעוד 11213 מוגדר במקור כ\"פיזיקה 3מכ\" - טעות מספור במקור, תוקנה כאן ל-11212.",
    ],
  },
  {
    id: "22846",
    name: "פתרונות אנליטיים בזרימה",
    credits: 2.5,
    type: "elective",
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["22610"])],
  },
  {
    id: "22849",
    name: "תהליכי מעבר ויישום בחומרים מתקדמים",
    credits: 2.5,
    type: "elective",
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["22400"])],
  },
  {
    id: "22867",
    name: "הנדסה בת קיימא בסביבת הבית",
    credits: 2,
    type: "elective",
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["22620"])],
  },
  {
    id: "51117",
    name: "הנדסת אנוש מכ",
    credits: 2,
    type: "elective",
    clusterId: "track-industry40",
    requirementGroup: "track-industry40",
    prerequisites: [p(["51700"])],
  },
  ...generalStudiesCourses,
  ...sportCourses,
];

export const degreePlan: DegreePlan = {
  id: "mechanical-engineering-bsc",
  title: "מפת תואר הנדסת מכונות",
  subtitle: "המכללה האקדמית להנדסה בראודה - שנתון תשפ\"ד 2023-2024",
  catalogYear: 'תשפ"ד (2023-2024)',
  status: "archived",
  source: {
    fileName: "ידיעונים, שנתונים ולוח שנה אקדמית - בראודה.pdf",
    pages: "105-121",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 160,
    fixedDegreeCredits: 124.5,
    electiveCreditsNeeded: 28.5,
    generalCredits: 6,
    sportCredits: 1,
    englishRequiredIds: ["11061"],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [
  {
    code: "track-design-mfg",
    name: "צבירת נ\"ז מסלול תכן וייצור",
    kind: "credits",
    requiredCredits: 28.5,
    courseIds: ["22720", "22251", "22267", "22268", "22853", "22163", "22255", "22254", "31854", "22779", "31852", "22844", "22253", "22776", "22772", "22784", "22777", "22486", "22449", "22774", "22848", "22775", "21461", "22834", "251504", "251506", "251507", "251508", "251512", "251514", "251965", "251966", "251520", "251102", "22868", "22453", "22458", "22459", "22484", "22747", "22778", "22839", "22971", "22973", "22975", "22977"],
  },
  {
    code: "track-mechatronics",
    name: "צבירת נ\"ז מסלול מכטרוניקה",
    kind: "credits",
    requiredCredits: 28.5,
    courseIds: ["22861", "22862", "22864", "22863", "22853", "22163", "31854", "22772", "22784", "22486", "22774", "22848", "31853", "22845", "22874", "22748", "22837", "22851", "22769", "22838", "22995", "22997", "21461", "22834", "251504", "251506", "251507", "251508", "251512", "251514", "251965", "251966", "251520", "251102", "22868", "22971", "22973", "22975", "22977", "22840", "22843", "51203"],
  },
  {
    code: "track-biomechanics",
    name: "צבירת נ\"ז מסלול ביומכניקה",
    kind: "credits",
    requiredCredits: 28.5,
    courseIds: ["22467", "22472", "22855", "22471", "22853", "22163", "22844", "22784", "22486", "22449", "22848", "22775", "22837", "22997", "21461", "22483", "41591", "22450", "22968", "22770", "22834", "251504", "251506", "251507", "251508", "251512", "251514", "251965", "251966", "251102", "22453", "22459", "22971", "22973", "22975", "22977", "51203", "22456", "51525", "51301"],
  },
  {
    code: "track-industry40",
    name: "צבירת נ\"ז מסלול תעשייה מתקדמת בעידן המידע",
    kind: "credits",
    requiredCredits: 28.5,
    courseIds: ["22993", "22992", "22994", "22853", "22163", "22254", "22253", "22772", "22784", "22774", "22848", "22845", "22769", "22838", "22995", "22997", "21461", "22968", "22834", "251504", "251506", "251507", "251508", "251512", "251514", "251966", "251102", "22868", "22453", "22484", "22747", "22778", "22839", "22840", "22843", "51203", "22456", "51525", "22991", "22996", "22455", "22846", "22849", "22867", "51117"],
  },
  {
    code: "general-studies",
    name: "לימודים כלליים",
    kind: "credits",
    requiredCredits: 6,
  },
  {
    code: "sport-elective",
    name: "ספורט",
    kind: "credits",
    requiredCredits: 1,
  },
  ],
  clusters,
  courses,
  rules: [
    {
      id: "english-basic-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית בסיסי וגם פטור/סיווג מאנגלית בסיסית.",
      payload: { courseIds: ["11063", "ENG_BASIC_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים א וגם פטור/סיווג מאנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-a-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים א חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_A_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-placement-mutual-exclusion",
      type: "mutual_exclusion",
      message: "לא ניתן לסמן גם אנגלית מתקדמים ב וגם פטור/סיווג מאנגלית מתקדמים ב.",
      payload: { courseIds: ["11061", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-basic",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית בסיסי.",
      payload: { courseIds: ["11063", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-advanced-b-blocks-advanced-a",
      type: "mutual_exclusion",
      message: "פטור/סיווג מאנגלית מתקדמים ב חוסם גם את אנגלית מתקדמים א.",
      payload: { courseIds: ["11064", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
    {
      id: "english-exemptions-single-choice",
      type: "mutual_exclusion",
      message: "ניתן לבחור פטור/סיווג אנגלית אחד בלבד: בסיסי, מתקדמים א או מתקדמים ב.",
      payload: { courseIds: ["ENG_BASIC_OK", "ENG_ADV_A_OK", "ENG_ADV_B_OK"], maxSelected: 1 },
      enabled: true,
    },
  ],
  notes: [
    "לצורך זכאות לתואר יש לצבור לפחות 160 נ\"ז: 123.5 נ\"ז לימודי חובה (כולל 1 נ\"ז מיומנויות יסוד הנדסיות), 28.5 נ\"ז לימודי התמחות, 6 נ\"ז לימודים כלליים ו-1 נ\"ז ספורט.",
    "שדה fixedDegreeCredits (124.5) במחשבון זה משקף את 123.5 הנ\"ז לימודי חובה יחד עם 1 הנ\"ז של קורס מיומנויות יסוד הנדסיות; שדה electiveCreditsNeeded (28.5) משקף את לימודי ההתמחות.",
    "המקור מציין גם שורה נפרדת \"8.5 נ\"ז לימודי בחירה מחלקתיים (חובה בהתמחות + בחירה בהתמחות + קורסים מתקדמים)\"; סכום חמשת הסעיפים המקוריים (123.5+28.5+8.5+6+1+1) עולה על 160, כך שהשורה הזו נראית כפירוט חופף/מקונן של 28.5 לימודי ההתמחות ולא כתוספת עצמאית - נעשה שימוש בפירוש שמסתכם ל-160 נ\"ז בדיוק.",
    "יש ללמוד ולסיים את כל קורסי היסוד (הרשומים בטבלת סמסטרים 1-4 ובנספח קורסי היסוד בשנתון) בטרם ניתן להתחיל בקורסי ההתמחות של המסלול הנבחר.",
    "בכל התמחות (מסלול) ישנם קורסי חובה שאינם ניתנים לשינוי/החלפה, בנוסף לרשימות קורסי בחירה והעשרה בהתמחות מהם בוחר הסטודנט קורסים עד לצבירת 28.5 נ\"ז. ההתמחות אינה נרשמת על גבי תעודת התואר אלא מופיעה בגיליון הציונים בלבד.",
    "מקורסי היזמות (251504, 251506, 251507, 251508, 251512, 251514) ניתן לצבור לכיוון התואר עד מכסה של 4 נ\"ז בלבד.",
    "יש לסיים את לימודי האנגלית עד תום השנה השנייה ללימודים.",
    "קורס 22163 (אלמנטים סופיים) מופיע במקור עם קורסי צמוד (22130, 22620) בשלוש מתוך ארבע טבלאות מסלולים ובלי קורסי צמוד בטבלה הרביעית (תכן וייצור) - חוסר עקביות מתועד במקור; המחשבון מציג את גרסת הרוב (עם קורסי צמוד).",
    "מספר קורסי בחירה/העשרה מופיעים ברשימות של יותר ממסלול אחד; שדה clusterId על כל קורס משקף מסלול ראשי אחד לצורך תצוגה, בעוד ש-requirementGroups כולל את מלוא רשימת הקורסים המוכרים לכל מסלול (כולל קורסים משותפים) לצורך חישוב נ\"ז.",
    "המסמך הרשמי (שנתון תשפ\"ד) עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
