import type { Course, DegreePlan } from "@/types/degree";

const courses: Course[] = [
  {
    id: "63010",
    name: "מתודולוגיה לפיתוח תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "63011",
    name: "מערכות לומדות",
    credits: 3,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "63012",
    name: "ניהול פרויקטי תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "63019",
    name: "הבטחת נתונים ורשתות",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "63014",
    name: "הבטחת איכות תוכנה ושיפור תהליכים",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "63015",
    name: "אנליזה נומרית מתקדמת",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "FINAL_PROJECT_1",
    name: "עבודת גמר - חלק א'",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    notes: [
      "עבודת הגמר מתפרסת על פני שני סמסטרים (חלק א' וחלק ב'); לא צוין מספר קורס רשמי במקור.",
    ],
  },
  {
    id: "63103",
    name: "תורת הקירובים הנומריים",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
  },
  {
    id: "63110",
    name: "עקרונות תכנות באמצעות טכנולוגיות ענן",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
  },
  {
    id: "FINAL_PROJECT_2",
    name: "עבודת גמר - חלק ב'",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
    notes: [
      "עבודת הגמר מתפרסת על פני שני סמסטרים (חלק א' וחלק ב'); לא צוין מספר קורס רשמי במקור.",
    ],
  },
  {
    id: "63001",
    name: "סמינר בהנדסת דרישות",
    credits: 3,
    type: "elective",
  },
  {
    id: "63105",
    name: "נושאים מתקדמים בהנדסת תוכנה",
    credits: 3,
    type: "elective",
  },
  {
    id: "63102",
    name: "נושאים מתקדמים במערכות ניהול מסדי נתונים",
    credits: 3,
    type: "elective",
    notes: [
      "מספר קורס 63102 מופיע במסמך המקור פעמיים עבור שני שמות קורס שונים (ככל הנראה טעות/כפילות במקור); תועד כפי שהופיע.",
    ],
  },
  {
    id: "63102-2",
    name: "סמינר בנושאים מתקדמים במערכות ניהול מסדי נתונים",
    credits: 3,
    type: "elective",
    notes: [
      "מספר קורס 63102 מופיע במסמך המקור פעמיים עבור שני שמות קורס שונים (ככל הנראה טעות/כפילות במקור); מזהה זה הותאם כדי למנוע התנגשות מזהים.",
    ],
  },
  {
    id: "63104",
    name: "אלגוריתמים מתקדמים בביולוגיה חישובית",
    credits: 3,
    type: "elective",
  },
  {
    id: "63107",
    name: "שימושיות ומנשקי משתמש",
    credits: 3,
    type: "elective",
    notes: [
      "סטודנטים שלמדו קורס זה (או שקול לו) במסגרת לימודי התואר הראשון אינם רשאים ללומדו בשנית.",
    ],
  },
  {
    id: "63108",
    name: "השתלמות יחידנית בהנדסת תוכנה",
    credits: 3,
    type: "elective",
  },
];

export const degreePlan: DegreePlan = {
  id: "msc-software-engineering",
  title: "תואר שני בהנדסת תוכנה",
  subtitle: "המכללה האקדמית להנדסה בראודה - תואר מוסמך M.Sc. בהנדסת תוכנה",
  catalogYear: 'תשפ"ד (2023-2024)',
  status: "archived",
  source: {
    fileName: "שנתון תשפ\"ד 2024-2023 - בראודה.pdf",
    pages: "212-215",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 39,
    fixedDegreeCredits: 30,
    electiveCreditsNeeded: 9,
    generalCredits: 0,
    sportCredits: 0,
    englishRequiredIds: [],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [],
  clusters: [],
  courses,
  rules: [],
  notes: [
    "לצורך זכאות לתואר יש לצבור 39 נ\"ז לפי התוכנית המומלצת, כולל עבודת גמר בת שני חלקים (חלק א' וחלק ב').",
    "תוכנית הלימודים המומלצת נמשכת שנתיים; ניתן לפרוס את הלימודים גם לאורך שלוש שנים, כדי להקל על מי שעובד במשרה מלאה או על מי שחייב בקורסי השלמה.",
    "מספר קורסי הבחירה המוצעים עשוי להשתנות משנה לשנה, בהתאם למספר הסטודנטים הלומדים באותה שנה.",
    "סטודנטים שלמדו את הקורס 63107 (שימושיות ומנשקי משתמש) או שקול לו במסגרת לימודי התואר הראשון אינם רשאים ללומדו בשנית.",
    "מסמך המקור אינו כולל עמודת קורסי קדם/צמודים עבור תוכנית זו; לא אותרו זוגות קורסים צמודים (0 קורסים צמודים).",
    "המסמך הרשמי עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
