import type { Course, DegreePlan } from "@/types/degree";

const courses: Course[] = [
  {
    id: "23150",
    name: "שיטות אנליטיות בהנדסת מכונות",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "22365",
    name: "נושאים נבחרים בהדפסת תלת ממד",
    credits: 3,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "23100",
    name: "תורת הדפורמציה הפלסטית",
    credits: 3,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "23120",
    name: "נושאים מתקדמים במדע ובטכנולוגיית הפולימרים",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "23151",
    name: "שיטות אנליטיות בהנדסת מכונות 2",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "23252",
    name: "נושאים בתעשייה מתקדמת",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "23727",
    name: "פרויקט מסכם 1",
    credits: 2,
    type: "required",
    required: true,
    semester: 3,
    notes: [
      "חלק א' של הפרויקט המסכם השנתי הנדרש מכלל הסטודנטים בשנה ב' לתואר; ממשיך בסמסטר הבא בקורס 23273.",
    ],
  },
  {
    id: "22366",
    name: "תיאוריות ושיטות תכן",
    credits: 3.5,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "23110",
    name: "חומרים קרמיים",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "23166",
    name: "תורת האלסטיות",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "23273",
    name: "פרויקט מסכם 2",
    credits: 2,
    type: "required",
    required: true,
    semester: 4,
    notes: ["חלק ב' של הפרויקט המסכם השנתי; המשך ישיר של קורס 23727."],
  },
  {
    id: "23164",
    name: "מכניקת השבר",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
  },
  {
    id: "23163",
    name: "נושאים מתקדמים בתהליכי עיבוד שבבי",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
  },
];

export const degreePlan: DegreePlan = {
  id: "msc-mechanical-engineering",
  title: "תואר שני בהנדסת מכונות",
  subtitle: "M.Sc. תואר שני נלמד - המכללה האקדמית להנדסה בראודה, כרמיאל",
  source: {
    fileName: "שנתון תשפ\"ד 2024-2023 - בראודה.pdf",
    pages: "203-206",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 38,
    fixedDegreeCredits: 38,
    electiveCreditsNeeded: 0,
    generalCredits: 0,
    sportCredits: 0,
    englishRequiredIds: [],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [],
  clusters: [],
  courses,
  rules: [],
  notes: [
    "לתום הלימודים יוענק תואר שני נלמד (M.Sc.) בהנדסת מכונות; לשם קבלתו יש לצבור 38 נ\"ז: 34 נ\"ז מקורסים פרונטליים (שני קורסי מתמטיקה ותשעה קורסים מחלקתיים) ו-4 נ\"ז מפרויקט מסכם שנתי בשנה ב' (מחולק לשני קורסים - 23727 ו-23273).",
    "סכום נקודות הזכות בטבלאות רצף הלימוד המומלץ לפי סמסטרים הוא 38.5 נ\"ז - הפרש של 0.5 נ\"ז מהסך הרשמי המצוין בסעיף קבלת התואר (38 נ\"ז); ההפרש מדווח כפי שמופיע במסמך המקור ולא תוקן.",
    "משך הלימודים הנומינלי הוא שנתיים (ארבעה סמסטרים, כשלושה קורסים בכל סמסטר), אך ניתן לפרוס את הלימודים על פני תקופה ארוכה יותר; התוכנית מותאמת גם למהנדסים העובדים בתעשייה.",
    "התוכנית מיועדת לבעלי תואר ראשון בהנדסת מכונות ולמהנדסים בתחומים בעלי זיקה למכונות (כגון הנדסה חקלאית, כימית, אווירונאוטית, חומרים ועוד), וכן לבעלי תואר ראשון במדעים מדויקים העומדים בקריטריונים.",
    "לא נמצאה בפרק זה טבלת קורסי קדם לתואר ראשון (בשונה מתוכנית התואר השני בביוטכנולוגיה); תנאי הקבלה מתוארים בפרוזה בלבד.",
    "טבלאות הקורסים בתוכנית זו (עמ' 205-206) אינן כוללות עמודת קורסי קדם/קורסים צמודים כלל, ולא אותרו קורסים או שמות קורסים עם קו תחתי (סימון קורס צמוד) בפרק זה - לפיכך לא נקבעו יחסי קדם/צמוד בין קורסי התוכנית.",
    "לא אותרו הערות שוליים (כוכביות) המצורפות לטבלאות הקורסים בפרק זה.",
    "המסמך הרשמי עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
