import type { Course, DegreePlan, ElectiveCluster } from "@/types/degree";

const clusters: ElectiveCluster[] = [
  {
    id: "elective-management",
    name: "אשכול בחירה - תחום ניהול",
    minCourses: 1,
    note: "יש לבחור קורס בחירה אחד מתחום הניהול.",
  },
  {
    id: "elective-engineering",
    name: "אשכול בחירה - תחום הנדסה",
    minCourses: 1,
    note: "יש לבחור קורס בחירה אחד מתחום ההנדסה.",
  },
  {
    id: "leveling-courses",
    name: "קורסי השלמה (תלוי קבלה)",
    minCourses: 0,
    note: "קורסי השלמה ברמת תואר ראשון הנדרשים רק ממועמדים שחסרים קורסים אלה בגיליון הציונים שלהם, כתנאי קדם להשתתפות בקורסי החובה של התוכנית; אינם נספרים בסך 41 הנ\"ז של התואר.",
  },
];

const courses: Course[] = [
  // --- Mandatory recommended-sequence courses (12) ---
  {
    id: "53323",
    name: "תכנון פרויקטים",
    credits: 3,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "53311",
    name: "מבוא להנדסת מערכות",
    credits: 2,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "53312",
    name: "הנדסת דרישות",
    credits: 2,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "53314",
    name: "כלכלה הנדסית",
    credits: 2,
    type: "required",
    required: true,
    semester: 1,
  },
  {
    id: "53321",
    name: "הנדסת מערכות מבוססת מודלים",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "53322",
    name: "אינטגרציה של מערכות",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "53313",
    name: "תכן הנדסי לפיתוח מערכות",
    credits: 3,
    type: "required",
    required: true,
    semester: 2,
  },
  {
    id: "53324",
    name: "סמינר מחלקתי",
    credits: 0,
    type: "required",
    required: true,
    semester: 2,
    notes: ["קורס ללא נקודות זכות (0.0 נ\"ז) במסגרת הרצף המומלץ."],
  },
  {
    id: "53331",
    name: "הנדסת מערכות עתירות תוכנה",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "53428",
    name: "מבוא ליישומי RAMST",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "53422",
    name: "מידול וסימולציה של מערכות",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
  },
  {
    id: "53342",
    name: "סמינר בהנדסת מערכות",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
  },
  // --- Yearly systems-engineering project (2 stages, 6 נ"ז) ---
  {
    id: "53333",
    name: "פרויקט 1 בהנדסת מערכות",
    credits: 3,
    type: "required",
    required: true,
    semester: 3,
    notes: ["פרויקט שנתי בהנדסת מערכות, נלמד בשני שלבים (53333 בסמסטר ג', 53334 בסמסטר ד')."],
  },
  {
    id: "53334",
    name: "פרויקט 2 בהנדסת מערכות",
    credits: 3,
    type: "required",
    required: true,
    semester: 4,
    notes: ["המשך פרויקט 1 בהנדסת מערכות (53333)."],
  },
  // --- Elective courses: management track (4) ---
  {
    id: "53526",
    name: "קבלת החלטות ביישומים טכנולוגיים",
    credits: 2,
    type: "elective",
    clusterId: "elective-management",
  },
  {
    id: "53413",
    name: "ניהול ידע",
    credits: 2,
    type: "elective",
    clusterId: "elective-management",
  },
  {
    id: "53417",
    name: "מנהיגות בסביבה ארגונית עתירת טכנולוגיה",
    credits: 2,
    type: "elective",
    clusterId: "elective-management",
  },
  {
    id: "53116",
    name: "נושאים מתקדמים בניהול השיווק",
    credits: 2,
    type: "elective",
    clusterId: "elective-management",
  },
  // --- Elective courses: engineering track (5) ---
  {
    id: "53427",
    name: "יישומי הנדסת אנוש במערכות טכנולוגיות",
    credits: 3,
    type: "elective",
    clusterId: "elective-engineering",
  },
  {
    id: "53425",
    name: "מערכות אמל\"ח",
    credits: 3,
    type: "elective",
    clusterId: "elective-engineering",
  },
  {
    id: "53231",
    name: "חקר סיבתיות בביצועים",
    credits: 3,
    type: "elective",
    clusterId: "elective-engineering",
  },
  {
    id: "53243",
    name: "כריית נתונים",
    credits: 3,
    type: "elective",
    clusterId: "elective-engineering",
  },
  {
    id: "53423",
    name: "ניהול והערכת סיכונים בפרויקטי פיתוח הנדסיים",
    credits: 3,
    type: "elective",
    clusterId: "elective-engineering",
  },
  // --- Leveling (admission-dependent) courses (4) - not counted in the 41 נ"ז ---
  {
    id: "LVL_PROB",
    name: "הסתברות ויסודות סטטיסטיקה",
    credits: 2.5,
    type: "required",
    required: false,
    clusterId: "leveling-courses",
    notes: [
      "קורס השלמה ברמת תואר ראשון; נדרש רק ממועמדים שבגיליון ציוניהם לא כלול קורס זה, כתנאי קדם להשתתפות בקורסי החובה של התוכנית.",
      "אינו נספר בסך 41 הנ\"ז של התוכנית.",
    ],
  },
  {
    id: "LVL_ECON",
    name: "מבוא לכלכלה למהנדסים",
    credits: 2,
    type: "required",
    required: false,
    clusterId: "leveling-courses",
    notes: [
      "קורס השלמה ברמת תואר ראשון; נדרש רק ממועמדים שבגיליון ציוניהם לא כלול קורס זה, כתנאי קדם להשתתפות בקורסי החובה של התוכנית.",
      "אינו נספר בסך 41 הנ\"ז של התוכנית.",
    ],
  },
  {
    id: "LVL_CONTROL",
    name: "מבוא לבקרה",
    credits: 3,
    type: "required",
    required: false,
    clusterId: "leveling-courses",
    notes: [
      "קורס השלמה ברמת תואר ראשון; נדרש רק ממועמדים שבגיליון ציוניהם לא כלול קורס זה, כתנאי קדם להשתתפות בקורסי החובה של התוכנית.",
      "אינו נספר בסך 41 הנ\"ז של התוכנית.",
    ],
  },
  {
    id: "LVL_QA",
    name: "הבטחת איכות",
    credits: 2,
    type: "required",
    required: false,
    clusterId: "leveling-courses",
    notes: [
      "קורס השלמה ברמת תואר ראשון; נדרש רק ממועמדים שבגיליון ציוניהם לא כלול קורס זה, כתנאי קדם להשתתפות בקורסי החובה של התוכנית.",
      "אינו נספר בסך 41 הנ\"ז של התוכנית.",
    ],
  },
];

export const degreePlan: DegreePlan = {
  id: "msc-systems-engineering",
  title: "תואר שני בהנדסת מערכות",
  subtitle: "לימודי תואר שני (M.Sc.) - המכללה האקדמית להנדסה בראודה, כרמיאל",
  catalogYear: 'תשפ"ד (2023-2024)',
  status: "archived",
  source: {
    fileName: "שנתון תשפ\"ד 2024-2023 - בראודה.pdf",
    pages: "207-211",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 41,
    fixedDegreeCredits: 36,
    electiveCreditsNeeded: 5,
    generalCredits: 0,
    sportCredits: 0,
    englishRequiredIds: [],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "general", label: "כללי", sortOrder: 2 },
    { code: "sport", label: "ספורט", sortOrder: 3 },
    { code: "english", label: "אנגלית", sortOrder: 4 },
    { code: "placement", label: "סיווג/פטור", sortOrder: 5 },
    { code: "conversion", label: "המרה", sortOrder: 6 },
  ],
  requirementGroups: [],
  clusters,
  courses,
  rules: [],
  notes: [
    "לקבלת התואר על הסטודנט לצבור לפחות 41 נ\"ז: 30 נ\"ז ב-11 קורסי חובה בעלי נקודות זכות (מתוך 12 הקורסים ברצף המומלץ, כולל סמינר מחלקתי ללא נקודות זכות), 6 נ\"ז בפרויקט הנדסת מערכות השנתי (שלב א' ושלב ב') ו-5 נ\"ז בשני קורסי בחירה.",
    "יש לבחור קורס בחירה אחד מתחום הניהול וקורס בחירה אחד מתחום ההנדסה - סה\"כ שני קורסי בחירה, קורס אחד מכל תחום.",
    "תנאי סף לרישום: תואר ראשון מוכר על-ידי המל\"ג בהנדסת מכונות, הנדסת חשמל ואלקטרוניקה, הנדסה אופטית, הנדסת אלקטרואופטיקה, הנדסה כימית, הנדסת ביוטכנולוגיה, הנדסת מחשבים, הנדסת מערכות מידע או הנדסת תוכנה, בממוצע ציונים של 80 ומעלה, עם שלוש שנות ניסיון מקצועי רלוונטי מתום התואר הראשון ושני מכתבי המלצה.",
    "מועמדים שבגיליון ציוניהם לא כלול אחד מארבעת קורסי ההשלמה (הסתברות ויסודות סטטיסטיקה, מבוא לכלכלה למהנדסים, מבוא לבקרה, הבטחת איכות) יחויבו ללומדם ברמת התואר הראשון, כתנאי קדם להשתתפות בקורסי החובה של התוכנית; קורסי השלמה אלה אינם נספרים בסך 41 הנ\"ז. ייתכנו קורסי השלמה נוספים בהתאם לרקע הלימודי האישי של כל סטודנט.",
    "מסמך המקור אינו כולל עמודת קורסי קדם/קורסים צמודים בטבלאות התוכנית; לא זוהו קורסי קדם או זוגות קורסים צמודים בתוכנית זו.",
    "התוכנית נלמדת על פני שנתיים בממוצע (ניתן להאריך עד שלוש שנים); הלימודים מתקיימים פעמיים בשבוע (יום שישי ואחר-צהריים אחד באמצע השבוע).",
    "המסמך הרשמי עשוי להשתנות; המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
