import type { Course, DegreeRule, DegreePlan, ElectiveCluster, RequirementGroup } from "@/types/degree";

const clusters: ElectiveCluster[] = [
  {
    id: "track-shared-core",
    name: "מסלול 1: ליבת חובה משותפת לתעודות הוראה (הנדסי / מתמטיקה / משולב)",
    minCourses: 1,
    note: "אינו אשכול בחירה אלא ליבת חובה (24 נ\"ז) המשותפת לכל מסלולי תעודת ההוראה; ראו requirementGroups לחלופות (\"או\") בין זוגות קורסים.",
  },
  {
    id: "track-engineering",
    name: "מסלול 2: תעודת הוראה במקצוע הנדסי",
    minCourses: 1,
    note: "48 נ\"ז בסה\"כ (24 נ\"ז ליבה משותפת + 18 נ\"ז קורסי חובה נוספים/התנסות מעשית + 6 נ\"ז קורסי בחירה משני אשכולות הבחירה של המסלול).",
  },
  {
    id: "track-math",
    name: "מסלול 3: תעודת הוראה במתמטיקה",
    minCourses: 1,
    note: "48 נ\"ז בסה\"כ (24 נ\"ז ליבה משותפת + 18 נ\"ז קורסי חובה נוספים/התנסות מעשית + 6 נ\"ז קורסי בחירה: 2 מתוך 81557/81560/81564 ואחד מתוך 81551(או81291)/81671(או81290) - ראו rules).",
  },
  {
    id: "track-combined",
    name: "מסלול 4: תעודת הוראה משולבת (מקצוע הנדסי + מתמטיקה)",
    minCourses: 1,
    note: "71 נ\"ז בסה\"כ (24 נ\"ז ליבה משותפת + 45 נ\"ז קורסים נוספים הכוללים 18 נ\"ז התנסות מעשית + 2 נ\"ז קורס בחירה).",
  },
  {
    id: "track-math-extension",
    name: "מסלול 5: הרחבת הסמכה לתעודת הוראה במתמטיקה",
    minCourses: 1,
    note: "28 נ\"ז, מיועד לבעלי תעודת הוראה במקצוע הנדסי המבקשים להוסיף הסמכה במתמטיקה. מורכב מהקורסים: 81402, 81410, 81411, 81553, 81556, 81557, 81558, 81560, 81561 (כולם מוגדרים כבר תחת track-combined; מפורטים כאן להשלמת התיאור מאחר שאותם קורסים משרתים שני מסלולים).",
  },
  {
    id: "track-engineering-electives-pedagogy",
    name: "אשכול בחירה (מסלול הנדסי): חינוך, פדגוגיה ודידקטיקה",
    minCourses: 1,
    note: "יש לבחור לפחות קורס אחד מאשכול זה כחלק מ-3 קורסי הבחירה (6 נ\"ז) הנדרשים לתעודת הוראה במקצוע הנדסי (לפחות קורס אחד נוסף מאשכול חברה ותרבות).",
  },
  {
    id: "track-engineering-electives-society",
    name: "אשכול בחירה (מסלול הנדסי): חברה ותרבות",
    minCourses: 1,
    note: "יש לבחור לפחות קורס אחד מאשכול זה כחלק מ-3 קורסי הבחירה (6 נ\"ז) הנדרשים לתעודת הוראה במקצוע הנדסי.",
  },
  {
    id: "general-studies",
    name: "ב. לימודים כלליים",
    minCourses: 3,
    note: "כלל תלמידי ההנדסה לתואר B.Sc. נדרשים לצבור 6 נ\"ז מרשימה זו (בד\"כ 3 קורסים בני 2.0 נ\"ז); 4 נ\"ז בלבד למי שהחל לימודיו לפני תשע\"ז. חובת נוכחות 80%.",
  },
  {
    id: "sport",
    name: "ג. לימודי חינוך גופני / ספורט",
    minCourses: 1,
    note: "היקף חובת הספורט (בנ\"ז) נקבע בנפרד בכל מחלקה להנדסה. חובת נוכחות 80%. קורסי \"נבחרת\" מיועדים לספורטאי נבחרות ייצוגיות ומזכים בהיקף נ\"ז שונה (חלקם ללא נ\"ז, ראו זכאות למלגות).",
  },
];

const requirementGroups: RequirementGroup[] = [
  {
    code: "edu-philosophy-alt",
    name: "פילוסופיה של החינוך / דילמות פילוסופיות בחינוך",
    kind: "alternative",
    requiredCredits: 2,
    minCourses: 1,
    courseIds: ["81364", "81284"],
  },
  {
    code: "edu-sociology-alt",
    name: "סוציולוגיה של החינוך / סוציולוגיה בחינוך בראייה רב-תרבותית",
    kind: "alternative",
    requiredCredits: 2,
    minCourses: 1,
    courseIds: ["81365", "81282"],
  },
  {
    code: "edu-psych-intro-alt",
    name: "מבוא לפסיכולוגיה של החינוך / תלמידים בעלי צרכים מיוחדים",
    kind: "alternative",
    requiredCredits: 2,
    minCourses: 1,
    courseIds: ["81366", "81281"],
  },
  {
    code: "edu-adolescent-alt",
    name: "פסיכולוגיה של גיל ההתבגרות / התבגרות: דברים שרואים מפה לא רואים משם",
    kind: "alternative",
    requiredCredits: 2,
    minCourses: 1,
    courseIds: ["81367", "81283"],
  },
  {
    code: "edu-microteaching-alt",
    name: "מיקרו הוראה / מיומנויות הוראה",
    kind: "alternative",
    requiredCredits: 2,
    minCourses: 1,
    courseIds: ["81375", "81285"],
    metadata: { note: "שני הקורסים ניתנים ללמוד במקביל ל-81399 תורת ההוראה." },
  },
  {
    code: "edu-theory-teaching-alt",
    name: "תורת ההוראה, או השילוב הוראה מקדמת למידה + סוגיות בהוראה למידה והערכה",
    kind: "alternative",
    requiredCredits: 3,
    minCourses: 1,
    courseIds: ["81399", "81287", "81288"],
    metadata: { note: "81399 (3 נ\"ז) לבדו, לחלופין השילוב של 81287+81288 יחדיו (2+2 נ\"ז)." },
  },
  {
    code: "edu-evaluation-alt",
    name: "הערכה בחינוך / הערכה מקדמת למידה",
    kind: "alternative",
    requiredCredits: 3,
    minCourses: 1,
    courseIds: ["81398", "81289"],
  },
  {
    code: "edu-curriculum-alt",
    name: "פיתוח והערכה של תוכניות לימודים / תכנון לימודים בהוראת הנדסה ומתמטיקה",
    kind: "alternative",
    requiredCredits: 2,
    minCourses: 1,
    courseIds: ["81391", "81286"],
  },
  {
    code: "methodology-by-track",
    name: "מתודיקה של הוראת המקצוע ההנדסי (לפי מסלול ההנדסה של הסטודנט)",
    kind: "alternative",
    requiredCredits: 3,
    minCourses: 1,
    courseIds: ["81627", "85367", "85368", "85369"],
    metadata: { note: "הסטודנט לומד רק את קורס המתודיקה התואם את מסלול ההנדסה שבו למד; ניתן להחליף בקורס חליפי מתאים (\"דרכי הוראת...\")." },
  },
  {
    code: "methodology-math-alt",
    name: "מתודיקה של הוראת הגיאומטריה / מתודיקה של הוראת האלגברה",
    kind: "alternative",
    requiredCredits: 3,
    minCourses: 1,
    courseIds: ["81553", "81558"],
    metadata: { note: "שני הקורסים ניתנים ללמוד במקביל (\"גם\") ל-81399 תורת ההוראה ו-81375 מיקרו הוראה." },
  },
];

const rules: DegreeRule[] = [
  {
    id: "math-track-elective-pick-two",
    type: "selection_requirement",
    message: "במסגרת קורסי הבחירה לתעודת הוראה במתמטיקה יש לבחור שני קורסים מתוך: 81557 (הוראת המתמטיקה לתלמיד המצטיין), 81560 (הוכחות והנמקות בהוראת המתמטיקה), 81564 (היבטים פסיכולוגיים בהוראת המתמטיקה).",
    payload: {"courseIds":["81557","81560","81564"],"minSelected":2},
    enabled: true,
  },
  {
    id: "teaching-cert-classroom-or-digital-elective",
    type: "selection_requirement",
    message: "יש ללמוד קורס אחד מתוך שני זוגות חלופיים: 81551 ניווט כיתה (2 נ\"ז) או חלופתו 81291 סוגיות במנהיגות פדגוגית וניווט כיתה (3 נ\"ז); לעומת/או 81671 שילוב טכנולוגיות מתקדמות בהוראה והדרכה (2 נ\"ז) או חלופתו 81290 סוגיות בלמידה דיגיטלית בהנדסה ומתמטיקה (3 נ\"ז). דרישה זו חלה הן במסלול ההנדסי (כחלק מ-3 קורסי הבחירה) והן במסלול המתמטיקה (כקורס הבחירה הנוסף) והן במסלול המשולב (כקורס הבחירה בן 2 נ\"ז).",
    payload: {"courseIds":["81551","81291","81671","81290"],"minSelected":1},
    enabled: true,
  },
  {
    id: "engineering-cert-elective-cluster-min",
    type: "selection_requirement",
    message: "לתעודת הוראה במקצוע הנדסי: לימודי הבחירה כוללים 3 קורסים בהיקף כולל של 6 נ\"ז מהאשכולות \"חינוך, פדגוגיה ודידקטיקה\" ו-\"חברה ותרבות\", ויש לבחור לפחות קורס אחד מכל אשכול (לפחות אחד מחברה ותרבות).",
    payload: {"clusterIds":["track-engineering-electives-pedagogy","track-engineering-electives-society"],"minPerCluster":1,"totalCourses":3,"totalCredits":6},
    enabled: true,
  },
];

const courses: Course[] = [
  {
    id: "81364",
    name: "פילוסופיה של החינוך",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-philosophy-alt",
  },
  {
    id: "81284",
    name: "דילמות פילוסופיות בחינוך: הגות ומעשה",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-philosophy-alt",
  },
  {
    id: "81365",
    name: "סוציולוגיה של החינוך",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-sociology-alt",
  },
  {
    id: "81282",
    name: "סוציולוגיה בחינוך בראייה רב-תרבותית",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-sociology-alt",
  },
  {
    id: "81366",
    name: "מבוא לפסיכולוגיה של החינוך",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-psych-intro-alt",
  },
  {
    id: "81281",
    name: "תלמידים בעלי צרכים מיוחדים – השתלבות והכלה",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-psych-intro-alt",
    notes: [
      "קורס זה מופיע גם ברשימת קורסי הבחירה לתעודת הוראה במקצוע הנדסי (אשכול חברה ותרבות).",
    ],
  },
  {
    id: "81367",
    name: "פסיכולוגיה של גיל ההתבגרות",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-adolescent-alt",
  },
  {
    id: "81283",
    name: "התבגרות: דברים שרואים מפה לא רואים משם",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-adolescent-alt",
    notes: [
      "קורס זה מופיע גם ברשימת קורסי הבחירה לתעודת הוראה במקצוע הנדסי (אשכול חברה ותרבות).",
    ],
  },
  {
    id: "81399",
    name: "תורת ההוראה",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-theory-teaching-alt",
    notes: [
      "ניתן להחליף בשילוב 81287 הוראה מקדמת למידה (2 נ\"ז) + 81288 סוגיות בהוראה למידה והערכה (2 נ\"ז).",
    ],
  },
  {
    id: "81375",
    name: "מיקרו הוראה",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-microteaching-alt",
    coRequisites: ["81399"],
    notes: [
      "ניתן ללמוד במקביל ל-81399 תורת ההוראה.",
    ],
  },
  {
    id: "81285",
    name: "מיומנויות הוראה",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-microteaching-alt",
    coRequisites: ["81399"],
    notes: [
      "ניתן ללמוד במקביל ל-81399 תורת ההוראה.",
      "קורס זה מופיע גם ברשימת קורסי הבחירה לתעודת הוראה במקצוע הנדסי (אשכול חינוך, פדגוגיה ודידקטיקה).",
    ],
  },
  {
    id: "81398",
    name: "הערכה בחינוך",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-evaluation-alt",
    prerequisites: [
      { mode: "all", ids: ["81399", "81375"] },
    ],
    notes: [
      "ניתן להחליף ב-81289 הערכה מקדמת למידה (2 נ\"ז).",
    ],
  },
  {
    id: "81385",
    name: "סמינר במחקר חינוכי",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    prerequisites: [
      { mode: "all", ids: ["81399"] },
    ],
  },
  {
    id: "81391",
    name: "פיתוח והערכה של תוכניות לימודים",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-curriculum-alt",
    prerequisites: [
      { mode: "all", ids: ["81399"] },
    ],
  },
  {
    id: "81286",
    name: "תכנון לימודים בהוראת הנדסה ומתמטיקה",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    requirementGroup: "edu-curriculum-alt",
    prerequisites: [
      { mode: "all", ids: ["81399"] },
    ],
    notes: [
      "קורס זה מופיע גם ברשימת קורסי הבחירה לתעודת הוראה במקצוע הנדסי (אשכול חינוך, פדגוגיה ודידקטיקה).",
    ],
  },
  {
    id: "81393",
    name: "שיטות מחקר איכותניות",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    prerequisites: [
      { mode: "all", ids: ["81399"] },
    ],
  },
  {
    id: "81372",
    name: "ביטחון ובטיחות (השתלמות)",
    credits: 0,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    notes: [
      "השתלמות ללא נ\"ז.",
    ],
  },
  {
    id: "81373",
    name: "עזרה ראשונה (השתלמות)",
    credits: 0,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    notes: [
      "השתלמות ללא נ\"ז.",
    ],
  },
  {
    id: "81537",
    name: "זהירות בדרכים (השתלמות)",
    credits: 0,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    notes: [
      "השתלמות ללא נ\"ז.",
    ],
  },
  {
    id: "81360",
    name: "הבעה עברית",
    credits: 0,
    type: "required",
    required: true,
    clusterId: "track-shared-core",
    notes: [
      "השתלמות ללא נ\"ז. ציון עובר 75 מזכה בפטור מהקורס.",
    ],
  },
  {
    id: "81627",
    name: "מתודיקה של הוראת מדעי המחשב",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-engineering",
    requirementGroup: "methodology-by-track",
    prerequisites: [
      { mode: "all", ids: ["81399", "81375"] },
    ],
    notes: [
      "ניתן להחליף בקורס חליפי מתאים למסלול ההנדסי (\"דרכי הוראת...\").",
    ],
  },
  {
    id: "85367",
    name: "מתודיקה של הוראת ביוטכנולוגיה",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-engineering",
    requirementGroup: "methodology-by-track",
    prerequisites: [
      { mode: "all", ids: ["81399", "81375"] },
    ],
  },
  {
    id: "85368",
    name: "מתודיקה של הוראת תעשייה וניהול",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-engineering",
    requirementGroup: "methodology-by-track",
    prerequisites: [
      { mode: "all", ids: ["81399", "81375"] },
    ],
  },
  {
    id: "85369",
    name: "מתודיקה של הוראת אלקטרוניקה ומכונות",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-engineering",
    requirementGroup: "methodology-by-track",
    prerequisites: [
      { mode: "all", ids: ["81399", "81375"] },
    ],
  },
  {
    id: "81320",
    name: "למידה מבוססת פרויקטים בחינוך ההנדסי",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-engineering",
    prerequisites: [
      { mode: "all", ids: ["81399", "81375"] },
    ],
    notes: [
      "קורס זה מופיע גם ברשימת הקורסים הנוספים לתעודת הוראה משולבת (track-combined).",
    ],
  },
  {
    id: "81383",
    name: "התנסות מעשית 1",
    credits: 6,
    type: "required",
    required: true,
    clusterId: "track-engineering",
    prerequisites: [
      { mode: "all", ids: ["81399", "81375"] },
      { mode: "any", ids: ["81627", "85367", "85368", "85369", "81553", "81558"], label: "מתודיקה מתאימה למסלול הלימוד (הנדסי או מתמטיקה)" },
    ],
    notes: [
      "דרישת הקדם המדויקת תלויה במסלול: תעודת הוראה במקצוע הנדסי דורשת אחת ממתודיקות ההנדסה (81627/85367/85368/85369); תעודת הוראה במתמטיקה דורשת אחת ממתודיקות המתמטיקה (81553/81558).",
    ],
  },
  {
    id: "81387",
    name: "התנסות מעשית 2",
    credits: 6,
    type: "required",
    required: true,
    clusterId: "track-engineering",
    prerequisites: [
      { mode: "all", ids: ["81383"] },
    ],
  },
  {
    id: "81553",
    name: "מתודיקה של הוראת הגיאומטריה",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-math",
    requirementGroup: "methodology-math-alt",
    coRequisites: ["81399", "81375"],
    notes: [
      "ניתן ללמוד במקביל ל-81399 תורת ההוראה ו-81375 מיקרו הוראה.",
      "קורס זה מופיע גם ברשימת הקורסים הנוספים לתעודת הוראה משולבת ולהרחבת הסמכה במתמטיקה.",
    ],
  },
  {
    id: "81558",
    name: "מתודיקה של הוראת האלגברה",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-math",
    requirementGroup: "methodology-math-alt",
    coRequisites: ["81399", "81375"],
    notes: [
      "ניתן ללמוד במקביל ל-81399 תורת ההוראה ו-81375 מיקרו הוראה.",
      "קורס זה מופיע גם ברשימת הקורסים הנוספים לתעודת הוראה משולבת ולהרחבת הסמכה במתמטיקה.",
    ],
  },
  {
    id: "81401",
    name: "התנסות מעשית בהוראת ההנדסה ומתמטיקה – 1",
    credits: 9,
    type: "required",
    required: true,
    clusterId: "track-combined",
    prerequisites: [
      { mode: "all", ids: ["81399", "81375"] },
      { mode: "any", ids: ["81553", "81558"], label: "מתודיקה של הוראת הגיאומטריה או האלגברה" },
      { mode: "any", ids: ["81627", "85367", "85368", "85369"], label: "מתודיקה בהוראת המקצוע ההנדסי (לפי המסלול ההנדסי אותו למד הסטודנט)" },
    ],
  },
  {
    id: "81402",
    name: "התנסות מעשית בהוראת ההנדסה ומתמטיקה – 2",
    credits: 9,
    type: "required",
    required: true,
    clusterId: "track-combined",
    prerequisites: [
      { mode: "all", ids: ["81401"] },
    ],
    notes: [
      "קורס זה מופיע גם ברשימת קורסי הרחבת ההסמכה לתעודת הוראה במתמטיקה, בהנחה ש-81401 כבר הושלם כחלק מתעודת ההוראה ההנדסית הקודמת.",
    ],
  },
  {
    id: "81410",
    name: "נושאים בגיאומטריה 1",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-combined",
  },
  {
    id: "81411",
    name: "נושאים בגיאומטריה 2",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-combined",
  },
  {
    id: "81556",
    name: "טופולוגיה",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-combined",
  },
  {
    id: "81557",
    name: "הוראת המתמטיקה לתלמיד המצטיין",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-combined",
    notes: [
      "אחד מ-3 קורסים (עם 81560, 81564) שמתוכם יש לבחור 2 כקורסי בחירה במסלול תעודת הוראה במתמטיקה בלבד (ראו rules).",
    ],
  },
  {
    id: "81560",
    name: "הוכחות והנמקות בהוראת המתמטיקה",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-combined",
    notes: [
      "אחד מ-3 קורסים (עם 81557, 81564) שמתוכם יש לבחור 2 כקורסי בחירה במסלול תעודת הוראה במתמטיקה בלבד (ראו rules).",
    ],
  },
  {
    id: "81561",
    name: "נושאים מתמטיים נבחרים למורים למתמטיקה",
    credits: 3,
    type: "required",
    required: true,
    clusterId: "track-combined",
  },
  {
    id: "81564",
    name: "היבטים פסיכולוגיים בהוראת המתמטיקה",
    credits: 2,
    type: "required",
    required: true,
    clusterId: "track-combined",
    notes: [
      "אחד מ-3 קורסים (עם 81557, 81560) שמתוכם יש לבחור 2 כקורסי בחירה במסלול תעודת הוראה במתמטיקה בלבד (ראו rules).",
      "קורס זה מופיע גם ברשימת קורסי הבחירה לתעודת הוראה במקצוע הנדסי (אשכול חינוך, פדגוגיה ודידקטיקה).",
    ],
  },
  {
    id: "81287",
    name: "הוראה מקדמת למידה: תיאוריה ומעשה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81288",
    name: "סוגיות בהוראה למידה והערכה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81289",
    name: "הערכה מקדמת למידה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81290",
    name: "סוגיות בלמידה דיגיטלית בהנדסה ומתמטיקה",
    credits: 3,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81291",
    name: "סוגיות במנהיגות פדגוגית וניווט כיתה",
    credits: 3,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81301",
    name: "טכניקה, הבנה מתמטית ומה שביניהן",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81500",
    name: "הוראה בגישת חקר",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81522",
    name: "סוגיות ערכיות בחינוך",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81527",
    name: "מנהיגות חינוכית",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81543",
    name: "פסיכולוגיה של הלמידה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81545",
    name: "טכנולוגיות למידה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81551",
    name: "ניווט כיתה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
    notes: [
      "כפוף לדרישת הבחירה 'teaching-cert-classroom-or-digital-elective' (ראו rules).",
    ],
  },
  {
    id: "81552",
    name: "למידה סביב פרויקטים",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81554",
    name: "למידה בסביבת רובוטים",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81604",
    name: "מדידה והערכה בחינוך",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
  },
  {
    id: "81671",
    name: "שילוב טכנולוגיות מתקדמות בהוראה והדרכה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-pedagogy",
    notes: [
      "כפוף לדרישת הבחירה 'teaching-cert-classroom-or-digital-elective' (ראו rules).",
    ],
  },
  {
    id: "81352",
    name: "פילוסופיה של המדע",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81392",
    name: "החברה הישראלית בימינו",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81394",
    name: "מגלות לתקומה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81395",
    name: "יחסים בין קבוצות בחברה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81397",
    name: "תהליכי שינוי: התמודדות הפרט והארגון",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81417",
    name: "למה לי אמנות?",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81502",
    name: "שוויון הזדמנויות בחינוך",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81503",
    name: "מסרים סמויים בחינוך",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81507",
    name: "מגדר וחינוך",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81538",
    name: "המיעוט הערבי בישראל",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81541",
    name: "המשפחה במקרא",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81542",
    name: "הצצה אל עולם המשפט – עקרון השוויון ויחסי עבודה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81546",
    name: "היסטוריה של המדע (קורס מקוון)",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81548",
    name: "ביואתיקה – מבוא למשתמשים",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81563",
    name: "הזכות לשוויון במשפט הישראלי",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81565",
    name: "רעיונות יסוד במחשבת היהדות",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81566",
    name: "גברים ונשים בעידן המודרני",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81567",
    name: "משפחה והולדה בעידן טכנולוגי",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81568",
    name: "עולמם של חכמים במסכת אבות",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81569",
    name: "בנים חכמים בנות חרוצות?",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81572",
    name: "אשנב לאקולוגיה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81573",
    name: "מיומנויות בתקשורת בינאישית",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81574",
    name: "המוח הלומד",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81575",
    name: "מובילי אורח חיים בריא",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81577",
    name: "למידה ומעורבות ברשתות חברתיות (קורס מקוון היברידי)",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81578",
    name: "חינוך וטכנולוגיה בעידן המהפכה התעשייתית",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81667",
    name: "אמנות הסיפור הקצר",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81668",
    name: "למה דברים רעים קורים לאנשים טובים",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81669",
    name: "שוברים את הכללים – להבין אמנות מודרנית",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81670",
    name: "אשנב לאסטרונומיה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81874",
    name: "קבלת השונות - Embracing Diversity (קורס מקוון)",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "81875",
    name: "אינטליגנציה בבני אדם",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85364",
    name: "הנדסה אקולוגית בחיי היום יום",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85365",
    name: "קיימות למהנדסים",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85375",
    name: "פרשיות סוערות במשפט ישראלי",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85378",
    name: "ההיסטוריה חוזרת?",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85380",
    name: "חינוך לקיימות דרך קולנוע",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85383",
    name: "אגדות חז\"ל: היו היה, או נכון לעכשיו?",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85385",
    name: "מניוטון לאיינשטיין (קורס מקוון)",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85386",
    name: "אחריות מקצועית - דילמות וחוק",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "85400",
    name: "Ethics in Engineering - אתיקה בהנדסה",
    credits: 2,
    type: "elective",
    clusterId: "track-engineering-electives-society",
  },
  {
    id: "11280",
    name: "חינוך לקיימות דרך קולנוע",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11281",
    name: "תלמידים בעלי צרכים מיוחדים - השתלבות",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11282",
    name: "סוציולוגיה בחינוך בראייה רב-תרבותית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11283",
    name: "התבגרות - דברים שרואים מפה לא רואים משם",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11314",
    name: "גבריות ונשיות בעידן המודרני",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11318",
    name: "פסיכולוגיה של גיל ההתבגרות",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11322",
    name: "ספרדית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11323",
    name: "צרפתית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11327",
    name: "סדנא בתקשורת בין אישית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11329",
    name: "ערבית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11336",
    name: "מגלות לתקומה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11337",
    name: "יחסים בין קבוצות בחברה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11340",
    name: "תהליכי שינוי: התמודדות הפרט והארגון",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11341",
    name: "סינית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11347",
    name: "גברים ונשים בעידן המודרני",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11348",
    name: "משפחה והולדה בעידן טכנולוגי",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11351",
    name: "אוריינות עברית",
    credits: 0,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11352",
    name: "פילוסופיה של המדע",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11370",
    name: "Ethics of the Fathers - אתיקה של האבות",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11375",
    name: "פרשיות סוערות במשפט הישראלית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11378",
    name: "ההיסטוריה חוזרת?",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11386",
    name: "אחריות מקצועית-דילמות וחוק",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11416",
    name: "טכנולוגיות מים",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11483",
    name: "אגדות חז\"ל: היה היה, או נכון לעכשיו?",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11485",
    name: "מניוטון לאיינשטיין (קורס מקוון)",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11565",
    name: "רעיונות יסוד במחשבת היהדות",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11568",
    name: "עולמם של חכמים במסכת אבות",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11569",
    name: "בנים חכמים בנות חרוצות",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11572",
    name: "אשנב לאקולוגיה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11573",
    name: "מיומנויות בתקשורת בינאישית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11574",
    name: "המוח הלומד",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11575",
    name: "מובילי אורח חיים בריא",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11577",
    name: "למידה ומעורבות ברשתות חברתיות (קורס מקוון היברידי)",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11578",
    name: "חינוך וטכנולוגיה בעידן המהפכה התעשייתית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11801",
    name: "סוציולוגיה של החינוך",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11802",
    name: "מבוא לפסיכולוגיה של החינוך",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11804",
    name: "פילוסופיה של החינוך",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11805",
    name: "מיומנויות הנחיה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11809",
    name: "סוציולוגיה של הילדות",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11810",
    name: "מסרים סמויים בחינוך",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11816",
    name: "החברה הישראלית בימינו",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11819",
    name: "סוגיות ערכיות בחינוך",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11830",
    name: "המיעוט הערבי בישראל",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11833",
    name: "ביואתיקה – מבוא למשתמשים",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11834",
    name: "סגנונות מוזיקליים במאה ה-20",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11835",
    name: "סדנה בתכנון והצגת נושא – פרזנטציה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11839",
    name: "Myth and Legends - מיתוס ואגדה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11840",
    name: "המשפחה במקרא",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11841",
    name: "הצצה אל עולם המשפט – עקרון השוויון ויחסי עבודה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11842",
    name: "פסיכולוגיה של הלמידה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11843",
    name: "תרבות-מורשת עם וחינוך לאזרחות",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11844",
    name: "טכנולוגיות למידה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11845",
    name: "היסטוריה של המדע (קורס מקוון)",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11848",
    name: "הוראה בגישת חקר",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11852",
    name: "טכניקה, הבנה מתמטית ומה שביניהן",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11855",
    name: "גרמנית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11858",
    name: "קיימות למהנדסים",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11862",
    name: "הזכות לשוויון במשפט הישראלי",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11867",
    name: "אמנות הסיפור הקצר",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11868",
    name: "למה דברים רעים קורים לאנשים טובים",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11869",
    name: "שוברים את הכללים – להבין אמנות מודרנית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11870",
    name: "אשנב לאסטרונומיה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11874",
    name: "קבלת השונות - Embracing Diversity (קורס מקוון)",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11875",
    name: "אינטליגנציה בבני אדם",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11877",
    name: "Ethics in Engineering - אתיקה בהנדסה",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11898",
    name: "נשים פורצות דרך",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11899",
    name: "Advancing Global Health Through Engineering - קידום הבריאות הגלובלית",
    credits: 2,
    type: "elective",
    clusterId: "general-studies",
  },
  {
    id: "11070",
    name: "טניס",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11071",
    name: "טניס נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11073",
    name: "טניס שולחן",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11074",
    name: "טניס שולחן נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11075",
    name: "כדורסל",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11076",
    name: "כדורסל נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11078",
    name: "שחייה נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11079",
    name: "קט-רגל נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11081",
    name: "קראטה",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11082",
    name: "קראטה נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11083",
    name: "יוגה",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11085",
    name: "עיצוב הגוף ואירובי",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11086",
    name: "קט רגל",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11089",
    name: "אגרוף תאילנדי",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11091",
    name: "ספורט 1",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11092",
    name: "ספורט 2",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11094",
    name: "זומבה",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11096",
    name: "פלדנקרייז",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11097",
    name: "כדורסל נשים",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11098",
    name: "כדור עף",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11402",
    name: "הגנה עצמית - נשים",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11403",
    name: "כדור עף נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11404",
    name: "מבוא לחדר כושר",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11406",
    name: "שחמט נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11407",
    name: "הליכה ספורטיבית",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11408",
    name: "טיפוח יציבה",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11409",
    name: "טיפוח יציבה מעורב",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11410",
    name: "ריצות ארוכות נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11411",
    name: "טניס שדה למתקדמים",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11412",
    name: "קיק בוקסינג",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11424",
    name: "טייצ'י",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11425",
    name: "כדורסל נשים נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11426",
    name: "אופניים נבחרת",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11427",
    name: "פילאטיס",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11428",
    name: "כדורשת נשים",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11429",
    name: "כדורגל נבחרת",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11430",
    name: "בולדרינג (קיר טיפוס)",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11431",
    name: "שחמט",
    credits: 1,
    type: "sport",
    clusterId: "sport",
  },
  {
    id: "11490",
    name: "מועדון דיבייט",
    credits: 0,
    type: "sport",
    clusterId: "sport",
  },
];

export const degreePlan: DegreePlan = {
  id: "teaching-general-studies",
  title: "הוראה ולימודים כלליים",
  subtitle: "המכללה האקדמית להנדסה בראודה - קטלוג משלים: מסלולי תעודת הוראה, לימודים כלליים וספורט (אינו תואר עצמאי)",
  source: {
    fileName: "ידיעונים, שנתונים ולוח שנה אקדמית - בראודה.pdf",
    pages: "180-196",
    extractedAt: "2026-07-10",
  },
  requirements: {
    totalCredits: 0,
    fixedDegreeCredits: 0,
    electiveCreditsNeeded: 0,
    generalCredits: 6,
    sportCredits: 1,
    englishRequiredIds: [],
  },
  courseTypes: [
    { code: "required", label: "חובה", sortOrder: 0 },
    { code: "elective", label: "בחירה", sortOrder: 1 },
    { code: "sport", label: "ספורט", sortOrder: 2 },
  ],
  requirementGroups,
  clusters,
  courses,
  rules,
  notes: [
    "תוכנית זו אינה תואר עצמאי בעל רצף 8 סמסטרים, אלא קטלוג משלים (supplementary catalog) המנוהל ע\"י היחידה להוראה, המציע מסלולי תעודת הוראה, לימודים כלליים וספורט הנדרשים כחלק מתארי הנדסה אחרים במכללה - ולכן אין לו מבנה סמסטריאלי קבוע (שדה semester הושמט ברוב הקורסים).",
    "לתעודת הוראה במקצוע הנדסי אחד או במתמטיקה בלבד נדרשים 48 נ\"ז; לתעודת הוראה משולבת (מקצוע הנדסי + מתמטיקה) נדרשים 71 נ\"ז; להרחבת הסמכה להוראת מתמטיקה לבעלי תעודת הוראה הנדסית קיימת נדרשים 28 נ\"ז נוספים. אין ערך יחיד ל'סך נ\"ז לתואר' עבור תוכנית משלימה זו, ולכן requirements.totalCredits הוגדר כ-0 (ראו notes נוספים).",
    "כלל תלמידי ההנדסה לתואר B.Sc. נדרשים ל-6 נ\"ז לימודים כלליים (4 נ\"ז למי שהחל לפני תשע\"ז) מתוך רשימת הקורסים הכלליים; היקף חובת הספורט (בנ\"ז) נקבע בנפרד בכל מחלקה להנדסה.",
    "תנאי קבלה ללימודי הוראה: ממוצע ציונים 70 ומעלה (החל מהשנה השנייה ללימודים), או תואר אקדמי קיים בתחום קרוב בממוצע 70 ומעלה; קבלת התעודה מותנית בסיום התואר בציון 70 ומעלה. קבלה מותנית בראיון אישי.",
    "ציוני עובר: 65 בקורסי הוראה, 70 בקורסי התנסות מעשית, 75 בהבעה עברית (מזכה בפטור מהקורס).",
    "קורסי המתודיקה (81627/85367/85368/85369) ניתנים להחלפה בקורסים חליפיים שייקראו \"דרכי הוראת ה-...\" עבור ביוטכנולוגיה, מדעי המחשב, תעשייה וניהול, או אלקטרוניקה ומכונות.",
    "81399 תורת ההוראה ניתן להחלפה בשילוב 81287 הוראה מקדמת למידה + 81288 סוגיות בהוראה למידה והערכה (2 נ\"ז כל אחד); 81398 הערכה בחינוך ניתן להחלפה ב-81289 הערכה מקדמת למידה (2 נ\"ז).",
    "בניגוד לתוכניות ההנדסיות במכללה (בהן צמידות קורסים מסומנת בקו תחתון), פרק זה בשנתון מסמן קורס צמוד (\"ניתן ללמוד במקביל\") באמצעות הערה מפורשת בסוגריים תחת שם הקורס בטבלה; שבעה זוגות צמידות כאלה אותרו: 81375/81285 → 81399; 81553 → 81399+81375; 81558 → 81399+81375 (חוזרים בטבלאות 1, 3, 4, 5).",
    "טבלה 6 (קורסי בחירה לתעודת הוראה במקצוע הנדסי) וכן פרקי הלימודים הכלליים והספורט אינם כוללים כלל עמודת קורסי קדם במקור - קורסים אלו מוזנים ללא prerequisites בהתאם למקור.",
    "המסמך הרשמי עשוי להשתנות (עדכוני מתווה ודמן-ענבר); המחשבון הוא כלי עזר לתכנון ולא אישור זכאות רשמי.",
  ],
};
